// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type JournalConsumerPosition struct {
	ZoneID     string
	ConsumerID string
	EventType  string
	Position   int64
}

type JournalEvent struct {
	EventID        string
	ZoneID         string
	StreamID       string
	StreamSequence int64
	EventType      string
	EventSequence  int64
	SchemaVersion  int64
	OccurredAt     string
	CorrelationID  string
	CausationID    string
	Body           string
}

type JournalSchema struct {
	ID      int64
	Version int64
}
