// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AdvanceConsumerPosition(ctx context.Context, arg AdvanceConsumerPositionParams) (int64, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) error
	EnsureConsumerPosition(ctx context.Context, arg EnsureConsumerPositionParams) error
	GetConsumerPosition(ctx context.Context, arg GetConsumerPositionParams) (int64, error)
	// These named statements are the sole generated CRUD source for Journal persistence.
	GetEventByID(ctx context.Context, eventID string) (JournalEvent, error)
	GetEventTypePosition(ctx context.Context, arg GetEventTypePositionParams) (int64, error)
	GetLastStreamSequence(ctx context.Context, arg GetLastStreamSequenceParams) (int64, error)
	GetPendingConsumerZone(ctx context.Context, arg GetPendingConsumerZoneParams) (string, error)
	GetSchemaVersion(ctx context.Context) (int64, error)
	ListEventTypeEvents(ctx context.Context, arg ListEventTypeEventsParams) ([]JournalEvent, error)
	ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]JournalEvent, error)
	ListStreamEventsAfter(ctx context.Context, arg ListStreamEventsAfterParams) ([]JournalEvent, error)
	ReadPendingEvents(ctx context.Context, arg ReadPendingEventsParams) (ReadPendingEventsRow, error)
	ValidateSchema(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
