// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statements.sql

package db

import (
	"context"
)

const advanceConsumerPosition = `-- name: AdvanceConsumerPosition :execrows
UPDATE journal_consumer_positions
SET position = ?1
WHERE zone_id = ?2
  AND consumer_id = ?3
  AND event_type = ?4
  AND position = ?5
`

type AdvanceConsumerPositionParams struct {
	Position         int64
	ZoneID           string
	ConsumerID       string
	EventType        string
	ExpectedPosition int64
}

func (q *Queries) AdvanceConsumerPosition(ctx context.Context, arg AdvanceConsumerPositionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceConsumerPosition,
		arg.Position,
		arg.ZoneID,
		arg.ConsumerID,
		arg.EventType,
		arg.ExpectedPosition,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO journal_events (
    event_id,
    zone_id,
    stream_id,
    stream_sequence,
    event_type,
    event_sequence,
    schema_version,
    occurred_at,
    correlation_id,
    causation_id,
    body
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateEventParams struct {
	EventID        string
	ZoneID         string
	StreamID       string
	StreamSequence int64
	EventType      string
	EventSequence  int64
	SchemaVersion  int64
	OccurredAt     string
	CorrelationID  string
	CausationID    string
	Body           string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.EventID,
		arg.ZoneID,
		arg.StreamID,
		arg.StreamSequence,
		arg.EventType,
		arg.EventSequence,
		arg.SchemaVersion,
		arg.OccurredAt,
		arg.CorrelationID,
		arg.CausationID,
		arg.Body,
	)
	return err
}

const ensureConsumerPosition = `-- name: EnsureConsumerPosition :exec
INSERT INTO journal_consumer_positions (zone_id, consumer_id, event_type, position)
VALUES (
    ?1,
    ?2,
    ?3,
    0
)
ON CONFLICT (zone_id, consumer_id, event_type) DO NOTHING
`

type EnsureConsumerPositionParams struct {
	ZoneID     string
	ConsumerID string
	EventType  string
}

func (q *Queries) EnsureConsumerPosition(ctx context.Context, arg EnsureConsumerPositionParams) error {
	_, err := q.db.ExecContext(ctx, ensureConsumerPosition, arg.ZoneID, arg.ConsumerID, arg.EventType)
	return err
}

const getConsumerPosition = `-- name: GetConsumerPosition :one
SELECT position
FROM journal_consumer_positions
WHERE zone_id = ?1
  AND consumer_id = ?2
  AND event_type = ?3
`

type GetConsumerPositionParams struct {
	ZoneID     string
	ConsumerID string
	EventType  string
}

func (q *Queries) GetConsumerPosition(ctx context.Context, arg GetConsumerPositionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getConsumerPosition, arg.ZoneID, arg.ConsumerID, arg.EventType)
	var position int64
	err := row.Scan(&position)
	return position, err
}

const getEventByID = `-- name: GetEventByID :one
SELECT event_id, zone_id, stream_id, stream_sequence, event_type, event_sequence, schema_version, occurred_at, correlation_id, causation_id, body
FROM journal_events
WHERE event_id = ?
`

// These named statements are the sole generated CRUD source for Journal persistence.
func (q *Queries) GetEventByID(ctx context.Context, eventID string) (JournalEvent, error) {
	row := q.db.QueryRowContext(ctx, getEventByID, eventID)
	var i JournalEvent
	err := row.Scan(
		&i.EventID,
		&i.ZoneID,
		&i.StreamID,
		&i.StreamSequence,
		&i.EventType,
		&i.EventSequence,
		&i.SchemaVersion,
		&i.OccurredAt,
		&i.CorrelationID,
		&i.CausationID,
		&i.Body,
	)
	return i, err
}

const getEventTypePosition = `-- name: GetEventTypePosition :one
SELECT CAST(COALESCE(MAX(event_sequence) + 1, 0) AS INTEGER)
FROM journal_events
WHERE zone_id = ?1 AND event_type = ?2
`

type GetEventTypePositionParams struct {
	ZoneID    string
	EventType string
}

func (q *Queries) GetEventTypePosition(ctx context.Context, arg GetEventTypePositionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getEventTypePosition, arg.ZoneID, arg.EventType)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getLastStreamSequence = `-- name: GetLastStreamSequence :one
SELECT CAST(COALESCE(MAX(stream_sequence), 0) AS INTEGER)
FROM journal_events
WHERE zone_id = ? AND stream_id = ?
`

type GetLastStreamSequenceParams struct {
	ZoneID   string
	StreamID string
}

func (q *Queries) GetLastStreamSequence(ctx context.Context, arg GetLastStreamSequenceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getLastStreamSequence, arg.ZoneID, arg.StreamID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getPendingConsumerZone = `-- name: GetPendingConsumerZone :one
SELECT events.zone_id
FROM journal_events AS events
LEFT JOIN journal_consumer_positions AS positions
  ON positions.zone_id = events.zone_id
 AND positions.consumer_id = ?1
 AND positions.event_type = events.event_type
WHERE events.event_type = ?2
  AND events.schema_version = ?3
  AND events.event_sequence >= COALESCE(positions.position, 0)
GROUP BY events.zone_id
ORDER BY MIN(events.occurred_at), events.zone_id
LIMIT 1
`

type GetPendingConsumerZoneParams struct {
	ConsumerID    string
	EventType     string
	SchemaVersion int64
}

func (q *Queries) GetPendingConsumerZone(ctx context.Context, arg GetPendingConsumerZoneParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPendingConsumerZone, arg.ConsumerID, arg.EventType, arg.SchemaVersion)
	var zone_id string
	err := row.Scan(&zone_id)
	return zone_id, err
}

const getSchemaVersion = `-- name: GetSchemaVersion :one
SELECT version
FROM journal_schema
WHERE id = 1
`

func (q *Queries) GetSchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSchemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const listEventTypeEvents = `-- name: ListEventTypeEvents :many
SELECT event_id, zone_id, stream_id, stream_sequence, event_type, event_sequence, schema_version, occurred_at, correlation_id, causation_id, body
FROM journal_events
WHERE zone_id = ?1
  AND event_type = ?2
  AND event_sequence >= ?3
ORDER BY event_sequence
LIMIT ?4
`

type ListEventTypeEventsParams struct {
	ZoneID    string
	EventType string
	Position  int64
	ReadLimit int64
}

func (q *Queries) ListEventTypeEvents(ctx context.Context, arg ListEventTypeEventsParams) ([]JournalEvent, error) {
	rows, err := q.db.QueryContext(ctx, listEventTypeEvents,
		arg.ZoneID,
		arg.EventType,
		arg.Position,
		arg.ReadLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalEvent{}
	for rows.Next() {
		var i JournalEvent
		if err := rows.Scan(
			&i.EventID,
			&i.ZoneID,
			&i.StreamID,
			&i.StreamSequence,
			&i.EventType,
			&i.EventSequence,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalEntries = `-- name: ListJournalEntries :many
SELECT event_id, zone_id, stream_id, stream_sequence, event_type, event_sequence, schema_version, occurred_at, correlation_id, causation_id, body
FROM journal_events
WHERE zone_id = ?1
ORDER BY event_type, event_sequence
LIMIT ?3 OFFSET ?2
`

type ListJournalEntriesParams struct {
	ZoneID      string
	EntryOffset int64
	ReadLimit   int64
}

func (q *Queries) ListJournalEntries(ctx context.Context, arg ListJournalEntriesParams) ([]JournalEvent, error) {
	rows, err := q.db.QueryContext(ctx, listJournalEntries, arg.ZoneID, arg.EntryOffset, arg.ReadLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalEvent{}
	for rows.Next() {
		var i JournalEvent
		if err := rows.Scan(
			&i.EventID,
			&i.ZoneID,
			&i.StreamID,
			&i.StreamSequence,
			&i.EventType,
			&i.EventSequence,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStreamEventsAfter = `-- name: ListStreamEventsAfter :many
SELECT event_id, zone_id, stream_id, stream_sequence, event_type, event_sequence, schema_version, occurred_at, correlation_id, causation_id, body
FROM journal_events
WHERE zone_id = ? AND stream_id = ? AND stream_sequence > ?
ORDER BY stream_sequence
LIMIT ?
`

type ListStreamEventsAfterParams struct {
	ZoneID         string
	StreamID       string
	StreamSequence int64
	Limit          int64
}

func (q *Queries) ListStreamEventsAfter(ctx context.Context, arg ListStreamEventsAfterParams) ([]JournalEvent, error) {
	rows, err := q.db.QueryContext(ctx, listStreamEventsAfter,
		arg.ZoneID,
		arg.StreamID,
		arg.StreamSequence,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JournalEvent{}
	for rows.Next() {
		var i JournalEvent
		if err := rows.Scan(
			&i.EventID,
			&i.ZoneID,
			&i.StreamID,
			&i.StreamSequence,
			&i.EventType,
			&i.EventSequence,
			&i.SchemaVersion,
			&i.OccurredAt,
			&i.CorrelationID,
			&i.CausationID,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readPendingEvents = `-- name: ReadPendingEvents :one
SELECT
    CAST(COALESCE(MAX(event_sequence) + 1, 0) AS INTEGER) AS event_type_position,
    CAST(COUNT(CASE
        WHEN schema_version = ?1
         AND event_sequence >= ?2
        THEN 1
    END) AS INTEGER) AS event_count,
    MIN(CASE
        WHEN schema_version = ?1
         AND event_sequence >= ?2
        THEN occurred_at
    END) AS pending_since
FROM journal_events INDEXED BY journal_events_by_zone_key_sequence
WHERE zone_id = ?3
  AND event_type = ?4
`

type ReadPendingEventsParams struct {
	SchemaVersion int64
	EventSequence int64
	ZoneID        string
	EventType     string
}

type ReadPendingEventsRow struct {
	EventTypePosition int64
	EventCount        int64
	PendingSince      interface{}
}

func (q *Queries) ReadPendingEvents(ctx context.Context, arg ReadPendingEventsParams) (ReadPendingEventsRow, error) {
	row := q.db.QueryRowContext(ctx, readPendingEvents,
		arg.SchemaVersion,
		arg.EventSequence,
		arg.ZoneID,
		arg.EventType,
	)
	var i ReadPendingEventsRow
	err := row.Scan(&i.EventTypePosition, &i.EventCount, &i.PendingSince)
	return i, err
}

const validateSchema = `-- name: ValidateSchema :one
SELECT
    (SELECT
        count(event_id) +
        count(zone_id) +
        count(stream_id) +
        count(stream_sequence) +
        count(event_type) +
        count(event_sequence) +
        count(schema_version) +
        count(occurred_at) +
        count(correlation_id) +
        count(causation_id) +
        count(body)
     FROM journal_events INDEXED BY journal_events_by_stream
     WHERE 0) +
    (SELECT count(event_sequence)
     FROM journal_events INDEXED BY journal_events_by_zone_key_sequence
     WHERE 0) +
    (SELECT count(zone_id) + count(consumer_id) + count(event_type) + count(position)
     FROM journal_consumer_positions
     WHERE 0) +
    (SELECT count(id) + count(version)
     FROM journal_schema
     WHERE 0) AS valid
`

func (q *Queries) ValidateSchema(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, validateSchema)
	var valid int64
	err := row.Scan(&valid)
	return valid, err
}
