// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type CurrentEpoch struct {
	ZoneID  string
	EpochID int64
}

type Epoch struct {
	ZoneID          string
	ID              int64
	KnowledgeDigest string
	CorporaID       string
	StructureID     string
	PublishedAt     string
}

type EpochClaimVersion struct {
	ZoneID  string
	EpochID int64
	ClaimID string
	Version int64
}

type EpochEntityVersion struct {
	ZoneID   string
	EpochID  int64
	EntityID string
	Version  int64
}

type EpochRelationVersion struct {
	ZoneID     string
	EpochID    int64
	RelationID string
	Version    int64
}

type EpochSchema struct {
	ID      int64
	Version int64
}
