// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddEpochClaimVersion(ctx context.Context, arg AddEpochClaimVersionParams) error
	AddEpochEntityVersion(ctx context.Context, arg AddEpochEntityVersionParams) error
	AddEpochRelationVersion(ctx context.Context, arg AddEpochRelationVersionParams) error
	CountEpochs(ctx context.Context, zoneID string) (int64, error)
	CreateEpoch(ctx context.Context, arg CreateEpochParams) (int64, error)
	GetCurrentEpochID(ctx context.Context, zoneID string) (int64, error)
	GetEpoch(ctx context.Context, arg GetEpochParams) (Epoch, error)
	GetEpochByStructure(ctx context.Context, arg GetEpochByStructureParams) (Epoch, error)
	GetSchemaVersion(ctx context.Context) (int64, error)
	ListEpochClaimVersions(ctx context.Context, arg ListEpochClaimVersionsParams) ([]ListEpochClaimVersionsRow, error)
	ListEpochEntityVersions(ctx context.Context, arg ListEpochEntityVersionsParams) ([]ListEpochEntityVersionsRow, error)
	ListEpochRelationVersions(ctx context.Context, arg ListEpochRelationVersionsParams) ([]ListEpochRelationVersionsRow, error)
	SelectCurrentEpoch(ctx context.Context, arg SelectCurrentEpochParams) error
	ValidateSchema(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
