// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statements.sql

package db

import (
	"context"
)

const addEpochClaimVersion = `-- name: AddEpochClaimVersion :exec
INSERT INTO epoch_claim_versions (zone_id, epoch_id, claim_id, version)
VALUES (?1, ?2, ?3, ?4)
`

type AddEpochClaimVersionParams struct {
	ZoneID  string
	EpochID int64
	ClaimID string
	Version int64
}

func (q *Queries) AddEpochClaimVersion(ctx context.Context, arg AddEpochClaimVersionParams) error {
	_, err := q.db.ExecContext(ctx, addEpochClaimVersion,
		arg.ZoneID,
		arg.EpochID,
		arg.ClaimID,
		arg.Version,
	)
	return err
}

const addEpochEntityVersion = `-- name: AddEpochEntityVersion :exec
INSERT INTO epoch_entity_versions (zone_id, epoch_id, entity_id, version)
VALUES (?1, ?2, ?3, ?4)
`

type AddEpochEntityVersionParams struct {
	ZoneID   string
	EpochID  int64
	EntityID string
	Version  int64
}

func (q *Queries) AddEpochEntityVersion(ctx context.Context, arg AddEpochEntityVersionParams) error {
	_, err := q.db.ExecContext(ctx, addEpochEntityVersion,
		arg.ZoneID,
		arg.EpochID,
		arg.EntityID,
		arg.Version,
	)
	return err
}

const addEpochRelationVersion = `-- name: AddEpochRelationVersion :exec
INSERT INTO epoch_relation_versions (zone_id, epoch_id, relation_id, version)
VALUES (?1, ?2, ?3, ?4)
`

type AddEpochRelationVersionParams struct {
	ZoneID     string
	EpochID    int64
	RelationID string
	Version    int64
}

func (q *Queries) AddEpochRelationVersion(ctx context.Context, arg AddEpochRelationVersionParams) error {
	_, err := q.db.ExecContext(ctx, addEpochRelationVersion,
		arg.ZoneID,
		arg.EpochID,
		arg.RelationID,
		arg.Version,
	)
	return err
}

const countEpochs = `-- name: CountEpochs :one
SELECT count(*) FROM epochs WHERE zone_id = ?
`

func (q *Queries) CountEpochs(ctx context.Context, zoneID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEpochs, zoneID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEpoch = `-- name: CreateEpoch :one
INSERT INTO epochs (zone_id, id, knowledge_digest, corpora_id, structure_id, published_at)
VALUES (
    ?1,
    (SELECT COALESCE(MAX(id), 0) + 1 FROM epochs WHERE zone_id = ?1),
    ?2, ?3, ?4, ?5
)
RETURNING id
`

type CreateEpochParams struct {
	ZoneID          string
	KnowledgeDigest string
	CorporaID       string
	StructureID     string
	PublishedAt     string
}

func (q *Queries) CreateEpoch(ctx context.Context, arg CreateEpochParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createEpoch,
		arg.ZoneID,
		arg.KnowledgeDigest,
		arg.CorporaID,
		arg.StructureID,
		arg.PublishedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getCurrentEpochID = `-- name: GetCurrentEpochID :one
SELECT epoch_id FROM current_epoch WHERE zone_id = ?
`

func (q *Queries) GetCurrentEpochID(ctx context.Context, zoneID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCurrentEpochID, zoneID)
	var epoch_id int64
	err := row.Scan(&epoch_id)
	return epoch_id, err
}

const getEpoch = `-- name: GetEpoch :one
SELECT zone_id, id, knowledge_digest, corpora_id, structure_id, published_at FROM epochs WHERE zone_id = ? AND id = ?
`

type GetEpochParams struct {
	ZoneID string
	ID     int64
}

func (q *Queries) GetEpoch(ctx context.Context, arg GetEpochParams) (Epoch, error) {
	row := q.db.QueryRowContext(ctx, getEpoch, arg.ZoneID, arg.ID)
	var i Epoch
	err := row.Scan(
		&i.ZoneID,
		&i.ID,
		&i.KnowledgeDigest,
		&i.CorporaID,
		&i.StructureID,
		&i.PublishedAt,
	)
	return i, err
}

const getEpochByStructure = `-- name: GetEpochByStructure :one
SELECT zone_id, id, knowledge_digest, corpora_id, structure_id, published_at FROM epochs
WHERE zone_id = ?1 AND structure_id = ?2
`

type GetEpochByStructureParams struct {
	ZoneID      string
	StructureID string
}

func (q *Queries) GetEpochByStructure(ctx context.Context, arg GetEpochByStructureParams) (Epoch, error) {
	row := q.db.QueryRowContext(ctx, getEpochByStructure, arg.ZoneID, arg.StructureID)
	var i Epoch
	err := row.Scan(
		&i.ZoneID,
		&i.ID,
		&i.KnowledgeDigest,
		&i.CorporaID,
		&i.StructureID,
		&i.PublishedAt,
	)
	return i, err
}

const getSchemaVersion = `-- name: GetSchemaVersion :one
SELECT version FROM epoch_schema WHERE id = 1
`

func (q *Queries) GetSchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSchemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const listEpochClaimVersions = `-- name: ListEpochClaimVersions :many
SELECT claim_id, version FROM epoch_claim_versions
WHERE zone_id = ?1 AND epoch_id = ?2
ORDER BY claim_id
`

type ListEpochClaimVersionsParams struct {
	ZoneID  string
	EpochID int64
}

type ListEpochClaimVersionsRow struct {
	ClaimID string
	Version int64
}

func (q *Queries) ListEpochClaimVersions(ctx context.Context, arg ListEpochClaimVersionsParams) ([]ListEpochClaimVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEpochClaimVersions, arg.ZoneID, arg.EpochID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpochClaimVersionsRow{}
	for rows.Next() {
		var i ListEpochClaimVersionsRow
		if err := rows.Scan(&i.ClaimID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpochEntityVersions = `-- name: ListEpochEntityVersions :many
SELECT entity_id, version FROM epoch_entity_versions
WHERE zone_id = ?1 AND epoch_id = ?2
ORDER BY entity_id
`

type ListEpochEntityVersionsParams struct {
	ZoneID  string
	EpochID int64
}

type ListEpochEntityVersionsRow struct {
	EntityID string
	Version  int64
}

func (q *Queries) ListEpochEntityVersions(ctx context.Context, arg ListEpochEntityVersionsParams) ([]ListEpochEntityVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEpochEntityVersions, arg.ZoneID, arg.EpochID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpochEntityVersionsRow{}
	for rows.Next() {
		var i ListEpochEntityVersionsRow
		if err := rows.Scan(&i.EntityID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEpochRelationVersions = `-- name: ListEpochRelationVersions :many
SELECT relation_id, version FROM epoch_relation_versions
WHERE zone_id = ?1 AND epoch_id = ?2
ORDER BY relation_id
`

type ListEpochRelationVersionsParams struct {
	ZoneID  string
	EpochID int64
}

type ListEpochRelationVersionsRow struct {
	RelationID string
	Version    int64
}

func (q *Queries) ListEpochRelationVersions(ctx context.Context, arg ListEpochRelationVersionsParams) ([]ListEpochRelationVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEpochRelationVersions, arg.ZoneID, arg.EpochID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEpochRelationVersionsRow{}
	for rows.Next() {
		var i ListEpochRelationVersionsRow
		if err := rows.Scan(&i.RelationID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectCurrentEpoch = `-- name: SelectCurrentEpoch :exec
INSERT INTO current_epoch (zone_id, epoch_id) VALUES (?, ?)
ON CONFLICT(zone_id) DO UPDATE SET epoch_id = excluded.epoch_id
`

type SelectCurrentEpochParams struct {
	ZoneID  string
	EpochID int64
}

func (q *Queries) SelectCurrentEpoch(ctx context.Context, arg SelectCurrentEpochParams) error {
	_, err := q.db.ExecContext(ctx, selectCurrentEpoch, arg.ZoneID, arg.EpochID)
	return err
}

const validateSchema = `-- name: ValidateSchema :one
SELECT
	(SELECT count(zone_id) + count(id) + count(knowledge_digest) + count(corpora_id) + count(structure_id) + count(published_at) FROM epochs WHERE 0) +
	(SELECT count(*) FROM epoch_entity_versions WHERE 0) +
	(SELECT count(*) FROM epoch_relation_versions WHERE 0) +
	(SELECT count(*) FROM epoch_claim_versions WHERE 0) +
	(SELECT count(zone_id) + count(epoch_id) FROM current_epoch WHERE 0) +
	(SELECT count(*) FROM epochs INDEXED BY epochs_by_structure WHERE 0) +
    (SELECT count(id) + count(version) FROM epoch_schema WHERE 0) AS valid
`

func (q *Queries) ValidateSchema(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, validateSchema)
	var valid int64
	err := row.Scan(&valid)
	return valid, err
}
