// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitecache

type AnalysisCache struct {
	CacheKey   string
	Capability string
	Payload    []byte
	CreatedAt  string
}

type AnalysisCacheSchema struct {
	ID      int64
	Version int64
}
