// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlitecache

import (
	"context"
)

type Querier interface {
	GetAnalysisCacheEntry(ctx context.Context, cacheKey string) (GetAnalysisCacheEntryRow, error)
	GetAnalysisCacheSchemaVersion(ctx context.Context) (int64, error)
	PutAnalysisCacheEntry(ctx context.Context, arg PutAnalysisCacheEntryParams) error
	ValidateAnalysisCacheSchema(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
