// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sqlite_cache_statements.sql

package sqlitecache

import (
	"context"
)

const getAnalysisCacheEntry = `-- name: GetAnalysisCacheEntry :one
SELECT capability, payload, created_at
FROM analysis_cache
WHERE cache_key = ?
`

type GetAnalysisCacheEntryRow struct {
	Capability string
	Payload    []byte
	CreatedAt  string
}

func (q *Queries) GetAnalysisCacheEntry(ctx context.Context, cacheKey string) (GetAnalysisCacheEntryRow, error) {
	row := q.db.QueryRowContext(ctx, getAnalysisCacheEntry, cacheKey)
	var i GetAnalysisCacheEntryRow
	err := row.Scan(&i.Capability, &i.Payload, &i.CreatedAt)
	return i, err
}

const getAnalysisCacheSchemaVersion = `-- name: GetAnalysisCacheSchemaVersion :one
SELECT version
FROM analysis_cache_schema
WHERE id = 1
`

func (q *Queries) GetAnalysisCacheSchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAnalysisCacheSchemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const putAnalysisCacheEntry = `-- name: PutAnalysisCacheEntry :exec
INSERT INTO analysis_cache (
    cache_key,
    capability,
    payload,
    created_at
) VALUES (?, ?, ?, ?)
ON CONFLICT(cache_key) DO UPDATE SET
    capability = excluded.capability,
    payload = excluded.payload,
    created_at = excluded.created_at
`

type PutAnalysisCacheEntryParams struct {
	CacheKey   string
	Capability string
	Payload    []byte
	CreatedAt  string
}

func (q *Queries) PutAnalysisCacheEntry(ctx context.Context, arg PutAnalysisCacheEntryParams) error {
	_, err := q.db.ExecContext(ctx, putAnalysisCacheEntry,
		arg.CacheKey,
		arg.Capability,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const validateAnalysisCacheSchema = `-- name: ValidateAnalysisCacheSchema :one
SELECT
    (SELECT
        count(cache_key) +
        count(capability) +
        count(payload) +
        count(created_at)
     FROM analysis_cache
     WHERE 0) +
    (SELECT count(id) + count(version)
     FROM analysis_cache_schema
     WHERE 0) AS valid
`

func (q *Queries) ValidateAnalysisCacheSchema(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, validateAnalysisCacheSchema)
	var valid int64
	err := row.Scan(&valid)
	return valid, err
}
