// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type NamespaceConfig struct {
	ID     int64
	ZoneID string
	Name   string
}

type NamespaceVector struct {
	ID             int64
	ZoneID         string
	NamespaceRowID int64
	VectorRowID    int64
}

type SemanticSchema struct {
	ID      int64
	Version int64
}

type Vector struct {
	ID        int64
	VectorID  string
	Embedding string
}

type VectorDatabase struct {
	Singleton int64
	Model     string
	Dimension int64
}
