// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountNamespaceVectors(ctx context.Context, arg CountNamespaceVectorsParams) (int64, error)
	CreateVectorDatabase(ctx context.Context, model string) error
	DeleteNamespace(ctx context.Context, arg DeleteNamespaceParams) error
	DeleteNamespaceVectors(ctx context.Context, arg DeleteNamespaceVectorsParams) error
	GetNamespace(ctx context.Context, arg GetNamespaceParams) (NamespaceConfig, error)
	GetNamespaceVector(ctx context.Context, arg GetNamespaceVectorParams) (GetNamespaceVectorRow, error)
	// Static persistent SQL is generated by sqlc. Dimension-specific vec0
	// identifiers remain adapter-owned dynamic SQL.
	GetSchemaVersion(ctx context.Context) (int64, error)
	GetVector(ctx context.Context, vectorID string) (Vector, error)
	GetVectorDatabase(ctx context.Context) (GetVectorDatabaseRow, error)
	ListNamespaceVectorIDs(ctx context.Context, arg ListNamespaceVectorIDsParams) ([]string, error)
	ListVectors(ctx context.Context, vectorIds []string) ([]ListVectorsRow, error)
	RetainNamespace(ctx context.Context, arg RetainNamespaceParams) error
	RetainNamespaceVector(ctx context.Context, arg RetainNamespaceVectorParams) (int64, error)
	RetainVector(ctx context.Context, arg RetainVectorParams) error
	SetVectorDimension(ctx context.Context, dimension int64) error
	ValidateSchema(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
