// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statements.sql

package db

import (
	"context"
	"strings"
)

const countNamespaceVectors = `-- name: CountNamespaceVectors :one
SELECT count(*)
FROM namespace_vectors
WHERE zone_id = ?1 AND namespace_row_id = ?2
`

type CountNamespaceVectorsParams struct {
	ZoneID         string
	NamespaceRowID int64
}

func (q *Queries) CountNamespaceVectors(ctx context.Context, arg CountNamespaceVectorsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNamespaceVectors, arg.ZoneID, arg.NamespaceRowID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVectorDatabase = `-- name: CreateVectorDatabase :exec
INSERT INTO vector_database (singleton, model, dimension) VALUES (1, ?, 0)
`

func (q *Queries) CreateVectorDatabase(ctx context.Context, model string) error {
	_, err := q.db.ExecContext(ctx, createVectorDatabase, model)
	return err
}

const deleteNamespace = `-- name: DeleteNamespace :exec
DELETE FROM namespace_config
WHERE zone_id = ?1 AND id = ?2
`

type DeleteNamespaceParams struct {
	ZoneID string
	ID     int64
}

func (q *Queries) DeleteNamespace(ctx context.Context, arg DeleteNamespaceParams) error {
	_, err := q.db.ExecContext(ctx, deleteNamespace, arg.ZoneID, arg.ID)
	return err
}

const deleteNamespaceVectors = `-- name: DeleteNamespaceVectors :exec
DELETE FROM namespace_vectors
WHERE zone_id = ?1 AND namespace_row_id = ?2
`

type DeleteNamespaceVectorsParams struct {
	ZoneID         string
	NamespaceRowID int64
}

func (q *Queries) DeleteNamespaceVectors(ctx context.Context, arg DeleteNamespaceVectorsParams) error {
	_, err := q.db.ExecContext(ctx, deleteNamespaceVectors, arg.ZoneID, arg.NamespaceRowID)
	return err
}

const getNamespace = `-- name: GetNamespace :one
SELECT id, zone_id, name
FROM namespace_config
WHERE zone_id = ?1 AND name = ?2
`

type GetNamespaceParams struct {
	ZoneID string
	Name   string
}

func (q *Queries) GetNamespace(ctx context.Context, arg GetNamespaceParams) (NamespaceConfig, error) {
	row := q.db.QueryRowContext(ctx, getNamespace, arg.ZoneID, arg.Name)
	var i NamespaceConfig
	err := row.Scan(&i.ID, &i.ZoneID, &i.Name)
	return i, err
}

const getNamespaceVector = `-- name: GetNamespaceVector :one
SELECT member.zone_id, vector.vector_id, vector.embedding
FROM namespace_vectors AS member
JOIN vectors AS vector
  ON vector.id = member.vector_row_id
WHERE member.zone_id = ?1
  AND member.namespace_row_id = ?2
  AND vector.vector_id = ?3
`

type GetNamespaceVectorParams struct {
	ZoneID         string
	NamespaceRowID int64
	VectorID       string
}

type GetNamespaceVectorRow struct {
	ZoneID    string
	VectorID  string
	Embedding string
}

func (q *Queries) GetNamespaceVector(ctx context.Context, arg GetNamespaceVectorParams) (GetNamespaceVectorRow, error) {
	row := q.db.QueryRowContext(ctx, getNamespaceVector, arg.ZoneID, arg.NamespaceRowID, arg.VectorID)
	var i GetNamespaceVectorRow
	err := row.Scan(&i.ZoneID, &i.VectorID, &i.Embedding)
	return i, err
}

const getSchemaVersion = `-- name: GetSchemaVersion :one

SELECT version
FROM semantic_schema
WHERE id = 1
`

// Static persistent SQL is generated by sqlc. Dimension-specific vec0
// identifiers remain adapter-owned dynamic SQL.
func (q *Queries) GetSchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSchemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getVector = `-- name: GetVector :one
SELECT id, vector_id, embedding
FROM vectors
WHERE vector_id = ?1
`

func (q *Queries) GetVector(ctx context.Context, vectorID string) (Vector, error) {
	row := q.db.QueryRowContext(ctx, getVector, vectorID)
	var i Vector
	err := row.Scan(&i.ID, &i.VectorID, &i.Embedding)
	return i, err
}

const getVectorDatabase = `-- name: GetVectorDatabase :one
SELECT model, dimension FROM vector_database WHERE singleton = 1
`

type GetVectorDatabaseRow struct {
	Model     string
	Dimension int64
}

func (q *Queries) GetVectorDatabase(ctx context.Context) (GetVectorDatabaseRow, error) {
	row := q.db.QueryRowContext(ctx, getVectorDatabase)
	var i GetVectorDatabaseRow
	err := row.Scan(&i.Model, &i.Dimension)
	return i, err
}

const listNamespaceVectorIDs = `-- name: ListNamespaceVectorIDs :many
SELECT vector.vector_id
FROM namespace_vectors AS member
JOIN vectors AS vector
  ON vector.id = member.vector_row_id
WHERE member.zone_id = ?1
  AND member.namespace_row_id = ?2
  AND vector.vector_id > ?3
ORDER BY vector.vector_id
LIMIT ?4
`

type ListNamespaceVectorIDsParams struct {
	ZoneID         string
	NamespaceRowID int64
	AfterID        string
	PageLimit      int64
}

func (q *Queries) ListNamespaceVectorIDs(ctx context.Context, arg ListNamespaceVectorIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listNamespaceVectorIDs,
		arg.ZoneID,
		arg.NamespaceRowID,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var vector_id string
		if err := rows.Scan(&vector_id); err != nil {
			return nil, err
		}
		items = append(items, vector_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVectors = `-- name: ListVectors :many
SELECT vector_id, embedding
FROM vectors
WHERE vector_id IN (/*SLICE:vector_ids*/?)
ORDER BY vector_id
`

type ListVectorsRow struct {
	VectorID  string
	Embedding string
}

func (q *Queries) ListVectors(ctx context.Context, vectorIds []string) ([]ListVectorsRow, error) {
	query := listVectors
	var queryParams []interface{}
	if len(vectorIds) > 0 {
		for _, v := range vectorIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:vector_ids*/?", strings.Repeat(",?", len(vectorIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:vector_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVectorsRow{}
	for rows.Next() {
		var i ListVectorsRow
		if err := rows.Scan(&i.VectorID, &i.Embedding); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retainNamespace = `-- name: RetainNamespace :exec
INSERT INTO namespace_config (zone_id, name)
VALUES (?1, ?2)
ON CONFLICT (zone_id, name) DO NOTHING
`

type RetainNamespaceParams struct {
	ZoneID string
	Name   string
}

func (q *Queries) RetainNamespace(ctx context.Context, arg RetainNamespaceParams) error {
	_, err := q.db.ExecContext(ctx, retainNamespace, arg.ZoneID, arg.Name)
	return err
}

const retainNamespaceVector = `-- name: RetainNamespaceVector :one
INSERT INTO namespace_vectors (zone_id, namespace_row_id, vector_row_id)
VALUES (?1, ?2, ?3)
ON CONFLICT (zone_id, namespace_row_id, vector_row_id) DO NOTHING
RETURNING id
`

type RetainNamespaceVectorParams struct {
	ZoneID         string
	NamespaceRowID int64
	VectorRowID    int64
}

func (q *Queries) RetainNamespaceVector(ctx context.Context, arg RetainNamespaceVectorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, retainNamespaceVector, arg.ZoneID, arg.NamespaceRowID, arg.VectorRowID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const retainVector = `-- name: RetainVector :exec
INSERT INTO vectors (vector_id, embedding)
VALUES (?1, ?2)
ON CONFLICT (vector_id) DO NOTHING
`

type RetainVectorParams struct {
	VectorID  string
	Embedding string
}

func (q *Queries) RetainVector(ctx context.Context, arg RetainVectorParams) error {
	_, err := q.db.ExecContext(ctx, retainVector, arg.VectorID, arg.Embedding)
	return err
}

const setVectorDimension = `-- name: SetVectorDimension :exec
UPDATE vector_database SET dimension = ? WHERE singleton = 1 AND dimension = 0
`

func (q *Queries) SetVectorDimension(ctx context.Context, dimension int64) error {
	_, err := q.db.ExecContext(ctx, setVectorDimension, dimension)
	return err
}

const validateSchema = `-- name: ValidateSchema :one
SELECT
    (SELECT count(singleton) + count(model) + count(dimension)
     FROM vector_database
     WHERE 0) +
    (SELECT count(id) + count(vector_id) + count(embedding)
     FROM vectors
     WHERE 0) +
    (SELECT count(id) + count(zone_id) + count(name)
     FROM namespace_config
     WHERE 0) +
    (SELECT count(id) + count(zone_id) + count(namespace_row_id) + count(vector_row_id)
     FROM namespace_vectors
     WHERE 0) +
    (SELECT count(id) + count(version)
     FROM semantic_schema
     WHERE 0) AS valid
`

func (q *Queries) ValidateSchema(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, validateSchema)
	var valid int64
	err := row.Scan(&valid)
	return valid, err
}
