// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type CorpusChildBoundary struct {
	ZoneID          string
	ChildZoneID     string
	SourceCorporaID int64
}

type CorpusLocalText struct {
	ZoneID string
	TextID string
}

type CorpusSchema struct {
	ID      int64
	Version int64
}

type CorpusState struct {
	ZoneID            string
	CurrentCorporaID  int64
	BuildingCorporaID sql.NullInt64
	BuildingState     sql.NullString
}

type CorpusTextVectorProgress struct {
	ZoneID        string
	CorporaID     int64
	TextID        string
	SourceEventID string
}

type Document struct {
	ID        string
	Name      string
	MediaType string
	Size      int64
	Digest    string
	Location  string
}

type Message struct {
	ZoneID     string
	ID         string
	Role       string
	Position   int64
	TextUnitID string
}

type Text struct {
	ID                   string
	SourceDocumentID     string
	Title                string
	Body                 string
	Format               string
	ExtractionProfile    string
	NormalizationProfile string
}

type TextChunkingProgress struct {
	ZoneID         string
	TextID         string
	SourceEventID  string
	NextChunkIndex int64
	Completed      int64
}

type TextUnit struct {
	ZoneID string
	ID     string
	Text   string
}

type TextUnitSpan struct {
	ZoneID     string
	CorporaID  int64
	TextID     string
	TextUnitID string
	StartChar  int64
	EndChar    int64
	TokenCount int64
}

type TextWarning struct {
	TextID          string
	WarningPosition int64
	Warning         string
}

type ZoneDocument struct {
	ZoneID     string
	DocumentID string
}
