// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	ActivateCorpus(ctx context.Context, arg ActivateCorpusParams) (int64, error)
	AddTextUnitSpan(ctx context.Context, arg AddTextUnitSpanParams) error
	AddTextWarning(ctx context.Context, arg AddTextWarningParams) error
	AdvanceTextChunkingProgress(ctx context.Context, arg AdvanceTextChunkingProgressParams) (int64, error)
	BrowseDocuments(ctx context.Context, arg BrowseDocumentsParams) ([]BrowseDocumentsRow, error)
	ClearTextChunkingProgress(ctx context.Context, zoneID string) error
	CopyTextUnitSpans(ctx context.Context, arg CopyTextUnitSpansParams) error
	CountCorporaTexts(ctx context.Context, arg CountCorporaTextsParams) (int64, error)
	CountIncompleteTextChunking(ctx context.Context, zoneID string) (int64, error)
	CountTextUnitSpans(ctx context.Context, arg CountTextUnitSpansParams) (int64, error)
	CountTexts(ctx context.Context, zoneID string) (int64, error)
	CreateTextChunkingProgress(ctx context.Context, arg CreateTextChunkingProgressParams) error
	DeleteCorporaTextUnitSpans(ctx context.Context, arg DeleteCorporaTextUnitSpansParams) error
	EnsureCorpusState(ctx context.Context, zoneID string) error
	FindStoredText(ctx context.Context, arg FindStoredTextParams) (Text, error)
	FindText(ctx context.Context, arg FindTextParams) (Text, error)
	GetChildCorporaBoundary(ctx context.Context, arg GetChildCorporaBoundaryParams) (int64, error)
	GetCorpusState(ctx context.Context, zoneID string) (GetCorpusStateRow, error)
	GetCurrentCorporaID(ctx context.Context, zoneID string) (int64, error)
	GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error)
	GetDocumentByDigest(ctx context.Context, digest string) (Document, error)
	GetDocumentByLocation(ctx context.Context, arg GetDocumentByLocationParams) (Document, error)
	GetMessage(ctx context.Context, arg GetMessageParams) (GetMessageRow, error)
	GetSchemaVersion(ctx context.Context) (int64, error)
	GetStoredDocument(ctx context.Context, id string) (Document, error)
	GetStoredText(ctx context.Context, id string) (Text, error)
	GetText(ctx context.Context, arg GetTextParams) (Text, error)
	GetTextChunkingProgress(ctx context.Context, arg GetTextChunkingProgressParams) (GetTextChunkingProgressRow, error)
	GetTextChunkingProgressBySource(ctx context.Context, arg GetTextChunkingProgressBySourceParams) (GetTextChunkingProgressBySourceRow, error)
	GetTextUnit(ctx context.Context, arg GetTextUnitParams) (GetTextUnitRow, error)
	LastMessagePosition(ctx context.Context, zoneID string) (int64, error)
	ListChildCorporaBoundaries(ctx context.Context, zoneID string) ([]ListChildCorporaBoundariesRow, error)
	ListCorporaTextUnitSpans(ctx context.Context, arg ListCorporaTextUnitSpansParams) ([]ListCorporaTextUnitSpansRow, error)
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error)
	ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error)
	ListTextUnitLocations(ctx context.Context, arg ListTextUnitLocationsParams) ([]ListTextUnitLocationsRow, error)
	ListTextUnitSpans(ctx context.Context, arg ListTextUnitSpansParams) ([]ListTextUnitSpansRow, error)
	ListTextUnitsBeforeCorpora(ctx context.Context, arg ListTextUnitsBeforeCorporaParams) ([]ListTextUnitsBeforeCorporaRow, error)
	ListTextWarnings(ctx context.Context, textID string) ([]TextWarning, error)
	ListTexts(ctx context.Context, arg ListTextsParams) ([]Text, error)
	MarkCorpusPrepared(ctx context.Context, arg MarkCorpusPreparedParams) (int64, error)
	MarkLocalText(ctx context.Context, arg MarkLocalTextParams) error
	SaveChildCorporaBoundary(ctx context.Context, arg SaveChildCorporaBoundaryParams) error
	SaveDocument(ctx context.Context, arg SaveDocumentParams) (int64, error)
	SaveMessage(ctx context.Context, arg SaveMessageParams) (int64, error)
	SaveText(ctx context.Context, arg SaveTextParams) (int64, error)
	SaveTextUnit(ctx context.Context, arg SaveTextUnitParams) (int64, error)
	SaveZoneDocument(ctx context.Context, arg SaveZoneDocumentParams) (int64, error)
	StartCorpusBuild(ctx context.Context, zoneID string) (int64, error)
	ValidateSchema(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
