// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statements.sql

package db

import (
	"context"
	"database/sql"
	"strings"
)

const activateCorpus = `-- name: ActivateCorpus :execrows
UPDATE corpus_state
SET current_corpora_id = building_corpora_id,
    building_corpora_id = NULL,
    building_state = NULL
WHERE zone_id = ?1
  AND building_corpora_id = ?2
  AND building_state = 'prepared'
`

type ActivateCorpusParams struct {
	ZoneID            string
	BuildingCorporaID sql.NullInt64
}

func (q *Queries) ActivateCorpus(ctx context.Context, arg ActivateCorpusParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, activateCorpus, arg.ZoneID, arg.BuildingCorporaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const addTextUnitSpan = `-- name: AddTextUnitSpan :exec
INSERT INTO text_unit_spans (
    zone_id, corpora_id, text_id, text_unit_id, start_char, end_char, token_count
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AddTextUnitSpanParams struct {
	ZoneID     string
	CorporaID  int64
	TextID     string
	TextUnitID string
	StartChar  int64
	EndChar    int64
	TokenCount int64
}

func (q *Queries) AddTextUnitSpan(ctx context.Context, arg AddTextUnitSpanParams) error {
	_, err := q.db.ExecContext(ctx, addTextUnitSpan,
		arg.ZoneID,
		arg.CorporaID,
		arg.TextID,
		arg.TextUnitID,
		arg.StartChar,
		arg.EndChar,
		arg.TokenCount,
	)
	return err
}

const addTextWarning = `-- name: AddTextWarning :exec
INSERT INTO text_warnings (text_id, warning_position, warning)
VALUES (?, ?, ?)
`

type AddTextWarningParams struct {
	TextID          string
	WarningPosition int64
	Warning         string
}

func (q *Queries) AddTextWarning(ctx context.Context, arg AddTextWarningParams) error {
	_, err := q.db.ExecContext(ctx, addTextWarning, arg.TextID, arg.WarningPosition, arg.Warning)
	return err
}

const advanceTextChunkingProgress = `-- name: AdvanceTextChunkingProgress :execrows
UPDATE text_chunking_progress
SET next_chunk_index = ?1, completed = ?2
WHERE zone_id = ?3
  AND text_id = ?4
  AND next_chunk_index = ?5
  AND completed = 0
`

type AdvanceTextChunkingProgressParams struct {
	NextChunkIndex         int64
	Completed              int64
	ZoneID                 string
	TextID                 string
	ExpectedNextChunkIndex int64
}

func (q *Queries) AdvanceTextChunkingProgress(ctx context.Context, arg AdvanceTextChunkingProgressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceTextChunkingProgress,
		arg.NextChunkIndex,
		arg.Completed,
		arg.ZoneID,
		arg.TextID,
		arg.ExpectedNextChunkIndex,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const browseDocuments = `-- name: BrowseDocuments :many
SELECT document_value.id, document_value.name, document_value.media_type,
       document_value.size, document_value.digest,
       CASE WHEN zone_document.document_id IS NULL THEN 0 ELSE 1 END AS selected
FROM documents AS document_value
LEFT JOIN zone_documents AS zone_document
  ON zone_document.zone_id = ? AND zone_document.document_id = document_value.id
ORDER BY document_value.id LIMIT ? OFFSET ?
`

type BrowseDocumentsParams struct {
	ZoneID string
	Limit  int64
	Offset int64
}

type BrowseDocumentsRow struct {
	ID        string
	Name      string
	MediaType string
	Size      int64
	Digest    string
	Selected  int64
}

func (q *Queries) BrowseDocuments(ctx context.Context, arg BrowseDocumentsParams) ([]BrowseDocumentsRow, error) {
	rows, err := q.db.QueryContext(ctx, browseDocuments, arg.ZoneID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BrowseDocumentsRow{}
	for rows.Next() {
		var i BrowseDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MediaType,
			&i.Size,
			&i.Digest,
			&i.Selected,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearTextChunkingProgress = `-- name: ClearTextChunkingProgress :exec
DELETE FROM text_chunking_progress WHERE zone_id = ?
`

func (q *Queries) ClearTextChunkingProgress(ctx context.Context, zoneID string) error {
	_, err := q.db.ExecContext(ctx, clearTextChunkingProgress, zoneID)
	return err
}

const copyTextUnitSpans = `-- name: CopyTextUnitSpans :exec
INSERT INTO text_unit_spans (
    zone_id, corpora_id, text_id, text_unit_id, start_char, end_char, token_count
)
SELECT ?1, ?2, source.text_id,
       source.text_unit_id, source.start_char, source.end_char, source.token_count
FROM text_unit_spans AS source
WHERE source.zone_id = ?1
  AND source.corpora_id = ?3
  AND EXISTS (
      SELECT 1 FROM corpus_local_texts AS local_text
      WHERE local_text.zone_id = source.zone_id
        AND local_text.text_id = source.text_id
  )
`

type CopyTextUnitSpansParams struct {
	ZoneID          string
	TargetCorporaID int64
	SourceCorporaID int64
}

func (q *Queries) CopyTextUnitSpans(ctx context.Context, arg CopyTextUnitSpansParams) error {
	_, err := q.db.ExecContext(ctx, copyTextUnitSpans, arg.ZoneID, arg.TargetCorporaID, arg.SourceCorporaID)
	return err
}

const countCorporaTexts = `-- name: CountCorporaTexts :one
SELECT count(DISTINCT text_id)
FROM text_unit_spans WHERE zone_id = ? AND corpora_id = ?
`

type CountCorporaTextsParams struct {
	ZoneID    string
	CorporaID int64
}

func (q *Queries) CountCorporaTexts(ctx context.Context, arg CountCorporaTextsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCorporaTexts, arg.ZoneID, arg.CorporaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countIncompleteTextChunking = `-- name: CountIncompleteTextChunking :one
SELECT count(*) FROM text_chunking_progress WHERE zone_id = ? AND completed = 0
`

func (q *Queries) CountIncompleteTextChunking(ctx context.Context, zoneID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countIncompleteTextChunking, zoneID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTextUnitSpans = `-- name: CountTextUnitSpans :one
SELECT count(*) FROM text_unit_spans WHERE zone_id = ? AND corpora_id = ?
`

type CountTextUnitSpansParams struct {
	ZoneID    string
	CorporaID int64
}

func (q *Queries) CountTextUnitSpans(ctx context.Context, arg CountTextUnitSpansParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTextUnitSpans, arg.ZoneID, arg.CorporaID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTexts = `-- name: CountTexts :one
SELECT count(*)
FROM corpus_local_texts
WHERE zone_id = ?
`

func (q *Queries) CountTexts(ctx context.Context, zoneID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTexts, zoneID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTextChunkingProgress = `-- name: CreateTextChunkingProgress :exec
INSERT INTO text_chunking_progress (
    zone_id, text_id, source_event_id, next_chunk_index, completed
) VALUES (?, ?, ?, 0, 0)
`

type CreateTextChunkingProgressParams struct {
	ZoneID        string
	TextID        string
	SourceEventID string
}

func (q *Queries) CreateTextChunkingProgress(ctx context.Context, arg CreateTextChunkingProgressParams) error {
	_, err := q.db.ExecContext(ctx, createTextChunkingProgress, arg.ZoneID, arg.TextID, arg.SourceEventID)
	return err
}

const deleteCorporaTextUnitSpans = `-- name: DeleteCorporaTextUnitSpans :exec
DELETE FROM text_unit_spans
WHERE zone_id = ? AND corpora_id = ? AND text_id = ?
`

type DeleteCorporaTextUnitSpansParams struct {
	ZoneID    string
	CorporaID int64
	TextID    string
}

func (q *Queries) DeleteCorporaTextUnitSpans(ctx context.Context, arg DeleteCorporaTextUnitSpansParams) error {
	_, err := q.db.ExecContext(ctx, deleteCorporaTextUnitSpans, arg.ZoneID, arg.CorporaID, arg.TextID)
	return err
}

const ensureCorpusState = `-- name: EnsureCorpusState :exec
INSERT OR IGNORE INTO corpus_state (
    zone_id, current_corpora_id, building_corpora_id, building_state
) VALUES (?, 0, NULL, NULL)
`

func (q *Queries) EnsureCorpusState(ctx context.Context, zoneID string) error {
	_, err := q.db.ExecContext(ctx, ensureCorpusState, zoneID)
	return err
}

const findStoredText = `-- name: FindStoredText :one
SELECT id, source_document_id, title, body, format,
       extraction_profile, normalization_profile
FROM texts
WHERE source_document_id = ?
  AND extraction_profile = ?
  AND normalization_profile = ?
`

type FindStoredTextParams struct {
	SourceDocumentID     string
	ExtractionProfile    string
	NormalizationProfile string
}

func (q *Queries) FindStoredText(ctx context.Context, arg FindStoredTextParams) (Text, error) {
	row := q.db.QueryRowContext(ctx, findStoredText, arg.SourceDocumentID, arg.ExtractionProfile, arg.NormalizationProfile)
	var i Text
	err := row.Scan(
		&i.ID,
		&i.SourceDocumentID,
		&i.Title,
		&i.Body,
		&i.Format,
		&i.ExtractionProfile,
		&i.NormalizationProfile,
	)
	return i, err
}

const findText = `-- name: FindText :one
SELECT id, source_document_id, title, body, format,
       extraction_profile, normalization_profile
FROM texts AS text_value
JOIN corpus_local_texts AS local_text ON local_text.text_id = text_value.id
WHERE local_text.zone_id = ?
  AND text_value.source_document_id = ?
  AND extraction_profile = ?
  AND normalization_profile = ?
`

type FindTextParams struct {
	ZoneID               string
	SourceDocumentID     string
	ExtractionProfile    string
	NormalizationProfile string
}

func (q *Queries) FindText(ctx context.Context, arg FindTextParams) (Text, error) {
	row := q.db.QueryRowContext(ctx, findText,
		arg.ZoneID,
		arg.SourceDocumentID,
		arg.ExtractionProfile,
		arg.NormalizationProfile,
	)
	var i Text
	err := row.Scan(
		&i.ID,
		&i.SourceDocumentID,
		&i.Title,
		&i.Body,
		&i.Format,
		&i.ExtractionProfile,
		&i.NormalizationProfile,
	)
	return i, err
}

const getChildCorporaBoundary = `-- name: GetChildCorporaBoundary :one
SELECT source_corpora_id
FROM corpus_child_boundaries
WHERE zone_id = ?1 AND child_zone_id = ?2
`

type GetChildCorporaBoundaryParams struct {
	ZoneID      string
	ChildZoneID string
}

func (q *Queries) GetChildCorporaBoundary(ctx context.Context, arg GetChildCorporaBoundaryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getChildCorporaBoundary, arg.ZoneID, arg.ChildZoneID)
	var source_corpora_id int64
	err := row.Scan(&source_corpora_id)
	return source_corpora_id, err
}

const getCorpusState = `-- name: GetCorpusState :one
SELECT current_corpora_id, building_corpora_id, building_state
FROM corpus_state WHERE zone_id = ?
`

type GetCorpusStateRow struct {
	CurrentCorporaID  int64
	BuildingCorporaID sql.NullInt64
	BuildingState     sql.NullString
}

func (q *Queries) GetCorpusState(ctx context.Context, zoneID string) (GetCorpusStateRow, error) {
	row := q.db.QueryRowContext(ctx, getCorpusState, zoneID)
	var i GetCorpusStateRow
	err := row.Scan(&i.CurrentCorporaID, &i.BuildingCorporaID, &i.BuildingState)
	return i, err
}

const getCurrentCorporaID = `-- name: GetCurrentCorporaID :one
SELECT current_corpora_id FROM corpus_state WHERE zone_id = ?
`

func (q *Queries) GetCurrentCorporaID(ctx context.Context, zoneID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCurrentCorporaID, zoneID)
	var current_corpora_id int64
	err := row.Scan(&current_corpora_id)
	return current_corpora_id, err
}

const getDocument = `-- name: GetDocument :one
SELECT document_value.id, document_value.name, document_value.media_type,
       document_value.size, document_value.digest, document_value.location
FROM documents AS document_value
JOIN zone_documents AS zone_document
  ON zone_document.document_id = document_value.id
WHERE zone_document.zone_id = ? AND document_value.id = ?
`

type GetDocumentParams struct {
	ZoneID string
	ID     string
}

func (q *Queries) GetDocument(ctx context.Context, arg GetDocumentParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocument, arg.ZoneID, arg.ID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MediaType,
		&i.Size,
		&i.Digest,
		&i.Location,
	)
	return i, err
}

const getDocumentByDigest = `-- name: GetDocumentByDigest :one
SELECT id, name, media_type, size, digest, location
FROM documents WHERE digest = ?
`

func (q *Queries) GetDocumentByDigest(ctx context.Context, digest string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByDigest, digest)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MediaType,
		&i.Size,
		&i.Digest,
		&i.Location,
	)
	return i, err
}

const getDocumentByLocation = `-- name: GetDocumentByLocation :one
SELECT document_value.id, document_value.name, document_value.media_type,
       document_value.size, document_value.digest, document_value.location
FROM documents AS document_value
JOIN zone_documents AS zone_document
  ON zone_document.document_id = document_value.id
WHERE zone_document.zone_id = ? AND document_value.location = ?
`

type GetDocumentByLocationParams struct {
	ZoneID   string
	Location string
}

func (q *Queries) GetDocumentByLocation(ctx context.Context, arg GetDocumentByLocationParams) (Document, error) {
	row := q.db.QueryRowContext(ctx, getDocumentByLocation, arg.ZoneID, arg.Location)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MediaType,
		&i.Size,
		&i.Digest,
		&i.Location,
	)
	return i, err
}

const getMessage = `-- name: GetMessage :one
SELECT message.id, message.role, message.position,
       message.text_unit_id, unit.text AS text_unit_text
FROM messages AS message
JOIN text_units AS unit
  ON unit.zone_id = message.zone_id AND unit.id = message.text_unit_id
WHERE message.zone_id = ? AND message.id = ?
`

type GetMessageParams struct {
	ZoneID string
	ID     string
}

type GetMessageRow struct {
	ID           string
	Role         string
	Position     int64
	TextUnitID   string
	TextUnitText string
}

func (q *Queries) GetMessage(ctx context.Context, arg GetMessageParams) (GetMessageRow, error) {
	row := q.db.QueryRowContext(ctx, getMessage, arg.ZoneID, arg.ID)
	var i GetMessageRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Position,
		&i.TextUnitID,
		&i.TextUnitText,
	)
	return i, err
}

const getSchemaVersion = `-- name: GetSchemaVersion :one
SELECT version FROM corpus_schema WHERE id = 1
`

func (q *Queries) GetSchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSchemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getStoredDocument = `-- name: GetStoredDocument :one
SELECT id, name, media_type, size, digest, location
FROM documents WHERE id = ?
`

func (q *Queries) GetStoredDocument(ctx context.Context, id string) (Document, error) {
	row := q.db.QueryRowContext(ctx, getStoredDocument, id)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.MediaType,
		&i.Size,
		&i.Digest,
		&i.Location,
	)
	return i, err
}

const getStoredText = `-- name: GetStoredText :one
SELECT id, source_document_id, title, body, format,
       extraction_profile, normalization_profile
FROM texts WHERE id = ?
`

func (q *Queries) GetStoredText(ctx context.Context, id string) (Text, error) {
	row := q.db.QueryRowContext(ctx, getStoredText, id)
	var i Text
	err := row.Scan(
		&i.ID,
		&i.SourceDocumentID,
		&i.Title,
		&i.Body,
		&i.Format,
		&i.ExtractionProfile,
		&i.NormalizationProfile,
	)
	return i, err
}

const getText = `-- name: GetText :one
SELECT id, source_document_id, title, body, format,
       extraction_profile, normalization_profile
FROM texts AS text_value
JOIN corpus_local_texts AS local_text ON local_text.text_id = text_value.id
WHERE local_text.zone_id = ? AND text_value.id = ?
`

type GetTextParams struct {
	ZoneID string
	ID     string
}

func (q *Queries) GetText(ctx context.Context, arg GetTextParams) (Text, error) {
	row := q.db.QueryRowContext(ctx, getText, arg.ZoneID, arg.ID)
	var i Text
	err := row.Scan(
		&i.ID,
		&i.SourceDocumentID,
		&i.Title,
		&i.Body,
		&i.Format,
		&i.ExtractionProfile,
		&i.NormalizationProfile,
	)
	return i, err
}

const getTextChunkingProgress = `-- name: GetTextChunkingProgress :one
SELECT text_id, source_event_id, next_chunk_index, completed
FROM text_chunking_progress
WHERE zone_id = ? AND text_id = ?
`

type GetTextChunkingProgressParams struct {
	ZoneID string
	TextID string
}

type GetTextChunkingProgressRow struct {
	TextID         string
	SourceEventID  string
	NextChunkIndex int64
	Completed      int64
}

func (q *Queries) GetTextChunkingProgress(ctx context.Context, arg GetTextChunkingProgressParams) (GetTextChunkingProgressRow, error) {
	row := q.db.QueryRowContext(ctx, getTextChunkingProgress, arg.ZoneID, arg.TextID)
	var i GetTextChunkingProgressRow
	err := row.Scan(
		&i.TextID,
		&i.SourceEventID,
		&i.NextChunkIndex,
		&i.Completed,
	)
	return i, err
}

const getTextChunkingProgressBySource = `-- name: GetTextChunkingProgressBySource :one
SELECT text_id, source_event_id, next_chunk_index, completed
FROM text_chunking_progress
WHERE zone_id = ? AND source_event_id = ?
`

type GetTextChunkingProgressBySourceParams struct {
	ZoneID        string
	SourceEventID string
}

type GetTextChunkingProgressBySourceRow struct {
	TextID         string
	SourceEventID  string
	NextChunkIndex int64
	Completed      int64
}

func (q *Queries) GetTextChunkingProgressBySource(ctx context.Context, arg GetTextChunkingProgressBySourceParams) (GetTextChunkingProgressBySourceRow, error) {
	row := q.db.QueryRowContext(ctx, getTextChunkingProgressBySource, arg.ZoneID, arg.SourceEventID)
	var i GetTextChunkingProgressBySourceRow
	err := row.Scan(
		&i.TextID,
		&i.SourceEventID,
		&i.NextChunkIndex,
		&i.Completed,
	)
	return i, err
}

const getTextUnit = `-- name: GetTextUnit :one
SELECT id, text FROM text_units WHERE zone_id = ? AND id = ?
`

type GetTextUnitParams struct {
	ZoneID string
	ID     string
}

type GetTextUnitRow struct {
	ID   string
	Text string
}

func (q *Queries) GetTextUnit(ctx context.Context, arg GetTextUnitParams) (GetTextUnitRow, error) {
	row := q.db.QueryRowContext(ctx, getTextUnit, arg.ZoneID, arg.ID)
	var i GetTextUnitRow
	err := row.Scan(&i.ID, &i.Text)
	return i, err
}

const lastMessagePosition = `-- name: LastMessagePosition :one
SELECT CAST(coalesce(max(position), -1) AS INTEGER) AS position
FROM messages WHERE zone_id = ?
`

func (q *Queries) LastMessagePosition(ctx context.Context, zoneID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, lastMessagePosition, zoneID)
	var position int64
	err := row.Scan(&position)
	return position, err
}

const listChildCorporaBoundaries = `-- name: ListChildCorporaBoundaries :many
SELECT child_zone_id, source_corpora_id
FROM corpus_child_boundaries
WHERE zone_id = ?1
ORDER BY child_zone_id
`

type ListChildCorporaBoundariesRow struct {
	ChildZoneID     string
	SourceCorporaID int64
}

func (q *Queries) ListChildCorporaBoundaries(ctx context.Context, zoneID string) ([]ListChildCorporaBoundariesRow, error) {
	rows, err := q.db.QueryContext(ctx, listChildCorporaBoundaries, zoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChildCorporaBoundariesRow{}
	for rows.Next() {
		var i ListChildCorporaBoundariesRow
		if err := rows.Scan(&i.ChildZoneID, &i.SourceCorporaID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCorporaTextUnitSpans = `-- name: ListCorporaTextUnitSpans :many
SELECT span.text_unit_id, span.start_char, span.end_char, span.token_count,
       unit.text AS text_unit_text
FROM text_unit_spans AS span
JOIN text_units AS unit
  ON unit.zone_id = span.zone_id AND unit.id = span.text_unit_id
WHERE span.zone_id = ?1
  AND span.corpora_id = ?2
  AND span.text_id = ?3
ORDER BY span.start_char, span.end_char
`

type ListCorporaTextUnitSpansParams struct {
	ZoneID    string
	CorporaID int64
	TextID    string
}

type ListCorporaTextUnitSpansRow struct {
	TextUnitID   string
	StartChar    int64
	EndChar      int64
	TokenCount   int64
	TextUnitText string
}

func (q *Queries) ListCorporaTextUnitSpans(ctx context.Context, arg ListCorporaTextUnitSpansParams) ([]ListCorporaTextUnitSpansRow, error) {
	rows, err := q.db.QueryContext(ctx, listCorporaTextUnitSpans, arg.ZoneID, arg.CorporaID, arg.TextID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCorporaTextUnitSpansRow{}
	for rows.Next() {
		var i ListCorporaTextUnitSpansRow
		if err := rows.Scan(
			&i.TextUnitID,
			&i.StartChar,
			&i.EndChar,
			&i.TokenCount,
			&i.TextUnitText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT document_value.id, document_value.name, document_value.media_type,
       document_value.size, document_value.digest, document_value.location
FROM documents AS document_value
JOIN zone_documents AS zone_document
  ON zone_document.document_id = document_value.id
WHERE zone_document.zone_id = ?
ORDER BY document_value.id LIMIT ? OFFSET ?
`

type ListDocumentsParams struct {
	ZoneID string
	Limit  int64
	Offset int64
}

func (q *Queries) ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]Document, error) {
	rows, err := q.db.QueryContext(ctx, listDocuments, arg.ZoneID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Document{}
	for rows.Next() {
		var i Document
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MediaType,
			&i.Size,
			&i.Digest,
			&i.Location,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessages = `-- name: ListMessages :many
SELECT message.id, message.role, message.position,
       message.text_unit_id, unit.text AS text_unit_text
FROM messages AS message
JOIN text_units AS unit
  ON unit.zone_id = message.zone_id AND unit.id = message.text_unit_id
WHERE message.zone_id = ?1
  AND message.id IN (/*SLICE:message_ids*/?)
ORDER BY message.position
`

type ListMessagesParams struct {
	ZoneID     string
	MessageIds []string
}

type ListMessagesRow struct {
	ID           string
	Role         string
	Position     int64
	TextUnitID   string
	TextUnitText string
}

func (q *Queries) ListMessages(ctx context.Context, arg ListMessagesParams) ([]ListMessagesRow, error) {
	query := listMessages
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ZoneID)
	if len(arg.MessageIds) > 0 {
		for _, v := range arg.MessageIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:message_ids*/?", strings.Repeat(",?", len(arg.MessageIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:message_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesRow{}
	for rows.Next() {
		var i ListMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Position,
			&i.TextUnitID,
			&i.TextUnitText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTextUnitLocations = `-- name: ListTextUnitLocations :many
SELECT entry.corpora_id,
       entry.text_id,
       entry.start_char,
       entry.end_char,
       entry.token_count,
       text_value.id AS text_id,
       text_value.title,
       text_value.body AS text_body,
       text_value.source_document_id,
       document_value.location AS document_location,
       unit.text AS text_unit_text,
       unit.id AS text_unit_id
FROM text_unit_spans AS entry
JOIN texts AS text_value
  ON text_value.id = entry.text_id
JOIN documents AS document_value
  ON document_value.id = text_value.source_document_id
JOIN zone_documents AS zone_document
  ON zone_document.zone_id = entry.zone_id
 AND zone_document.document_id = document_value.id
JOIN text_units AS unit
  ON unit.zone_id = entry.zone_id AND unit.id = entry.text_unit_id
WHERE entry.zone_id = ?1
  AND entry.corpora_id = ?2
  AND entry.text_unit_id IN (/*SLICE:text_unit_ids*/?)
ORDER BY entry.text_id, entry.start_char, entry.end_char
`

type ListTextUnitLocationsParams struct {
	ZoneID      string
	CorporaID   int64
	TextUnitIds []string
}

type ListTextUnitLocationsRow struct {
	CorporaID        int64
	TextID           string
	StartChar        int64
	EndChar          int64
	TokenCount       int64
	TextID_2         string
	Title            string
	TextBody         string
	SourceDocumentID string
	DocumentLocation string
	TextUnitText     string
	TextUnitID       string
}

func (q *Queries) ListTextUnitLocations(ctx context.Context, arg ListTextUnitLocationsParams) ([]ListTextUnitLocationsRow, error) {
	query := listTextUnitLocations
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ZoneID)
	queryParams = append(queryParams, arg.CorporaID)
	if len(arg.TextUnitIds) > 0 {
		for _, v := range arg.TextUnitIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:text_unit_ids*/?", strings.Repeat(",?", len(arg.TextUnitIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:text_unit_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTextUnitLocationsRow{}
	for rows.Next() {
		var i ListTextUnitLocationsRow
		if err := rows.Scan(
			&i.CorporaID,
			&i.TextID,
			&i.StartChar,
			&i.EndChar,
			&i.TokenCount,
			&i.TextID_2,
			&i.Title,
			&i.TextBody,
			&i.SourceDocumentID,
			&i.DocumentLocation,
			&i.TextUnitText,
			&i.TextUnitID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTextUnitSpans = `-- name: ListTextUnitSpans :many
SELECT span.corpora_id, span.text_id, span.text_unit_id,
       span.start_char, span.end_char, span.token_count,
       unit.text AS text_unit_text
FROM text_unit_spans AS span
JOIN text_units AS unit
  ON unit.zone_id = span.zone_id AND unit.id = span.text_unit_id
WHERE span.zone_id = ? AND span.corpora_id = ?
ORDER BY span.text_id, span.start_char, span.end_char
`

type ListTextUnitSpansParams struct {
	ZoneID    string
	CorporaID int64
}

type ListTextUnitSpansRow struct {
	CorporaID    int64
	TextID       string
	TextUnitID   string
	StartChar    int64
	EndChar      int64
	TokenCount   int64
	TextUnitText string
}

func (q *Queries) ListTextUnitSpans(ctx context.Context, arg ListTextUnitSpansParams) ([]ListTextUnitSpansRow, error) {
	rows, err := q.db.QueryContext(ctx, listTextUnitSpans, arg.ZoneID, arg.CorporaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTextUnitSpansRow{}
	for rows.Next() {
		var i ListTextUnitSpansRow
		if err := rows.Scan(
			&i.CorporaID,
			&i.TextID,
			&i.TextUnitID,
			&i.StartChar,
			&i.EndChar,
			&i.TokenCount,
			&i.TextUnitText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTextUnitsBeforeCorpora = `-- name: ListTextUnitsBeforeCorpora :many
SELECT DISTINCT unit.id, unit.text
FROM text_units AS unit
JOIN text_unit_spans AS span
  ON span.zone_id = unit.zone_id AND span.text_unit_id = unit.id
WHERE unit.zone_id = ?1
  AND span.corpora_id < ?2
  AND unit.id IN (/*SLICE:text_unit_ids*/?)
ORDER BY unit.id
`

type ListTextUnitsBeforeCorporaParams struct {
	ZoneID             string
	ExclusiveCorporaID int64
	TextUnitIds        []string
}

type ListTextUnitsBeforeCorporaRow struct {
	ID   string
	Text string
}

func (q *Queries) ListTextUnitsBeforeCorpora(ctx context.Context, arg ListTextUnitsBeforeCorporaParams) ([]ListTextUnitsBeforeCorporaRow, error) {
	query := listTextUnitsBeforeCorpora
	var queryParams []interface{}
	queryParams = append(queryParams, arg.ZoneID)
	queryParams = append(queryParams, arg.ExclusiveCorporaID)
	if len(arg.TextUnitIds) > 0 {
		for _, v := range arg.TextUnitIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:text_unit_ids*/?", strings.Repeat(",?", len(arg.TextUnitIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:text_unit_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTextUnitsBeforeCorporaRow{}
	for rows.Next() {
		var i ListTextUnitsBeforeCorporaRow
		if err := rows.Scan(&i.ID, &i.Text); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTextWarnings = `-- name: ListTextWarnings :many
SELECT text_id, warning_position, warning
FROM text_warnings WHERE text_id = ? ORDER BY warning_position
`

func (q *Queries) ListTextWarnings(ctx context.Context, textID string) ([]TextWarning, error) {
	rows, err := q.db.QueryContext(ctx, listTextWarnings, textID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TextWarning{}
	for rows.Next() {
		var i TextWarning
		if err := rows.Scan(&i.TextID, &i.WarningPosition, &i.Warning); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTexts = `-- name: ListTexts :many
SELECT id, source_document_id, title, body, format,
       extraction_profile, normalization_profile
FROM texts AS text_value
JOIN corpus_local_texts AS local_text ON local_text.text_id = text_value.id
WHERE local_text.zone_id = ? ORDER BY text_value.id LIMIT ? OFFSET ?
`

type ListTextsParams struct {
	ZoneID string
	Limit  int64
	Offset int64
}

func (q *Queries) ListTexts(ctx context.Context, arg ListTextsParams) ([]Text, error) {
	rows, err := q.db.QueryContext(ctx, listTexts, arg.ZoneID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Text{}
	for rows.Next() {
		var i Text
		if err := rows.Scan(
			&i.ID,
			&i.SourceDocumentID,
			&i.Title,
			&i.Body,
			&i.Format,
			&i.ExtractionProfile,
			&i.NormalizationProfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCorpusPrepared = `-- name: MarkCorpusPrepared :execrows
UPDATE corpus_state
SET building_state = 'prepared'
WHERE zone_id = ?1
  AND building_corpora_id = ?2
  AND building_state = 'building'
`

type MarkCorpusPreparedParams struct {
	ZoneID            string
	BuildingCorporaID sql.NullInt64
}

func (q *Queries) MarkCorpusPrepared(ctx context.Context, arg MarkCorpusPreparedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markCorpusPrepared, arg.ZoneID, arg.BuildingCorporaID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const markLocalText = `-- name: MarkLocalText :exec
INSERT OR IGNORE INTO corpus_local_texts (zone_id, text_id) VALUES (?, ?)
`

type MarkLocalTextParams struct {
	ZoneID string
	TextID string
}

func (q *Queries) MarkLocalText(ctx context.Context, arg MarkLocalTextParams) error {
	_, err := q.db.ExecContext(ctx, markLocalText, arg.ZoneID, arg.TextID)
	return err
}

const saveChildCorporaBoundary = `-- name: SaveChildCorporaBoundary :exec
INSERT INTO corpus_child_boundaries (zone_id, child_zone_id, source_corpora_id)
VALUES (?1, ?2, ?3)
ON CONFLICT (zone_id, child_zone_id) DO UPDATE
SET source_corpora_id = excluded.source_corpora_id
`

type SaveChildCorporaBoundaryParams struct {
	ZoneID          string
	ChildZoneID     string
	SourceCorporaID int64
}

func (q *Queries) SaveChildCorporaBoundary(ctx context.Context, arg SaveChildCorporaBoundaryParams) error {
	_, err := q.db.ExecContext(ctx, saveChildCorporaBoundary, arg.ZoneID, arg.ChildZoneID, arg.SourceCorporaID)
	return err
}

const saveDocument = `-- name: SaveDocument :execrows
INSERT OR IGNORE INTO documents (id, name, media_type, size, digest, location)
VALUES (?, ?, ?, ?, ?, ?)
`

type SaveDocumentParams struct {
	ID        string
	Name      string
	MediaType string
	Size      int64
	Digest    string
	Location  string
}

func (q *Queries) SaveDocument(ctx context.Context, arg SaveDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveDocument,
		arg.ID,
		arg.Name,
		arg.MediaType,
		arg.Size,
		arg.Digest,
		arg.Location,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveMessage = `-- name: SaveMessage :execrows
INSERT INTO messages (zone_id, id, role, position, text_unit_id)
VALUES (?, ?, ?, ?, ?)
`

type SaveMessageParams struct {
	ZoneID     string
	ID         string
	Role       string
	Position   int64
	TextUnitID string
}

func (q *Queries) SaveMessage(ctx context.Context, arg SaveMessageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveMessage,
		arg.ZoneID,
		arg.ID,
		arg.Role,
		arg.Position,
		arg.TextUnitID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveText = `-- name: SaveText :execrows
INSERT OR IGNORE INTO texts (
    id, source_document_id, title, body, format,
    extraction_profile, normalization_profile
) VALUES (?, ?, ?, ?, ?, ?, ?)
`

type SaveTextParams struct {
	ID                   string
	SourceDocumentID     string
	Title                string
	Body                 string
	Format               string
	ExtractionProfile    string
	NormalizationProfile string
}

func (q *Queries) SaveText(ctx context.Context, arg SaveTextParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveText,
		arg.ID,
		arg.SourceDocumentID,
		arg.Title,
		arg.Body,
		arg.Format,
		arg.ExtractionProfile,
		arg.NormalizationProfile,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveTextUnit = `-- name: SaveTextUnit :execrows
INSERT OR IGNORE INTO text_units (zone_id, id, text) VALUES (?, ?, ?)
`

type SaveTextUnitParams struct {
	ZoneID string
	ID     string
	Text   string
}

func (q *Queries) SaveTextUnit(ctx context.Context, arg SaveTextUnitParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveTextUnit, arg.ZoneID, arg.ID, arg.Text)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveZoneDocument = `-- name: SaveZoneDocument :execrows
INSERT OR IGNORE INTO zone_documents (zone_id, document_id)
VALUES (?, ?)
`

type SaveZoneDocumentParams struct {
	ZoneID     string
	DocumentID string
}

func (q *Queries) SaveZoneDocument(ctx context.Context, arg SaveZoneDocumentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, saveZoneDocument, arg.ZoneID, arg.DocumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const startCorpusBuild = `-- name: StartCorpusBuild :execrows
UPDATE corpus_state
SET building_corpora_id = current_corpora_id + 1, building_state = 'building'
WHERE zone_id = ? AND building_corpora_id IS NULL AND building_state IS NULL
`

func (q *Queries) StartCorpusBuild(ctx context.Context, zoneID string) (int64, error) {
	result, err := q.db.ExecContext(ctx, startCorpusBuild, zoneID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const validateSchema = `-- name: ValidateSchema :one
SELECT
    (SELECT count(*) FROM corpus_child_boundaries WHERE 0) +
    (SELECT count(*) FROM corpus_text_vector_progress WHERE 0) +
    (SELECT count(*) FROM documents WHERE 0) +
    (SELECT count(*) FROM zone_documents WHERE 0) +
    (SELECT count(*) FROM texts WHERE 0) +
    (SELECT count(*) FROM corpus_local_texts WHERE 0) +
    (SELECT count(*) FROM text_warnings WHERE 0) +
    (SELECT count(*) FROM text_units WHERE 0) +
    (SELECT count(*) FROM messages WHERE 0) +
    (SELECT count(*) FROM text_unit_spans WHERE 0) +
    (SELECT count(*) FROM text_chunking_progress WHERE 0) +
    (SELECT count(*) FROM corpus_state WHERE 0) +
    (SELECT count(*) FROM texts INDEXED BY texts_by_document_and_profiles WHERE 0) +
    (SELECT count(*) FROM text_unit_spans INDEXED BY text_unit_spans_by_set_and_text_unit WHERE 0) AS valid
`

func (q *Queries) ValidateSchema(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, validateSchema)
	var valid int64
	err := row.Scan(&valid)
	return valid, err
}
