-- Static persistent SQL is generated by sqlc. Dimension-specific vec0
-- identifiers remain adapter-owned dynamic SQL.

-- name: GetSchemaVersion :one
SELECT version
FROM semantic_schema
WHERE id = 1;

-- name: ValidateSchema :one
SELECT
    (SELECT count(singleton) + count(model) + count(dimension)
     FROM vector_database
     WHERE 0) +
    (SELECT count(id) + count(vector_id) + count(embedding)
     FROM vectors
     WHERE 0) +
    (SELECT count(id) + count(zone_id) + count(name)
     FROM namespace_config
     WHERE 0) +
    (SELECT count(id) + count(zone_id) + count(namespace_row_id) + count(vector_row_id)
     FROM namespace_vectors
     WHERE 0) +
    (SELECT count(id) + count(version)
     FROM semantic_schema
     WHERE 0) AS valid;

-- name: CreateVectorDatabase :exec
INSERT INTO vector_database (singleton, model, dimension) VALUES (1, ?, 0);

-- name: GetVectorDatabase :one
SELECT model, dimension FROM vector_database WHERE singleton = 1;

-- name: SetVectorDimension :exec
UPDATE vector_database SET dimension = ? WHERE singleton = 1 AND dimension = 0;

-- name: RetainVector :exec
INSERT INTO vectors (vector_id, embedding)
VALUES (sqlc.arg(vector_id), sqlc.arg(embedding))
ON CONFLICT (vector_id) DO NOTHING;

-- name: GetVector :one
SELECT id, vector_id, embedding
FROM vectors
WHERE vector_id = sqlc.arg(vector_id);

-- name: ListVectors :many
SELECT vector_id, embedding
FROM vectors
WHERE vector_id IN (sqlc.slice('vector_ids'))
ORDER BY vector_id;

-- name: RetainNamespace :exec
INSERT INTO namespace_config (zone_id, name)
VALUES (sqlc.arg(zone_id), sqlc.arg(name))
ON CONFLICT (zone_id, name) DO NOTHING;

-- name: GetNamespace :one
SELECT id, zone_id, name
FROM namespace_config
WHERE zone_id = sqlc.arg(zone_id) AND name = sqlc.arg(name);

-- name: RetainNamespaceVector :one
INSERT INTO namespace_vectors (zone_id, namespace_row_id, vector_row_id)
VALUES (sqlc.arg(zone_id), sqlc.arg(namespace_row_id), sqlc.arg(vector_row_id))
ON CONFLICT (zone_id, namespace_row_id, vector_row_id) DO NOTHING
RETURNING id;

-- name: CountNamespaceVectors :one
SELECT count(*)
FROM namespace_vectors
WHERE zone_id = sqlc.arg(zone_id) AND namespace_row_id = sqlc.arg(namespace_row_id);

-- name: ListNamespaceVectorIDs :many
SELECT vector.vector_id
FROM namespace_vectors AS member
JOIN vectors AS vector
  ON vector.id = member.vector_row_id
WHERE member.zone_id = sqlc.arg(zone_id)
  AND member.namespace_row_id = sqlc.arg(namespace_row_id)
  AND vector.vector_id > sqlc.arg(after_id)
ORDER BY vector.vector_id
LIMIT sqlc.arg(page_limit);

-- name: GetNamespaceVector :one
SELECT member.zone_id, vector.vector_id, vector.embedding
FROM namespace_vectors AS member
JOIN vectors AS vector
  ON vector.id = member.vector_row_id
WHERE member.zone_id = sqlc.arg(zone_id)
  AND member.namespace_row_id = sqlc.arg(namespace_row_id)
  AND vector.vector_id = sqlc.arg(vector_id);

-- name: DeleteNamespaceVectors :exec
DELETE FROM namespace_vectors
WHERE zone_id = sqlc.arg(zone_id) AND namespace_row_id = sqlc.arg(namespace_row_id);

-- name: DeleteNamespace :exec
DELETE FROM namespace_config
WHERE zone_id = sqlc.arg(zone_id) AND id = sqlc.arg(id);
