// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type CommunityEntity struct {
	ZoneID         string
	CommunitySetID string
	EntityID       string
	Version        int64
}

type CommunityMember struct {
	ZoneID         string
	CommunitySetID string
	CommunityID    string
	MemberOrdinal  int64
	EntityID       string
}

type CommunityRelation struct {
	ZoneID         string
	CommunitySetID string
	RelationID     string
	Version        int64
}

type CommunityReportPublication struct {
	ZoneID       string
	StructureID  string
	EpochID      int64
	ReportSetID  string
	VectorsReady int64
	CreatedAt    string
}

type CommunitySchema struct {
	ID      int64
	Version int64
}

type CommunitySet struct {
	ZoneID                       string
	ID                           string
	DetectorVersion              int64
	MaxClusterSize               int64
	UseLargestConnectedComponent int64
	Seed                         int64
	CreatedAt                    string
}

type CommunitySetCommunity struct {
	ZoneID            string
	CommunitySetID    string
	CommunityID       string
	Number            int64
	Level             int64
	ParentCommunityID sql.NullString
	Final             int64
	Unsplittable      int64
}

type CommunityStructure struct {
	ZoneID          string
	ID              string
	CommunitySetID  string
	CorporaID       string
	KnowledgeDigest string
	CreatedAt       string
}

type CommunityStructureState struct {
	ZoneID                 string
	StructureID            string
	PendingRelationChanges int64
}

type Report struct {
	ZoneID            string
	ID                string
	CommunityID       string
	Period            string
	Title             string
	Summary           string
	Rank              float64
	RatingExplanation string
	FullContent       string
	FullContentJson   string
	Model             string
	PromptHash        []byte
	Tokenizer         string
	MaxInputTokens    int64
	MaxReportLength   int64
}

type ReportClaimEvidence struct {
	ZoneID        string
	ReportID      string
	Ordinal       int64
	ClaimID       string
	Version       int64
	EvidenceIndex int64
}

type ReportEntity struct {
	ZoneID   string
	ReportID string
	Ordinal  int64
	EntityID string
	Version  int64
}

type ReportRelation struct {
	ZoneID     string
	ReportID   string
	Ordinal    int64
	RelationID string
	Version    int64
}

type ReportSet struct {
	ZoneID         string
	ID             string
	CommunitySetID string
	CorporaID      string
	CreatedAt      string
}

type ReportSetReport struct {
	ZoneID      string
	ReportSetID string
	CommunityID string
	ReportID    string
}

type ReportTextUnit struct {
	ZoneID     string
	ReportID   string
	Ordinal    int64
	TextUnitID string
}

type StructureClaimVersion struct {
	ZoneID      string
	StructureID string
	ClaimID     string
	Version     int64
}

type StructureEntityVersion struct {
	ZoneID      string
	StructureID string
	EntityID    string
	Version     int64
}

type StructureRelationVersion struct {
	ZoneID      string
	StructureID string
	RelationID  string
	Version     int64
}
