// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddCommunity(ctx context.Context, arg AddCommunityParams) error
	AddCommunityEntity(ctx context.Context, arg AddCommunityEntityParams) error
	AddCommunityMember(ctx context.Context, arg AddCommunityMemberParams) error
	AddCommunityRelation(ctx context.Context, arg AddCommunityRelationParams) error
	AddReportClaimEvidence(ctx context.Context, arg AddReportClaimEvidenceParams) error
	AddReportEntity(ctx context.Context, arg AddReportEntityParams) error
	AddReportRelation(ctx context.Context, arg AddReportRelationParams) error
	AddReportSetReport(ctx context.Context, arg AddReportSetReportParams) error
	AddReportTextUnit(ctx context.Context, arg AddReportTextUnitParams) error
	AddStructureClaimVersion(ctx context.Context, arg AddStructureClaimVersionParams) error
	AddStructureEntityVersion(ctx context.Context, arg AddStructureEntityVersionParams) error
	AddStructureRelationVersion(ctx context.Context, arg AddStructureRelationVersionParams) error
	AdvanceStructureState(ctx context.Context, arg AdvanceStructureStateParams) (int64, error)
	CompleteReportPublication(ctx context.Context, arg CompleteReportPublicationParams) (int64, error)
	CreateCommunitySet(ctx context.Context, arg CreateCommunitySetParams) error
	CreateReport(ctx context.Context, arg CreateReportParams) error
	CreateReportPublication(ctx context.Context, arg CreateReportPublicationParams) (int64, error)
	CreateReportSet(ctx context.Context, arg CreateReportSetParams) error
	CreateStructure(ctx context.Context, arg CreateStructureParams) (int64, error)
	CreateStructureState(ctx context.Context, arg CreateStructureStateParams) (int64, error)
	FindCommunityWithoutParent(ctx context.Context, arg FindCommunityWithoutParentParams) (string, error)
	FindMemberWithoutCommunity(ctx context.Context, arg FindMemberWithoutCommunityParams) (string, error)
	FindMemberWithoutEntity(ctx context.Context, arg FindMemberWithoutEntityParams) (string, error)
	GetCommunitySet(ctx context.Context, arg GetCommunitySetParams) (CommunitySet, error)
	GetReport(ctx context.Context, arg GetReportParams) (Report, error)
	GetReportPublication(ctx context.Context, arg GetReportPublicationParams) (GetReportPublicationRow, error)
	GetReportSet(ctx context.Context, arg GetReportSetParams) (ReportSet, error)
	GetSchemaVersion(ctx context.Context) (int64, error)
	GetStructure(ctx context.Context, arg GetStructureParams) (GetStructureRow, error)
	GetStructureAt(ctx context.Context, arg GetStructureAtParams) (GetStructureAtRow, error)
	GetStructureState(ctx context.Context, zoneID string) (GetStructureStateRow, error)
	ListCommunities(ctx context.Context, arg ListCommunitiesParams) ([]ListCommunitiesRow, error)
	ListCommunityEntities(ctx context.Context, arg ListCommunityEntitiesParams) ([]ListCommunityEntitiesRow, error)
	ListCommunityMembers(ctx context.Context, arg ListCommunityMembersParams) ([]ListCommunityMembersRow, error)
	ListCommunityRelations(ctx context.Context, arg ListCommunityRelationsParams) ([]ListCommunityRelationsRow, error)
	ListReportClaimEvidence(ctx context.Context, arg ListReportClaimEvidenceParams) ([]ListReportClaimEvidenceRow, error)
	ListReportEntities(ctx context.Context, arg ListReportEntitiesParams) ([]ListReportEntitiesRow, error)
	ListReportRelations(ctx context.Context, arg ListReportRelationsParams) ([]ListReportRelationsRow, error)
	ListReportSetReports(ctx context.Context, arg ListReportSetReportsParams) ([]ListReportSetReportsRow, error)
	ListReportTextUnits(ctx context.Context, arg ListReportTextUnitsParams) ([]ListReportTextUnitsRow, error)
	ListStructureClaimVersions(ctx context.Context, arg ListStructureClaimVersionsParams) ([]ListStructureClaimVersionsRow, error)
	ListStructureEntityVersions(ctx context.Context, arg ListStructureEntityVersionsParams) ([]ListStructureEntityVersionsRow, error)
	ListStructureRelationVersions(ctx context.Context, arg ListStructureRelationVersionsParams) ([]ListStructureRelationVersionsRow, error)
	ValidateSchema(ctx context.Context) (int64, error)
}

var _ Querier = (*Queries)(nil)
