// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statements.sql

package db

import (
	"context"
	"database/sql"
)

const addCommunity = `-- name: AddCommunity :exec
INSERT INTO community_set_communities (
    zone_id, community_set_id, community_id, number, level,
    parent_community_id, final, unsplittable
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6,
    ?7, ?8
)
`

type AddCommunityParams struct {
	ZoneID            string
	CommunitySetID    string
	CommunityID       string
	Number            int64
	Level             int64
	ParentCommunityID sql.NullString
	Final             int64
	Unsplittable      int64
}

func (q *Queries) AddCommunity(ctx context.Context, arg AddCommunityParams) error {
	_, err := q.db.ExecContext(ctx, addCommunity,
		arg.ZoneID,
		arg.CommunitySetID,
		arg.CommunityID,
		arg.Number,
		arg.Level,
		arg.ParentCommunityID,
		arg.Final,
		arg.Unsplittable,
	)
	return err
}

const addCommunityEntity = `-- name: AddCommunityEntity :exec
INSERT INTO community_entities (zone_id, community_set_id, entity_id, version)
VALUES (
    ?1, ?2,
    ?3, ?4
)
`

type AddCommunityEntityParams struct {
	ZoneID         string
	CommunitySetID string
	EntityID       string
	Version        int64
}

func (q *Queries) AddCommunityEntity(ctx context.Context, arg AddCommunityEntityParams) error {
	_, err := q.db.ExecContext(ctx, addCommunityEntity,
		arg.ZoneID,
		arg.CommunitySetID,
		arg.EntityID,
		arg.Version,
	)
	return err
}

const addCommunityMember = `-- name: AddCommunityMember :exec
INSERT INTO community_members (
    zone_id, community_set_id, community_id, member_ordinal, entity_id
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5
)
`

type AddCommunityMemberParams struct {
	ZoneID         string
	CommunitySetID string
	CommunityID    string
	MemberOrdinal  int64
	EntityID       string
}

func (q *Queries) AddCommunityMember(ctx context.Context, arg AddCommunityMemberParams) error {
	_, err := q.db.ExecContext(ctx, addCommunityMember,
		arg.ZoneID,
		arg.CommunitySetID,
		arg.CommunityID,
		arg.MemberOrdinal,
		arg.EntityID,
	)
	return err
}

const addCommunityRelation = `-- name: AddCommunityRelation :exec
INSERT INTO community_relations (zone_id, community_set_id, relation_id, version)
VALUES (
    ?1, ?2,
    ?3, ?4
)
`

type AddCommunityRelationParams struct {
	ZoneID         string
	CommunitySetID string
	RelationID     string
	Version        int64
}

func (q *Queries) AddCommunityRelation(ctx context.Context, arg AddCommunityRelationParams) error {
	_, err := q.db.ExecContext(ctx, addCommunityRelation,
		arg.ZoneID,
		arg.CommunitySetID,
		arg.RelationID,
		arg.Version,
	)
	return err
}

const addReportClaimEvidence = `-- name: AddReportClaimEvidence :exec
INSERT INTO report_claim_evidence (
    zone_id, report_id, ordinal, claim_id, version, evidence_index
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6
)
`

type AddReportClaimEvidenceParams struct {
	ZoneID        string
	ReportID      string
	Ordinal       int64
	ClaimID       string
	Version       int64
	EvidenceIndex int64
}

func (q *Queries) AddReportClaimEvidence(ctx context.Context, arg AddReportClaimEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, addReportClaimEvidence,
		arg.ZoneID,
		arg.ReportID,
		arg.Ordinal,
		arg.ClaimID,
		arg.Version,
		arg.EvidenceIndex,
	)
	return err
}

const addReportEntity = `-- name: AddReportEntity :exec
INSERT INTO report_entities (zone_id, report_id, ordinal, entity_id, version)
VALUES (
    ?1, ?2, ?3,
    ?4, ?5
)
`

type AddReportEntityParams struct {
	ZoneID   string
	ReportID string
	Ordinal  int64
	EntityID string
	Version  int64
}

func (q *Queries) AddReportEntity(ctx context.Context, arg AddReportEntityParams) error {
	_, err := q.db.ExecContext(ctx, addReportEntity,
		arg.ZoneID,
		arg.ReportID,
		arg.Ordinal,
		arg.EntityID,
		arg.Version,
	)
	return err
}

const addReportRelation = `-- name: AddReportRelation :exec
INSERT INTO report_relations (zone_id, report_id, ordinal, relation_id, version)
VALUES (
    ?1, ?2, ?3,
    ?4, ?5
)
`

type AddReportRelationParams struct {
	ZoneID     string
	ReportID   string
	Ordinal    int64
	RelationID string
	Version    int64
}

func (q *Queries) AddReportRelation(ctx context.Context, arg AddReportRelationParams) error {
	_, err := q.db.ExecContext(ctx, addReportRelation,
		arg.ZoneID,
		arg.ReportID,
		arg.Ordinal,
		arg.RelationID,
		arg.Version,
	)
	return err
}

const addReportSetReport = `-- name: AddReportSetReport :exec
INSERT INTO report_set_reports (zone_id, report_set_id, community_id, report_id)
VALUES (
    ?1, ?2,
    ?3, ?4
)
`

type AddReportSetReportParams struct {
	ZoneID      string
	ReportSetID string
	CommunityID string
	ReportID    string
}

func (q *Queries) AddReportSetReport(ctx context.Context, arg AddReportSetReportParams) error {
	_, err := q.db.ExecContext(ctx, addReportSetReport,
		arg.ZoneID,
		arg.ReportSetID,
		arg.CommunityID,
		arg.ReportID,
	)
	return err
}

const addReportTextUnit = `-- name: AddReportTextUnit :exec
INSERT INTO report_text_units (zone_id, report_id, ordinal, text_unit_id)
VALUES (
    ?1, ?2,
    ?3, ?4
)
`

type AddReportTextUnitParams struct {
	ZoneID     string
	ReportID   string
	Ordinal    int64
	TextUnitID string
}

func (q *Queries) AddReportTextUnit(ctx context.Context, arg AddReportTextUnitParams) error {
	_, err := q.db.ExecContext(ctx, addReportTextUnit,
		arg.ZoneID,
		arg.ReportID,
		arg.Ordinal,
		arg.TextUnitID,
	)
	return err
}

const addStructureClaimVersion = `-- name: AddStructureClaimVersion :exec
INSERT INTO structure_claim_versions (zone_id, structure_id, claim_id, version)
VALUES (?1, ?2, ?3, ?4)
`

type AddStructureClaimVersionParams struct {
	ZoneID      string
	StructureID string
	ClaimID     string
	Version     int64
}

func (q *Queries) AddStructureClaimVersion(ctx context.Context, arg AddStructureClaimVersionParams) error {
	_, err := q.db.ExecContext(ctx, addStructureClaimVersion,
		arg.ZoneID,
		arg.StructureID,
		arg.ClaimID,
		arg.Version,
	)
	return err
}

const addStructureEntityVersion = `-- name: AddStructureEntityVersion :exec
INSERT INTO structure_entity_versions (zone_id, structure_id, entity_id, version)
VALUES (?1, ?2, ?3, ?4)
`

type AddStructureEntityVersionParams struct {
	ZoneID      string
	StructureID string
	EntityID    string
	Version     int64
}

func (q *Queries) AddStructureEntityVersion(ctx context.Context, arg AddStructureEntityVersionParams) error {
	_, err := q.db.ExecContext(ctx, addStructureEntityVersion,
		arg.ZoneID,
		arg.StructureID,
		arg.EntityID,
		arg.Version,
	)
	return err
}

const addStructureRelationVersion = `-- name: AddStructureRelationVersion :exec
INSERT INTO structure_relation_versions (zone_id, structure_id, relation_id, version)
VALUES (?1, ?2, ?3, ?4)
`

type AddStructureRelationVersionParams struct {
	ZoneID      string
	StructureID string
	RelationID  string
	Version     int64
}

func (q *Queries) AddStructureRelationVersion(ctx context.Context, arg AddStructureRelationVersionParams) error {
	_, err := q.db.ExecContext(ctx, addStructureRelationVersion,
		arg.ZoneID,
		arg.StructureID,
		arg.RelationID,
		arg.Version,
	)
	return err
}

const advanceStructureState = `-- name: AdvanceStructureState :execrows
UPDATE community_structure_state
SET structure_id = ?1,
    pending_relation_changes = ?2
WHERE zone_id = ?3
  AND structure_id = ?4
`

type AdvanceStructureStateParams struct {
	StructureID            string
	PendingRelationChanges int64
	ZoneID                 string
	ExpectedStructureID    string
}

func (q *Queries) AdvanceStructureState(ctx context.Context, arg AdvanceStructureStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceStructureState,
		arg.StructureID,
		arg.PendingRelationChanges,
		arg.ZoneID,
		arg.ExpectedStructureID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeReportPublication = `-- name: CompleteReportPublication :execrows
UPDATE community_report_publications
SET vectors_ready = 1
WHERE zone_id = ?1
  AND structure_id = ?2
  AND report_set_id = ?3
  AND vectors_ready = 0
`

type CompleteReportPublicationParams struct {
	ZoneID      string
	StructureID string
	ReportSetID string
}

func (q *Queries) CompleteReportPublication(ctx context.Context, arg CompleteReportPublicationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeReportPublication, arg.ZoneID, arg.StructureID, arg.ReportSetID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createCommunitySet = `-- name: CreateCommunitySet :exec
INSERT INTO community_sets (
    zone_id, id, detector_version, max_cluster_size,
    use_largest_connected_component, seed, created_at
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5,
    ?6, ?7
)
`

type CreateCommunitySetParams struct {
	ZoneID                       string
	ID                           string
	DetectorVersion              int64
	MaxClusterSize               int64
	UseLargestConnectedComponent int64
	Seed                         int64
	CreatedAt                    string
}

func (q *Queries) CreateCommunitySet(ctx context.Context, arg CreateCommunitySetParams) error {
	_, err := q.db.ExecContext(ctx, createCommunitySet,
		arg.ZoneID,
		arg.ID,
		arg.DetectorVersion,
		arg.MaxClusterSize,
		arg.UseLargestConnectedComponent,
		arg.Seed,
		arg.CreatedAt,
	)
	return err
}

const createReport = `-- name: CreateReport :exec
INSERT INTO reports (
    zone_id, id, community_id, period, title, summary, rank,
    rating_explanation, full_content, full_content_json, model,
    prompt_hash, tokenizer, max_input_tokens, max_report_length
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9,
    ?10, ?11, ?12,
    ?13, ?14, ?15
)
`

type CreateReportParams struct {
	ZoneID            string
	ID                string
	CommunityID       string
	Period            string
	Title             string
	Summary           string
	Rank              float64
	RatingExplanation string
	FullContent       string
	FullContentJson   string
	Model             string
	PromptHash        []byte
	Tokenizer         string
	MaxInputTokens    int64
	MaxReportLength   int64
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) error {
	_, err := q.db.ExecContext(ctx, createReport,
		arg.ZoneID,
		arg.ID,
		arg.CommunityID,
		arg.Period,
		arg.Title,
		arg.Summary,
		arg.Rank,
		arg.RatingExplanation,
		arg.FullContent,
		arg.FullContentJson,
		arg.Model,
		arg.PromptHash,
		arg.Tokenizer,
		arg.MaxInputTokens,
		arg.MaxReportLength,
	)
	return err
}

const createReportPublication = `-- name: CreateReportPublication :execrows
INSERT OR IGNORE INTO community_report_publications (
    zone_id, structure_id, epoch_id, report_set_id, vectors_ready, created_at
) VALUES (
    ?1, ?2, ?3,
    ?4, 0, ?5
)
`

type CreateReportPublicationParams struct {
	ZoneID      string
	StructureID string
	EpochID     int64
	ReportSetID string
	CreatedAt   string
}

func (q *Queries) CreateReportPublication(ctx context.Context, arg CreateReportPublicationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createReportPublication,
		arg.ZoneID,
		arg.StructureID,
		arg.EpochID,
		arg.ReportSetID,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createReportSet = `-- name: CreateReportSet :exec
INSERT INTO report_sets (zone_id, id, community_set_id, corpora_id, created_at)
VALUES (
    ?1, ?2, ?3,
    ?4, ?5
)
`

type CreateReportSetParams struct {
	ZoneID         string
	ID             string
	CommunitySetID string
	CorporaID      string
	CreatedAt      string
}

func (q *Queries) CreateReportSet(ctx context.Context, arg CreateReportSetParams) error {
	_, err := q.db.ExecContext(ctx, createReportSet,
		arg.ZoneID,
		arg.ID,
		arg.CommunitySetID,
		arg.CorporaID,
		arg.CreatedAt,
	)
	return err
}

const createStructure = `-- name: CreateStructure :execrows
INSERT OR IGNORE INTO community_structures (
    zone_id, id, community_set_id, corpora_id, knowledge_digest, created_at
) VALUES (
    ?1, ?2, ?3,
    ?4, ?5, ?6
)
`

type CreateStructureParams struct {
	ZoneID          string
	ID              string
	CommunitySetID  string
	CorporaID       string
	KnowledgeDigest string
	CreatedAt       string
}

func (q *Queries) CreateStructure(ctx context.Context, arg CreateStructureParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createStructure,
		arg.ZoneID,
		arg.ID,
		arg.CommunitySetID,
		arg.CorporaID,
		arg.KnowledgeDigest,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createStructureState = `-- name: CreateStructureState :execrows
INSERT OR IGNORE INTO community_structure_state (
    zone_id, structure_id, pending_relation_changes
) VALUES (
    ?1, ?2, ?3
)
`

type CreateStructureStateParams struct {
	ZoneID                 string
	StructureID            string
	PendingRelationChanges int64
}

func (q *Queries) CreateStructureState(ctx context.Context, arg CreateStructureStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createStructureState, arg.ZoneID, arg.StructureID, arg.PendingRelationChanges)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findCommunityWithoutParent = `-- name: FindCommunityWithoutParent :one
SELECT child.community_id
FROM community_set_communities AS child
WHERE child.zone_id = ?1
  AND child.community_set_id = ?2
  AND child.parent_community_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM community_set_communities AS parent
      WHERE parent.zone_id = child.zone_id
        AND parent.community_set_id = child.community_set_id
        AND parent.community_id = child.parent_community_id
  )
LIMIT 1
`

type FindCommunityWithoutParentParams struct {
	ZoneID         string
	CommunitySetID string
}

func (q *Queries) FindCommunityWithoutParent(ctx context.Context, arg FindCommunityWithoutParentParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findCommunityWithoutParent, arg.ZoneID, arg.CommunitySetID)
	var community_id string
	err := row.Scan(&community_id)
	return community_id, err
}

const findMemberWithoutCommunity = `-- name: FindMemberWithoutCommunity :one
SELECT member.entity_id
FROM community_members AS member
WHERE member.zone_id = ?1
  AND member.community_set_id = ?2
  AND NOT EXISTS (
      SELECT 1 FROM community_set_communities AS current
      WHERE current.zone_id = member.zone_id
        AND current.community_set_id = member.community_set_id
        AND current.community_id = member.community_id
  )
LIMIT 1
`

type FindMemberWithoutCommunityParams struct {
	ZoneID         string
	CommunitySetID string
}

func (q *Queries) FindMemberWithoutCommunity(ctx context.Context, arg FindMemberWithoutCommunityParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findMemberWithoutCommunity, arg.ZoneID, arg.CommunitySetID)
	var entity_id string
	err := row.Scan(&entity_id)
	return entity_id, err
}

const findMemberWithoutEntity = `-- name: FindMemberWithoutEntity :one
SELECT member.entity_id
FROM community_members AS member
WHERE member.zone_id = ?1
  AND member.community_set_id = ?2
  AND NOT EXISTS (
      SELECT 1 FROM community_entities AS entity
      WHERE entity.zone_id = member.zone_id
        AND entity.community_set_id = member.community_set_id
        AND entity.entity_id = member.entity_id
  )
LIMIT 1
`

type FindMemberWithoutEntityParams struct {
	ZoneID         string
	CommunitySetID string
}

func (q *Queries) FindMemberWithoutEntity(ctx context.Context, arg FindMemberWithoutEntityParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findMemberWithoutEntity, arg.ZoneID, arg.CommunitySetID)
	var entity_id string
	err := row.Scan(&entity_id)
	return entity_id, err
}

const getCommunitySet = `-- name: GetCommunitySet :one
SELECT zone_id, id, detector_version, max_cluster_size,
       use_largest_connected_component, seed, created_at
FROM community_sets
WHERE zone_id = ?1 AND id = ?2
`

type GetCommunitySetParams struct {
	ZoneID string
	ID     string
}

func (q *Queries) GetCommunitySet(ctx context.Context, arg GetCommunitySetParams) (CommunitySet, error) {
	row := q.db.QueryRowContext(ctx, getCommunitySet, arg.ZoneID, arg.ID)
	var i CommunitySet
	err := row.Scan(
		&i.ZoneID,
		&i.ID,
		&i.DetectorVersion,
		&i.MaxClusterSize,
		&i.UseLargestConnectedComponent,
		&i.Seed,
		&i.CreatedAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT zone_id, id, community_id, period, title, summary, rank,
       rating_explanation, full_content, full_content_json, model,
       prompt_hash, tokenizer, max_input_tokens, max_report_length
FROM reports
WHERE zone_id = ?1 AND id = ?2
`

type GetReportParams struct {
	ZoneID string
	ID     string
}

func (q *Queries) GetReport(ctx context.Context, arg GetReportParams) (Report, error) {
	row := q.db.QueryRowContext(ctx, getReport, arg.ZoneID, arg.ID)
	var i Report
	err := row.Scan(
		&i.ZoneID,
		&i.ID,
		&i.CommunityID,
		&i.Period,
		&i.Title,
		&i.Summary,
		&i.Rank,
		&i.RatingExplanation,
		&i.FullContent,
		&i.FullContentJson,
		&i.Model,
		&i.PromptHash,
		&i.Tokenizer,
		&i.MaxInputTokens,
		&i.MaxReportLength,
	)
	return i, err
}

const getReportPublication = `-- name: GetReportPublication :one
SELECT epoch_id, structure_id, report_set_id, vectors_ready, created_at
FROM community_report_publications
WHERE zone_id = ?1 AND structure_id = ?2
`

type GetReportPublicationParams struct {
	ZoneID      string
	StructureID string
}

type GetReportPublicationRow struct {
	EpochID      int64
	StructureID  string
	ReportSetID  string
	VectorsReady int64
	CreatedAt    string
}

func (q *Queries) GetReportPublication(ctx context.Context, arg GetReportPublicationParams) (GetReportPublicationRow, error) {
	row := q.db.QueryRowContext(ctx, getReportPublication, arg.ZoneID, arg.StructureID)
	var i GetReportPublicationRow
	err := row.Scan(
		&i.EpochID,
		&i.StructureID,
		&i.ReportSetID,
		&i.VectorsReady,
		&i.CreatedAt,
	)
	return i, err
}

const getReportSet = `-- name: GetReportSet :one
SELECT zone_id, id, community_set_id, corpora_id, created_at
FROM report_sets
WHERE zone_id = ?1 AND id = ?2
`

type GetReportSetParams struct {
	ZoneID string
	ID     string
}

func (q *Queries) GetReportSet(ctx context.Context, arg GetReportSetParams) (ReportSet, error) {
	row := q.db.QueryRowContext(ctx, getReportSet, arg.ZoneID, arg.ID)
	var i ReportSet
	err := row.Scan(
		&i.ZoneID,
		&i.ID,
		&i.CommunitySetID,
		&i.CorporaID,
		&i.CreatedAt,
	)
	return i, err
}

const getSchemaVersion = `-- name: GetSchemaVersion :one
SELECT version FROM community_schema WHERE id = 1
`

func (q *Queries) GetSchemaVersion(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSchemaVersion)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getStructure = `-- name: GetStructure :one
SELECT id, community_set_id, corpora_id, knowledge_digest, created_at
FROM community_structures
WHERE zone_id = ?1 AND id = ?2
`

type GetStructureParams struct {
	ZoneID string
	ID     string
}

type GetStructureRow struct {
	ID              string
	CommunitySetID  string
	CorporaID       string
	KnowledgeDigest string
	CreatedAt       string
}

func (q *Queries) GetStructure(ctx context.Context, arg GetStructureParams) (GetStructureRow, error) {
	row := q.db.QueryRowContext(ctx, getStructure, arg.ZoneID, arg.ID)
	var i GetStructureRow
	err := row.Scan(
		&i.ID,
		&i.CommunitySetID,
		&i.CorporaID,
		&i.KnowledgeDigest,
		&i.CreatedAt,
	)
	return i, err
}

const getStructureAt = `-- name: GetStructureAt :one
SELECT id, community_set_id, corpora_id, knowledge_digest, created_at
FROM community_structures
WHERE zone_id = ?1
  AND corpora_id = ?2
  AND knowledge_digest = ?3
`

type GetStructureAtParams struct {
	ZoneID          string
	CorporaID       string
	KnowledgeDigest string
}

type GetStructureAtRow struct {
	ID              string
	CommunitySetID  string
	CorporaID       string
	KnowledgeDigest string
	CreatedAt       string
}

func (q *Queries) GetStructureAt(ctx context.Context, arg GetStructureAtParams) (GetStructureAtRow, error) {
	row := q.db.QueryRowContext(ctx, getStructureAt, arg.ZoneID, arg.CorporaID, arg.KnowledgeDigest)
	var i GetStructureAtRow
	err := row.Scan(
		&i.ID,
		&i.CommunitySetID,
		&i.CorporaID,
		&i.KnowledgeDigest,
		&i.CreatedAt,
	)
	return i, err
}

const getStructureState = `-- name: GetStructureState :one
SELECT structure_id, pending_relation_changes
FROM community_structure_state
WHERE zone_id = ?1
`

type GetStructureStateRow struct {
	StructureID            string
	PendingRelationChanges int64
}

func (q *Queries) GetStructureState(ctx context.Context, zoneID string) (GetStructureStateRow, error) {
	row := q.db.QueryRowContext(ctx, getStructureState, zoneID)
	var i GetStructureStateRow
	err := row.Scan(&i.StructureID, &i.PendingRelationChanges)
	return i, err
}

const listCommunities = `-- name: ListCommunities :many
SELECT community_id, number, level, parent_community_id, final, unsplittable
FROM community_set_communities
WHERE zone_id = ?1 AND community_set_id = ?2
ORDER BY level, number
`

type ListCommunitiesParams struct {
	ZoneID         string
	CommunitySetID string
}

type ListCommunitiesRow struct {
	CommunityID       string
	Number            int64
	Level             int64
	ParentCommunityID sql.NullString
	Final             int64
	Unsplittable      int64
}

func (q *Queries) ListCommunities(ctx context.Context, arg ListCommunitiesParams) ([]ListCommunitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommunities, arg.ZoneID, arg.CommunitySetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommunitiesRow{}
	for rows.Next() {
		var i ListCommunitiesRow
		if err := rows.Scan(
			&i.CommunityID,
			&i.Number,
			&i.Level,
			&i.ParentCommunityID,
			&i.Final,
			&i.Unsplittable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunityEntities = `-- name: ListCommunityEntities :many
SELECT entity_id, version FROM community_entities
WHERE zone_id = ?1 AND community_set_id = ?2
ORDER BY entity_id
`

type ListCommunityEntitiesParams struct {
	ZoneID         string
	CommunitySetID string
}

type ListCommunityEntitiesRow struct {
	EntityID string
	Version  int64
}

func (q *Queries) ListCommunityEntities(ctx context.Context, arg ListCommunityEntitiesParams) ([]ListCommunityEntitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommunityEntities, arg.ZoneID, arg.CommunitySetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommunityEntitiesRow{}
	for rows.Next() {
		var i ListCommunityEntitiesRow
		if err := rows.Scan(&i.EntityID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunityMembers = `-- name: ListCommunityMembers :many
SELECT member_ordinal, entity_id FROM community_members
WHERE zone_id = ?1
  AND community_set_id = ?2
  AND community_id = ?3
ORDER BY member_ordinal
`

type ListCommunityMembersParams struct {
	ZoneID         string
	CommunitySetID string
	CommunityID    string
}

type ListCommunityMembersRow struct {
	MemberOrdinal int64
	EntityID      string
}

func (q *Queries) ListCommunityMembers(ctx context.Context, arg ListCommunityMembersParams) ([]ListCommunityMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommunityMembers, arg.ZoneID, arg.CommunitySetID, arg.CommunityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommunityMembersRow{}
	for rows.Next() {
		var i ListCommunityMembersRow
		if err := rows.Scan(&i.MemberOrdinal, &i.EntityID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommunityRelations = `-- name: ListCommunityRelations :many
SELECT relation_id, version FROM community_relations
WHERE zone_id = ?1 AND community_set_id = ?2
ORDER BY relation_id
`

type ListCommunityRelationsParams struct {
	ZoneID         string
	CommunitySetID string
}

type ListCommunityRelationsRow struct {
	RelationID string
	Version    int64
}

func (q *Queries) ListCommunityRelations(ctx context.Context, arg ListCommunityRelationsParams) ([]ListCommunityRelationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCommunityRelations, arg.ZoneID, arg.CommunitySetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCommunityRelationsRow{}
	for rows.Next() {
		var i ListCommunityRelationsRow
		if err := rows.Scan(&i.RelationID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportClaimEvidence = `-- name: ListReportClaimEvidence :many
SELECT ordinal, claim_id, version, evidence_index FROM report_claim_evidence
WHERE zone_id = ?1 AND report_id = ?2
ORDER BY ordinal
`

type ListReportClaimEvidenceParams struct {
	ZoneID   string
	ReportID string
}

type ListReportClaimEvidenceRow struct {
	Ordinal       int64
	ClaimID       string
	Version       int64
	EvidenceIndex int64
}

func (q *Queries) ListReportClaimEvidence(ctx context.Context, arg ListReportClaimEvidenceParams) ([]ListReportClaimEvidenceRow, error) {
	rows, err := q.db.QueryContext(ctx, listReportClaimEvidence, arg.ZoneID, arg.ReportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportClaimEvidenceRow{}
	for rows.Next() {
		var i ListReportClaimEvidenceRow
		if err := rows.Scan(
			&i.Ordinal,
			&i.ClaimID,
			&i.Version,
			&i.EvidenceIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportEntities = `-- name: ListReportEntities :many
SELECT ordinal, entity_id, version FROM report_entities
WHERE zone_id = ?1 AND report_id = ?2
ORDER BY ordinal
`

type ListReportEntitiesParams struct {
	ZoneID   string
	ReportID string
}

type ListReportEntitiesRow struct {
	Ordinal  int64
	EntityID string
	Version  int64
}

func (q *Queries) ListReportEntities(ctx context.Context, arg ListReportEntitiesParams) ([]ListReportEntitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listReportEntities, arg.ZoneID, arg.ReportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportEntitiesRow{}
	for rows.Next() {
		var i ListReportEntitiesRow
		if err := rows.Scan(&i.Ordinal, &i.EntityID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportRelations = `-- name: ListReportRelations :many
SELECT ordinal, relation_id, version FROM report_relations
WHERE zone_id = ?1 AND report_id = ?2
ORDER BY ordinal
`

type ListReportRelationsParams struct {
	ZoneID   string
	ReportID string
}

type ListReportRelationsRow struct {
	Ordinal    int64
	RelationID string
	Version    int64
}

func (q *Queries) ListReportRelations(ctx context.Context, arg ListReportRelationsParams) ([]ListReportRelationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReportRelations, arg.ZoneID, arg.ReportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportRelationsRow{}
	for rows.Next() {
		var i ListReportRelationsRow
		if err := rows.Scan(&i.Ordinal, &i.RelationID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportSetReports = `-- name: ListReportSetReports :many
SELECT community_id, report_id FROM report_set_reports
WHERE zone_id = ?1 AND report_set_id = ?2
ORDER BY community_id
`

type ListReportSetReportsParams struct {
	ZoneID      string
	ReportSetID string
}

type ListReportSetReportsRow struct {
	CommunityID string
	ReportID    string
}

func (q *Queries) ListReportSetReports(ctx context.Context, arg ListReportSetReportsParams) ([]ListReportSetReportsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReportSetReports, arg.ZoneID, arg.ReportSetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportSetReportsRow{}
	for rows.Next() {
		var i ListReportSetReportsRow
		if err := rows.Scan(&i.CommunityID, &i.ReportID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReportTextUnits = `-- name: ListReportTextUnits :many
SELECT ordinal, text_unit_id FROM report_text_units
WHERE zone_id = ?1 AND report_id = ?2
ORDER BY ordinal
`

type ListReportTextUnitsParams struct {
	ZoneID   string
	ReportID string
}

type ListReportTextUnitsRow struct {
	Ordinal    int64
	TextUnitID string
}

func (q *Queries) ListReportTextUnits(ctx context.Context, arg ListReportTextUnitsParams) ([]ListReportTextUnitsRow, error) {
	rows, err := q.db.QueryContext(ctx, listReportTextUnits, arg.ZoneID, arg.ReportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReportTextUnitsRow{}
	for rows.Next() {
		var i ListReportTextUnitsRow
		if err := rows.Scan(&i.Ordinal, &i.TextUnitID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStructureClaimVersions = `-- name: ListStructureClaimVersions :many
SELECT claim_id, version FROM structure_claim_versions
WHERE zone_id = ?1 AND structure_id = ?2
ORDER BY claim_id
`

type ListStructureClaimVersionsParams struct {
	ZoneID      string
	StructureID string
}

type ListStructureClaimVersionsRow struct {
	ClaimID string
	Version int64
}

func (q *Queries) ListStructureClaimVersions(ctx context.Context, arg ListStructureClaimVersionsParams) ([]ListStructureClaimVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStructureClaimVersions, arg.ZoneID, arg.StructureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStructureClaimVersionsRow{}
	for rows.Next() {
		var i ListStructureClaimVersionsRow
		if err := rows.Scan(&i.ClaimID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStructureEntityVersions = `-- name: ListStructureEntityVersions :many
SELECT entity_id, version FROM structure_entity_versions
WHERE zone_id = ?1 AND structure_id = ?2
ORDER BY entity_id
`

type ListStructureEntityVersionsParams struct {
	ZoneID      string
	StructureID string
}

type ListStructureEntityVersionsRow struct {
	EntityID string
	Version  int64
}

func (q *Queries) ListStructureEntityVersions(ctx context.Context, arg ListStructureEntityVersionsParams) ([]ListStructureEntityVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStructureEntityVersions, arg.ZoneID, arg.StructureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStructureEntityVersionsRow{}
	for rows.Next() {
		var i ListStructureEntityVersionsRow
		if err := rows.Scan(&i.EntityID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStructureRelationVersions = `-- name: ListStructureRelationVersions :many
SELECT relation_id, version FROM structure_relation_versions
WHERE zone_id = ?1 AND structure_id = ?2
ORDER BY relation_id
`

type ListStructureRelationVersionsParams struct {
	ZoneID      string
	StructureID string
}

type ListStructureRelationVersionsRow struct {
	RelationID string
	Version    int64
}

func (q *Queries) ListStructureRelationVersions(ctx context.Context, arg ListStructureRelationVersionsParams) ([]ListStructureRelationVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listStructureRelationVersions, arg.ZoneID, arg.StructureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStructureRelationVersionsRow{}
	for rows.Next() {
		var i ListStructureRelationVersionsRow
		if err := rows.Scan(&i.RelationID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validateSchema = `-- name: ValidateSchema :one
SELECT
    (SELECT count(*) FROM community_sets WHERE 0) +
    (SELECT count(*) FROM community_structures WHERE 0) +
	(SELECT count(*) FROM structure_entity_versions WHERE 0) +
	(SELECT count(*) FROM structure_relation_versions WHERE 0) +
	(SELECT count(*) FROM structure_claim_versions WHERE 0) +
    (SELECT count(*) FROM community_structure_state WHERE 0) +
    (SELECT count(*) FROM community_entities WHERE 0) +
    (SELECT count(*) FROM community_relations WHERE 0) +
    (SELECT count(*) FROM community_set_communities WHERE 0) +
    (SELECT count(*) FROM community_members WHERE 0) +
    (SELECT count(*) FROM reports WHERE 0) +
    (SELECT count(*) FROM report_entities WHERE 0) +
    (SELECT count(*) FROM report_relations WHERE 0) +
    (SELECT count(*) FROM report_claim_evidence WHERE 0) +
    (SELECT count(*) FROM report_text_units WHERE 0) +
    (SELECT count(*) FROM report_sets WHERE 0) +
	(SELECT count(*) FROM community_report_publications WHERE 0) +
    (SELECT count(*) FROM report_set_reports WHERE 0) +
    (SELECT count(*) FROM community_schema WHERE 0) +
    (SELECT count(*) FROM community_set_communities INDEXED BY community_set_communities_by_parent WHERE 0) +
    (SELECT count(*) FROM community_structures INDEXED BY community_structures_by_boundary WHERE 0) +
    (SELECT count(*) FROM community_members INDEXED BY community_members_by_entity WHERE 0) +
    (SELECT count(*) FROM reports INDEXED BY reports_by_community WHERE 0) +
    (SELECT count(*) FROM report_sets INDEXED BY report_sets_by_community_set WHERE 0) AS valid
`

func (q *Queries) ValidateSchema(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, validateSchema)
	var valid int64
	err := row.Scan(&valid)
	return valid, err
}
