// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: candidates.sql

package db

import (
	"context"
	"database/sql"
)

const browsePendingClaimIDs = `-- name: BrowsePendingClaimIDs :many
SELECT DISTINCT v.knowledge_id AS claim_id
FROM knowledge_versions v
WHERE v.zone_id = ?1
  AND v.knowledge_kind = 'claim'
  AND v.knowledge_id > ?2
  AND v.candidate_number > 0
  AND v.resolved_by_source_id IS NULL
ORDER BY v.knowledge_id
LIMIT ?3
`

type BrowsePendingClaimIDsParams struct {
	ZoneID    string
	AfterID   string
	PageLimit int64
}

func (q *Queries) BrowsePendingClaimIDs(ctx context.Context, arg BrowsePendingClaimIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, browsePendingClaimIDs, arg.ZoneID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var claim_id string
		if err := rows.Scan(&claim_id); err != nil {
			return nil, err
		}
		items = append(items, claim_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const browsePendingEntityIDs = `-- name: BrowsePendingEntityIDs :many
SELECT DISTINCT v.knowledge_id AS entity_id
FROM knowledge_versions v
WHERE v.zone_id = ?1
  AND v.knowledge_kind = 'entity'
  AND v.knowledge_id > ?2
  AND v.candidate_number > 0
  AND v.resolved_by_source_id IS NULL
ORDER BY v.knowledge_id
LIMIT ?3
`

type BrowsePendingEntityIDsParams struct {
	ZoneID    string
	AfterID   string
	PageLimit int64
}

func (q *Queries) BrowsePendingEntityIDs(ctx context.Context, arg BrowsePendingEntityIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, browsePendingEntityIDs, arg.ZoneID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var entity_id string
		if err := rows.Scan(&entity_id); err != nil {
			return nil, err
		}
		items = append(items, entity_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const browsePendingRelationIDs = `-- name: BrowsePendingRelationIDs :many
SELECT DISTINCT v.knowledge_id AS relation_id
FROM knowledge_versions v
WHERE v.zone_id = ?1
  AND v.knowledge_kind = 'relation'
  AND v.knowledge_id > ?2
  AND v.candidate_number > 0
  AND v.resolved_by_source_id IS NULL
ORDER BY v.knowledge_id
LIMIT ?3
`

type BrowsePendingRelationIDsParams struct {
	ZoneID    string
	AfterID   string
	PageLimit int64
}

func (q *Queries) BrowsePendingRelationIDs(ctx context.Context, arg BrowsePendingRelationIDsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, browsePendingRelationIDs, arg.ZoneID, arg.AfterID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var relation_id string
		if err := rows.Scan(&relation_id); err != nil {
			return nil, err
		}
		items = append(items, relation_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createClaimCandidate = `-- name: CreateClaimCandidate :exec
INSERT INTO knowledge_versions
    (zone_id, knowledge_kind, knowledge_id, version, candidate_number,
     deleted, content_hash, description, created_by_source_id)
VALUES
    (?1, 'claim', ?2, ?3,
     ?4, 0, ?5, ?6,
     ?7)
`

type CreateClaimCandidateParams struct {
	ZoneID            string
	ClaimID           string
	BaseVersion       int64
	CandidateNumber   int64
	ContentHash       []byte
	Description       string
	CreatedBySourceID string
}

func (q *Queries) CreateClaimCandidate(ctx context.Context, arg CreateClaimCandidateParams) error {
	_, err := q.db.ExecContext(ctx, createClaimCandidate,
		arg.ZoneID,
		arg.ClaimID,
		arg.BaseVersion,
		arg.CandidateNumber,
		arg.ContentHash,
		arg.Description,
		arg.CreatedBySourceID,
	)
	return err
}

const createEntityCandidate = `-- name: CreateEntityCandidate :exec
INSERT INTO knowledge_versions
    (zone_id, knowledge_kind, knowledge_id, version, candidate_number,
     deleted, content_hash, description, created_by_source_id)
VALUES
    (?1, 'entity', ?2, ?3,
     ?4, 0, ?5, ?6,
     ?7)
`

type CreateEntityCandidateParams struct {
	ZoneID            string
	EntityID          string
	BaseVersion       int64
	CandidateNumber   int64
	ContentHash       []byte
	Description       string
	CreatedBySourceID string
}

func (q *Queries) CreateEntityCandidate(ctx context.Context, arg CreateEntityCandidateParams) error {
	_, err := q.db.ExecContext(ctx, createEntityCandidate,
		arg.ZoneID,
		arg.EntityID,
		arg.BaseVersion,
		arg.CandidateNumber,
		arg.ContentHash,
		arg.Description,
		arg.CreatedBySourceID,
	)
	return err
}

const createEntityCandidateAlias = `-- name: CreateEntityCandidateAlias :exec
INSERT INTO entity_version_aliases
    (zone_id, entity_id, version, candidate_number, alias)
VALUES
    (?1, ?2, ?3,
     ?4, ?5)
`

type CreateEntityCandidateAliasParams struct {
	ZoneID          string
	EntityID        string
	BaseVersion     int64
	CandidateNumber int64
	Alias           string
}

func (q *Queries) CreateEntityCandidateAlias(ctx context.Context, arg CreateEntityCandidateAliasParams) error {
	_, err := q.db.ExecContext(ctx, createEntityCandidateAlias,
		arg.ZoneID,
		arg.EntityID,
		arg.BaseVersion,
		arg.CandidateNumber,
		arg.Alias,
	)
	return err
}

const createRelationCandidate = `-- name: CreateRelationCandidate :exec
INSERT INTO knowledge_versions
    (zone_id, knowledge_kind, knowledge_id, version, candidate_number,
     deleted, content_hash, description, created_by_source_id)
VALUES
    (?1, 'relation', ?2, ?3,
     ?4, 0, ?5, ?6,
     ?7)
`

type CreateRelationCandidateParams struct {
	ZoneID            string
	RelationID        string
	BaseVersion       int64
	CandidateNumber   int64
	ContentHash       []byte
	Description       string
	CreatedBySourceID string
}

func (q *Queries) CreateRelationCandidate(ctx context.Context, arg CreateRelationCandidateParams) error {
	_, err := q.db.ExecContext(ctx, createRelationCandidate,
		arg.ZoneID,
		arg.RelationID,
		arg.BaseVersion,
		arg.CandidateNumber,
		arg.ContentHash,
		arg.Description,
		arg.CreatedBySourceID,
	)
	return err
}

const getClaimCandidate = `-- name: GetClaimCandidate :one
SELECT candidate_number, description FROM knowledge_versions
WHERE zone_id = ?1 AND knowledge_kind = 'claim'
  AND knowledge_id = ?2 AND version = ?3
  AND candidate_number > 0 AND content_hash = ?4
  AND resolved_by_source_id IS NULL
`

type GetClaimCandidateParams struct {
	ZoneID      string
	ClaimID     string
	BaseVersion int64
	ContentHash []byte
}

type GetClaimCandidateRow struct {
	CandidateNumber int64
	Description     string
}

func (q *Queries) GetClaimCandidate(ctx context.Context, arg GetClaimCandidateParams) (GetClaimCandidateRow, error) {
	row := q.db.QueryRowContext(ctx, getClaimCandidate,
		arg.ZoneID,
		arg.ClaimID,
		arg.BaseVersion,
		arg.ContentHash,
	)
	var i GetClaimCandidateRow
	err := row.Scan(&i.CandidateNumber, &i.Description)
	return i, err
}

const getEntityCandidate = `-- name: GetEntityCandidate :one
SELECT candidate_number, description FROM knowledge_versions
WHERE zone_id = ?1 AND knowledge_kind = 'entity'
  AND knowledge_id = ?2 AND version = ?3
  AND candidate_number > 0 AND content_hash = ?4
  AND resolved_by_source_id IS NULL
`

type GetEntityCandidateParams struct {
	ZoneID      string
	EntityID    string
	BaseVersion int64
	ContentHash []byte
}

type GetEntityCandidateRow struct {
	CandidateNumber int64
	Description     string
}

func (q *Queries) GetEntityCandidate(ctx context.Context, arg GetEntityCandidateParams) (GetEntityCandidateRow, error) {
	row := q.db.QueryRowContext(ctx, getEntityCandidate,
		arg.ZoneID,
		arg.EntityID,
		arg.BaseVersion,
		arg.ContentHash,
	)
	var i GetEntityCandidateRow
	err := row.Scan(&i.CandidateNumber, &i.Description)
	return i, err
}

const getRelationCandidate = `-- name: GetRelationCandidate :one
SELECT candidate_number, description FROM knowledge_versions
WHERE zone_id = ?1 AND knowledge_kind = 'relation'
  AND knowledge_id = ?2 AND version = ?3
  AND candidate_number > 0 AND content_hash = ?4
  AND resolved_by_source_id IS NULL
`

type GetRelationCandidateParams struct {
	ZoneID      string
	RelationID  string
	BaseVersion int64
	ContentHash []byte
}

type GetRelationCandidateRow struct {
	CandidateNumber int64
	Description     string
}

func (q *Queries) GetRelationCandidate(ctx context.Context, arg GetRelationCandidateParams) (GetRelationCandidateRow, error) {
	row := q.db.QueryRowContext(ctx, getRelationCandidate,
		arg.ZoneID,
		arg.RelationID,
		arg.BaseVersion,
		arg.ContentHash,
	)
	var i GetRelationCandidateRow
	err := row.Scan(&i.CandidateNumber, &i.Description)
	return i, err
}

const listClaimCandidates = `-- name: ListClaimCandidates :many
SELECT content_hash, candidate_number, description FROM knowledge_versions
WHERE zone_id = ?1 AND knowledge_kind = 'claim'
  AND knowledge_id = ?2 AND version = ?3
  AND candidate_number > 0 AND resolved_by_source_id IS NULL
ORDER BY candidate_number
`

type ListClaimCandidatesParams struct {
	ZoneID      string
	ClaimID     string
	BaseVersion int64
}

type ListClaimCandidatesRow struct {
	ContentHash     []byte
	CandidateNumber int64
	Description     string
}

func (q *Queries) ListClaimCandidates(ctx context.Context, arg ListClaimCandidatesParams) ([]ListClaimCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listClaimCandidates, arg.ZoneID, arg.ClaimID, arg.BaseVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClaimCandidatesRow{}
	for rows.Next() {
		var i ListClaimCandidatesRow
		if err := rows.Scan(&i.ContentHash, &i.CandidateNumber, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityCandidateAliases = `-- name: ListEntityCandidateAliases :many
SELECT a.alias FROM entity_version_aliases a
WHERE a.zone_id = ?1 AND a.entity_id = ?2
  AND a.version = ?3
  AND a.candidate_number = ?4
ORDER BY a.alias
`

type ListEntityCandidateAliasesParams struct {
	ZoneID          string
	EntityID        string
	BaseVersion     int64
	CandidateNumber int64
}

func (q *Queries) ListEntityCandidateAliases(ctx context.Context, arg ListEntityCandidateAliasesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEntityCandidateAliases,
		arg.ZoneID,
		arg.EntityID,
		arg.BaseVersion,
		arg.CandidateNumber,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var alias string
		if err := rows.Scan(&alias); err != nil {
			return nil, err
		}
		items = append(items, alias)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityCandidates = `-- name: ListEntityCandidates :many
SELECT content_hash, candidate_number, description FROM knowledge_versions
WHERE zone_id = ?1 AND knowledge_kind = 'entity'
  AND knowledge_id = ?2 AND version = ?3
  AND candidate_number > 0 AND resolved_by_source_id IS NULL
ORDER BY candidate_number
`

type ListEntityCandidatesParams struct {
	ZoneID      string
	EntityID    string
	BaseVersion int64
}

type ListEntityCandidatesRow struct {
	ContentHash     []byte
	CandidateNumber int64
	Description     string
}

func (q *Queries) ListEntityCandidates(ctx context.Context, arg ListEntityCandidatesParams) ([]ListEntityCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntityCandidates, arg.ZoneID, arg.EntityID, arg.BaseVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntityCandidatesRow{}
	for rows.Next() {
		var i ListEntityCandidatesRow
		if err := rows.Scan(&i.ContentHash, &i.CandidateNumber, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationCandidates = `-- name: ListRelationCandidates :many
SELECT content_hash, candidate_number, description FROM knowledge_versions
WHERE zone_id = ?1 AND knowledge_kind = 'relation'
  AND knowledge_id = ?2 AND version = ?3
  AND candidate_number > 0 AND resolved_by_source_id IS NULL
ORDER BY candidate_number
`

type ListRelationCandidatesParams struct {
	ZoneID      string
	RelationID  string
	BaseVersion int64
}

type ListRelationCandidatesRow struct {
	ContentHash     []byte
	CandidateNumber int64
	Description     string
}

func (q *Queries) ListRelationCandidates(ctx context.Context, arg ListRelationCandidatesParams) ([]ListRelationCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelationCandidates, arg.ZoneID, arg.RelationID, arg.BaseVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelationCandidatesRow{}
	for rows.Next() {
		var i ListRelationCandidatesRow
		if err := rows.Scan(&i.ContentHash, &i.CandidateNumber, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextClaimCandidateNumber = `-- name: NextClaimCandidateNumber :one
SELECT COALESCE(MAX(candidate_number), 0) + 1 FROM knowledge_versions
WHERE zone_id = ?1 AND knowledge_kind = 'claim'
  AND knowledge_id = ?2 AND version = ?3
`

type NextClaimCandidateNumberParams struct {
	ZoneID      string
	ClaimID     string
	BaseVersion int64
}

func (q *Queries) NextClaimCandidateNumber(ctx context.Context, arg NextClaimCandidateNumberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextClaimCandidateNumber, arg.ZoneID, arg.ClaimID, arg.BaseVersion)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const nextEntityCandidateNumber = `-- name: NextEntityCandidateNumber :one
SELECT COALESCE(MAX(candidate_number), 0) + 1 FROM knowledge_versions
WHERE zone_id = ?1 AND knowledge_kind = 'entity'
  AND knowledge_id = ?2 AND version = ?3
`

type NextEntityCandidateNumberParams struct {
	ZoneID      string
	EntityID    string
	BaseVersion int64
}

func (q *Queries) NextEntityCandidateNumber(ctx context.Context, arg NextEntityCandidateNumberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextEntityCandidateNumber, arg.ZoneID, arg.EntityID, arg.BaseVersion)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const nextRelationCandidateNumber = `-- name: NextRelationCandidateNumber :one
SELECT COALESCE(MAX(candidate_number), 0) + 1 FROM knowledge_versions
WHERE zone_id = ?1 AND knowledge_kind = 'relation'
  AND knowledge_id = ?2 AND version = ?3
`

type NextRelationCandidateNumberParams struct {
	ZoneID      string
	RelationID  string
	BaseVersion int64
}

func (q *Queries) NextRelationCandidateNumber(ctx context.Context, arg NextRelationCandidateNumberParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextRelationCandidateNumber, arg.ZoneID, arg.RelationID, arg.BaseVersion)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const resolveClaimCandidate = `-- name: ResolveClaimCandidate :execrows
UPDATE knowledge_versions SET resolved_by_source_id = ?1
WHERE zone_id = ?2 AND knowledge_kind = 'claim'
  AND knowledge_id = ?3 AND version = ?4
  AND candidate_number > 0 AND content_hash = ?5
  AND resolved_by_source_id IS NULL
`

type ResolveClaimCandidateParams struct {
	ResolutionSourceID sql.NullString
	ZoneID             string
	ClaimID            string
	BaseVersion        int64
	ContentHash        []byte
}

func (q *Queries) ResolveClaimCandidate(ctx context.Context, arg ResolveClaimCandidateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveClaimCandidate,
		arg.ResolutionSourceID,
		arg.ZoneID,
		arg.ClaimID,
		arg.BaseVersion,
		arg.ContentHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveEntityCandidate = `-- name: ResolveEntityCandidate :execrows
UPDATE knowledge_versions SET resolved_by_source_id = ?1
WHERE zone_id = ?2 AND knowledge_kind = 'entity'
  AND knowledge_id = ?3 AND version = ?4
  AND candidate_number > 0 AND content_hash = ?5
  AND resolved_by_source_id IS NULL
`

type ResolveEntityCandidateParams struct {
	ResolutionSourceID sql.NullString
	ZoneID             string
	EntityID           string
	BaseVersion        int64
	ContentHash        []byte
}

func (q *Queries) ResolveEntityCandidate(ctx context.Context, arg ResolveEntityCandidateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveEntityCandidate,
		arg.ResolutionSourceID,
		arg.ZoneID,
		arg.EntityID,
		arg.BaseVersion,
		arg.ContentHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveRelationCandidate = `-- name: ResolveRelationCandidate :execrows
UPDATE knowledge_versions SET resolved_by_source_id = ?1
WHERE zone_id = ?2 AND knowledge_kind = 'relation'
  AND knowledge_id = ?3 AND version = ?4
  AND candidate_number > 0 AND content_hash = ?5
  AND resolved_by_source_id IS NULL
`

type ResolveRelationCandidateParams struct {
	ResolutionSourceID sql.NullString
	ZoneID             string
	RelationID         string
	BaseVersion        int64
	ContentHash        []byte
}

func (q *Queries) ResolveRelationCandidate(ctx context.Context, arg ResolveRelationCandidateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveRelationCandidate,
		arg.ResolutionSourceID,
		arg.ZoneID,
		arg.RelationID,
		arg.BaseVersion,
		arg.ContentHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
