// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: extraction.sql

package db

import (
	"context"
)

const advanceKnowledgeExtractionProgress = `-- name: AdvanceKnowledgeExtractionProgress :execrows
UPDATE knowledge_extraction_progress
SET last_text_unit_id = ?1
WHERE zone_id = ?2 AND corpora_id = ?3
  AND last_text_unit_id = ?4
`

type AdvanceKnowledgeExtractionProgressParams struct {
	LastTextUnitID     string
	ZoneID             string
	CorporaID          string
	ExpectedTextUnitID string
}

func (q *Queries) AdvanceKnowledgeExtractionProgress(ctx context.Context, arg AdvanceKnowledgeExtractionProgressParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceKnowledgeExtractionProgress,
		arg.LastTextUnitID,
		arg.ZoneID,
		arg.CorporaID,
		arg.ExpectedTextUnitID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getKnowledgeExtractionProgress = `-- name: GetKnowledgeExtractionProgress :one
SELECT last_text_unit_id FROM knowledge_extraction_progress
WHERE zone_id = ?1 AND corpora_id = ?2
`

type GetKnowledgeExtractionProgressParams struct {
	ZoneID    string
	CorporaID string
}

func (q *Queries) GetKnowledgeExtractionProgress(ctx context.Context, arg GetKnowledgeExtractionProgressParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeExtractionProgress, arg.ZoneID, arg.CorporaID)
	var last_text_unit_id string
	err := row.Scan(&last_text_unit_id)
	return last_text_unit_id, err
}

const startKnowledgeExtractionProgress = `-- name: StartKnowledgeExtractionProgress :exec
INSERT INTO knowledge_extraction_progress (zone_id, corpora_id, last_text_unit_id)
VALUES (?1, ?2, ?3)
`

type StartKnowledgeExtractionProgressParams struct {
	ZoneID         string
	CorporaID      string
	LastTextUnitID string
}

func (q *Queries) StartKnowledgeExtractionProgress(ctx context.Context, arg StartKnowledgeExtractionProgressParams) error {
	_, err := q.db.ExecContext(ctx, startKnowledgeExtractionProgress, arg.ZoneID, arg.CorporaID, arg.LastTextUnitID)
	return err
}
