// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package db

import (
	"context"
)

const createClaimIdentity = `-- name: CreateClaimIdentity :exec
INSERT INTO claim_identities
    (zone_id, claim_id, subject_kind, subject_id, claim_type)
VALUES
    (?1, ?2, ?3,
     ?4, ?5)
`

type CreateClaimIdentityParams struct {
	ZoneID      string
	ClaimID     string
	SubjectKind string
	SubjectID   string
	ClaimType   string
}

func (q *Queries) CreateClaimIdentity(ctx context.Context, arg CreateClaimIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createClaimIdentity,
		arg.ZoneID,
		arg.ClaimID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.ClaimType,
	)
	return err
}

const createEntityIdentity = `-- name: CreateEntityIdentity :exec
INSERT INTO entity_identities (zone_id, entity_id, title, entity_type)
VALUES (?1, ?2, ?3, ?4)
`

type CreateEntityIdentityParams struct {
	ZoneID     string
	EntityID   string
	Title      string
	EntityType string
}

func (q *Queries) CreateEntityIdentity(ctx context.Context, arg CreateEntityIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createEntityIdentity,
		arg.ZoneID,
		arg.EntityID,
		arg.Title,
		arg.EntityType,
	)
	return err
}

const createRelationIdentity = `-- name: CreateRelationIdentity :exec
INSERT INTO relation_identities
    (zone_id, relation_id, source_entity_id, target_entity_id, relation_type)
VALUES
    (?1, ?2, ?3,
     ?4, ?5)
`

type CreateRelationIdentityParams struct {
	ZoneID         string
	RelationID     string
	SourceEntityID string
	TargetEntityID string
	RelationType   string
}

func (q *Queries) CreateRelationIdentity(ctx context.Context, arg CreateRelationIdentityParams) error {
	_, err := q.db.ExecContext(ctx, createRelationIdentity,
		arg.ZoneID,
		arg.RelationID,
		arg.SourceEntityID,
		arg.TargetEntityID,
		arg.RelationType,
	)
	return err
}

const getClaimID = `-- name: GetClaimID :one
SELECT claim_id FROM claim_identities
WHERE zone_id = ?1
  AND subject_kind = ?2
  AND subject_id = ?3
  AND claim_type = ?4
`

type GetClaimIDParams struct {
	ZoneID      string
	SubjectKind string
	SubjectID   string
	ClaimType   string
}

func (q *Queries) GetClaimID(ctx context.Context, arg GetClaimIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getClaimID,
		arg.ZoneID,
		arg.SubjectKind,
		arg.SubjectID,
		arg.ClaimType,
	)
	var claim_id string
	err := row.Scan(&claim_id)
	return claim_id, err
}

const getClaimIdentity = `-- name: GetClaimIdentity :one
SELECT subject_kind, subject_id, claim_type FROM claim_identities
WHERE zone_id = ?1 AND claim_id = ?2
`

type GetClaimIdentityParams struct {
	ZoneID  string
	ClaimID string
}

type GetClaimIdentityRow struct {
	SubjectKind string
	SubjectID   string
	ClaimType   string
}

func (q *Queries) GetClaimIdentity(ctx context.Context, arg GetClaimIdentityParams) (GetClaimIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getClaimIdentity, arg.ZoneID, arg.ClaimID)
	var i GetClaimIdentityRow
	err := row.Scan(&i.SubjectKind, &i.SubjectID, &i.ClaimType)
	return i, err
}

const getEntityID = `-- name: GetEntityID :one
SELECT entity_id FROM entity_identities
WHERE zone_id = ?1
  AND title = ?2
  AND entity_type = ?3
`

type GetEntityIDParams struct {
	ZoneID     string
	Title      string
	EntityType string
}

func (q *Queries) GetEntityID(ctx context.Context, arg GetEntityIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getEntityID, arg.ZoneID, arg.Title, arg.EntityType)
	var entity_id string
	err := row.Scan(&entity_id)
	return entity_id, err
}

const getEntityIdentity = `-- name: GetEntityIdentity :one
SELECT title, entity_type FROM entity_identities
WHERE zone_id = ?1 AND entity_id = ?2
`

type GetEntityIdentityParams struct {
	ZoneID   string
	EntityID string
}

type GetEntityIdentityRow struct {
	Title      string
	EntityType string
}

func (q *Queries) GetEntityIdentity(ctx context.Context, arg GetEntityIdentityParams) (GetEntityIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getEntityIdentity, arg.ZoneID, arg.EntityID)
	var i GetEntityIdentityRow
	err := row.Scan(&i.Title, &i.EntityType)
	return i, err
}

const getRelationID = `-- name: GetRelationID :one
SELECT relation_id FROM relation_identities
WHERE zone_id = ?1
  AND source_entity_id = ?2
  AND target_entity_id = ?3
  AND relation_type = ?4
`

type GetRelationIDParams struct {
	ZoneID         string
	SourceEntityID string
	TargetEntityID string
	RelationType   string
}

func (q *Queries) GetRelationID(ctx context.Context, arg GetRelationIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getRelationID,
		arg.ZoneID,
		arg.SourceEntityID,
		arg.TargetEntityID,
		arg.RelationType,
	)
	var relation_id string
	err := row.Scan(&relation_id)
	return relation_id, err
}

const getRelationIdentity = `-- name: GetRelationIdentity :one
SELECT source_entity_id, target_entity_id, relation_type FROM relation_identities
WHERE zone_id = ?1 AND relation_id = ?2
`

type GetRelationIdentityParams struct {
	ZoneID     string
	RelationID string
}

type GetRelationIdentityRow struct {
	SourceEntityID string
	TargetEntityID string
	RelationType   string
}

func (q *Queries) GetRelationIdentity(ctx context.Context, arg GetRelationIdentityParams) (GetRelationIdentityRow, error) {
	row := q.db.QueryRowContext(ctx, getRelationIdentity, arg.ZoneID, arg.RelationID)
	var i GetRelationIdentityRow
	err := row.Scan(&i.SourceEntityID, &i.TargetEntityID, &i.RelationType)
	return i, err
}

const hasEntityIdentity = `-- name: HasEntityIdentity :one
SELECT count(*) FROM entity_identities
WHERE zone_id = ?1 AND entity_id = ?2
`

type HasEntityIdentityParams struct {
	ZoneID   string
	EntityID string
}

func (q *Queries) HasEntityIdentity(ctx context.Context, arg HasEntityIdentityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasEntityIdentity, arg.ZoneID, arg.EntityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const hasRelationIdentity = `-- name: HasRelationIdentity :one
SELECT count(*) FROM relation_identities
WHERE zone_id = ?1 AND relation_id = ?2
`

type HasRelationIdentityParams struct {
	ZoneID     string
	RelationID string
}

func (q *Queries) HasRelationIdentity(ctx context.Context, arg HasRelationIdentityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasRelationIdentity, arg.ZoneID, arg.RelationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
