// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type ClaimIdentity struct {
	ZoneID      string
	ClaimID     string
	SubjectKind string
	SubjectID   string
	ClaimType   string
}

type EntityIdentity struct {
	ZoneID     string
	EntityID   string
	Title      string
	EntityType string
}

type EntityVersionAlias struct {
	ZoneID          string
	EntityID        string
	Version         int64
	CandidateNumber int64
	Alias           string
}

type KnowledgeEvidence struct {
	ZoneID       string
	SourceID     string
	EvidenceJson string
}

type KnowledgeExtractionProgress struct {
	ZoneID         string
	CorporaID      string
	LastTextUnitID string
}

type KnowledgeSchema struct {
	ID      int64
	Version int64
}

type KnowledgeSource struct {
	ZoneID     string
	SourceID   string
	SourceKind string
	ProducerID string
}

type KnowledgeSourceMetadatum struct {
	ZoneID          string
	SourceID        string
	KnowledgeKind   string
	KnowledgeID     string
	Version         int64
	CandidateNumber int64
	MetadataJson    string
}

type KnowledgeVersion struct {
	ZoneID             string
	KnowledgeKind      string
	KnowledgeID        string
	Version            int64
	CandidateNumber    int64
	Deleted            int64
	ContentHash        []byte
	Description        string
	CreatedBySourceID  string
	ResolvedBySourceID sql.NullString
}

type RelationIdentity struct {
	ZoneID         string
	RelationID     string
	SourceEntityID string
	TargetEntityID string
	RelationType   string
}

type ZoneKnowledgeConflict struct {
	ChildZoneID          string
	KnowledgeKind        string
	ChildKnowledgeID     string
	ChildBaseVersion     int64
	ChildCandidateNumber int64
	ParentZoneID         string
	ParentKnowledgeID    string
	ParentVersion        int64
	ResolvedBySourceID   sql.NullString
	ParentReconciled     int64
}
