// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provenance.sql

package db

import (
	"context"
)

const createKnowledgeSource = `-- name: CreateKnowledgeSource :exec
INSERT INTO knowledge_sources (zone_id, source_id, source_kind, producer_id)
VALUES
    (?1, ?2, ?3, ?4)
`

type CreateKnowledgeSourceParams struct {
	ZoneID     string
	SourceID   string
	SourceKind string
	ProducerID string
}

func (q *Queries) CreateKnowledgeSource(ctx context.Context, arg CreateKnowledgeSourceParams) error {
	_, err := q.db.ExecContext(ctx, createKnowledgeSource,
		arg.ZoneID,
		arg.SourceID,
		arg.SourceKind,
		arg.ProducerID,
	)
	return err
}

const getKnowledgeEvidence = `-- name: GetKnowledgeEvidence :one
SELECT evidence_json FROM knowledge_evidence
WHERE zone_id = ?1 AND source_id = ?2
`

type GetKnowledgeEvidenceParams struct {
	ZoneID   string
	SourceID string
}

func (q *Queries) GetKnowledgeEvidence(ctx context.Context, arg GetKnowledgeEvidenceParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeEvidence, arg.ZoneID, arg.SourceID)
	var evidence_json string
	err := row.Scan(&evidence_json)
	return evidence_json, err
}

const getKnowledgeSource = `-- name: GetKnowledgeSource :one
SELECT source_id, source_kind, producer_id FROM knowledge_sources
WHERE zone_id = ?1 AND source_id = ?2
`

type GetKnowledgeSourceParams struct {
	ZoneID   string
	SourceID string
}

type GetKnowledgeSourceRow struct {
	SourceID   string
	SourceKind string
	ProducerID string
}

func (q *Queries) GetKnowledgeSource(ctx context.Context, arg GetKnowledgeSourceParams) (GetKnowledgeSourceRow, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeSource, arg.ZoneID, arg.SourceID)
	var i GetKnowledgeSourceRow
	err := row.Scan(&i.SourceID, &i.SourceKind, &i.ProducerID)
	return i, err
}

const getKnowledgeSourceMetadata = `-- name: GetKnowledgeSourceMetadata :one
SELECT metadata_json FROM knowledge_source_metadata
WHERE zone_id = ?1 AND source_id = ?2
  AND knowledge_kind = ?3
  AND knowledge_id = ?4
  AND version = ?5
  AND candidate_number = ?6
`

type GetKnowledgeSourceMetadataParams struct {
	ZoneID          string
	SourceID        string
	KnowledgeKind   string
	KnowledgeID     string
	Version         int64
	CandidateNumber int64
}

func (q *Queries) GetKnowledgeSourceMetadata(ctx context.Context, arg GetKnowledgeSourceMetadataParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getKnowledgeSourceMetadata,
		arg.ZoneID,
		arg.SourceID,
		arg.KnowledgeKind,
		arg.KnowledgeID,
		arg.Version,
		arg.CandidateNumber,
	)
	var metadata_json string
	err := row.Scan(&metadata_json)
	return metadata_json, err
}

const listClaimCandidateSources = `-- name: ListClaimCandidateSources :many
SELECT m.source_id, m.metadata_json, v.created_by_source_id = m.source_id AS opened_candidate
FROM knowledge_source_metadata m
JOIN knowledge_versions v
  ON v.zone_id = m.zone_id AND v.knowledge_kind = m.knowledge_kind
 AND v.knowledge_id = m.knowledge_id AND v.version = m.version
 AND v.candidate_number = m.candidate_number
WHERE m.zone_id = ?1 AND m.knowledge_kind = 'claim'
  AND m.knowledge_id = ?2 AND m.version = ?3
  AND m.candidate_number > 0 AND v.content_hash = ?4
  AND v.resolved_by_source_id IS NULL
ORDER BY m.source_id
`

type ListClaimCandidateSourcesParams struct {
	ZoneID      string
	ClaimID     string
	BaseVersion int64
	ContentHash []byte
}

type ListClaimCandidateSourcesRow struct {
	SourceID        string
	MetadataJson    string
	OpenedCandidate bool
}

func (q *Queries) ListClaimCandidateSources(ctx context.Context, arg ListClaimCandidateSourcesParams) ([]ListClaimCandidateSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listClaimCandidateSources,
		arg.ZoneID,
		arg.ClaimID,
		arg.BaseVersion,
		arg.ContentHash,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClaimCandidateSourcesRow{}
	for rows.Next() {
		var i ListClaimCandidateSourcesRow
		if err := rows.Scan(&i.SourceID, &i.MetadataJson, &i.OpenedCandidate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimVersionSources = `-- name: ListClaimVersionSources :many
SELECT m.source_id, m.metadata_json FROM knowledge_source_metadata m
WHERE m.zone_id = ?1 AND m.knowledge_kind = 'claim'
  AND m.knowledge_id = ?2 AND m.version = ?3
  AND m.candidate_number = 0
UNION
SELECT candidate_source.source_id, candidate_source.metadata_json
FROM knowledge_versions formal
JOIN knowledge_versions candidate
  ON candidate.zone_id = formal.zone_id
 AND candidate.knowledge_kind = formal.knowledge_kind
 AND candidate.knowledge_id = formal.knowledge_id
 AND candidate.version = formal.version - 1
 AND candidate.candidate_number > 0
 AND candidate.content_hash = formal.content_hash
 AND candidate.resolved_by_source_id = formal.created_by_source_id
JOIN knowledge_source_metadata candidate_source
  ON candidate_source.zone_id = candidate.zone_id
 AND candidate_source.knowledge_kind = candidate.knowledge_kind
 AND candidate_source.knowledge_id = candidate.knowledge_id
 AND candidate_source.version = candidate.version
 AND candidate_source.candidate_number = candidate.candidate_number
WHERE formal.zone_id = ?1 AND formal.knowledge_kind = 'claim'
  AND formal.knowledge_id = ?2 AND formal.version = ?3
  AND formal.candidate_number = 0
ORDER BY source_id
`

type ListClaimVersionSourcesParams struct {
	ZoneID  string
	ClaimID string
	Version int64
}

type ListClaimVersionSourcesRow struct {
	SourceID     string
	MetadataJson string
}

func (q *Queries) ListClaimVersionSources(ctx context.Context, arg ListClaimVersionSourcesParams) ([]ListClaimVersionSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listClaimVersionSources, arg.ZoneID, arg.ClaimID, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClaimVersionSourcesRow{}
	for rows.Next() {
		var i ListClaimVersionSourcesRow
		if err := rows.Scan(&i.SourceID, &i.MetadataJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityCandidateSources = `-- name: ListEntityCandidateSources :many
SELECT m.source_id, m.metadata_json, v.created_by_source_id = m.source_id AS opened_candidate
FROM knowledge_source_metadata m
JOIN knowledge_versions v
  ON v.zone_id = m.zone_id AND v.knowledge_kind = m.knowledge_kind
 AND v.knowledge_id = m.knowledge_id AND v.version = m.version
 AND v.candidate_number = m.candidate_number
WHERE m.zone_id = ?1 AND m.knowledge_kind = 'entity'
  AND m.knowledge_id = ?2 AND m.version = ?3
  AND m.candidate_number > 0 AND v.content_hash = ?4
  AND v.resolved_by_source_id IS NULL
ORDER BY m.source_id
`

type ListEntityCandidateSourcesParams struct {
	ZoneID      string
	EntityID    string
	BaseVersion int64
	ContentHash []byte
}

type ListEntityCandidateSourcesRow struct {
	SourceID        string
	MetadataJson    string
	OpenedCandidate bool
}

func (q *Queries) ListEntityCandidateSources(ctx context.Context, arg ListEntityCandidateSourcesParams) ([]ListEntityCandidateSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntityCandidateSources,
		arg.ZoneID,
		arg.EntityID,
		arg.BaseVersion,
		arg.ContentHash,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntityCandidateSourcesRow{}
	for rows.Next() {
		var i ListEntityCandidateSourcesRow
		if err := rows.Scan(&i.SourceID, &i.MetadataJson, &i.OpenedCandidate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityVersionSources = `-- name: ListEntityVersionSources :many
SELECT m.source_id, m.metadata_json FROM knowledge_source_metadata m
WHERE m.zone_id = ?1 AND m.knowledge_kind = 'entity'
  AND m.knowledge_id = ?2 AND m.version = ?3
  AND m.candidate_number = 0
UNION
SELECT candidate_source.source_id, candidate_source.metadata_json
FROM knowledge_versions formal
JOIN knowledge_versions candidate
  ON candidate.zone_id = formal.zone_id
 AND candidate.knowledge_kind = formal.knowledge_kind
 AND candidate.knowledge_id = formal.knowledge_id
 AND candidate.version = formal.version - 1
 AND candidate.candidate_number > 0
 AND candidate.content_hash = formal.content_hash
 AND candidate.resolved_by_source_id = formal.created_by_source_id
JOIN knowledge_source_metadata candidate_source
  ON candidate_source.zone_id = candidate.zone_id
 AND candidate_source.knowledge_kind = candidate.knowledge_kind
 AND candidate_source.knowledge_id = candidate.knowledge_id
 AND candidate_source.version = candidate.version
 AND candidate_source.candidate_number = candidate.candidate_number
WHERE formal.zone_id = ?1 AND formal.knowledge_kind = 'entity'
  AND formal.knowledge_id = ?2 AND formal.version = ?3
  AND formal.candidate_number = 0
ORDER BY source_id
`

type ListEntityVersionSourcesParams struct {
	ZoneID   string
	EntityID string
	Version  int64
}

type ListEntityVersionSourcesRow struct {
	SourceID     string
	MetadataJson string
}

func (q *Queries) ListEntityVersionSources(ctx context.Context, arg ListEntityVersionSourcesParams) ([]ListEntityVersionSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntityVersionSources, arg.ZoneID, arg.EntityID, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntityVersionSourcesRow{}
	for rows.Next() {
		var i ListEntityVersionSourcesRow
		if err := rows.Scan(&i.SourceID, &i.MetadataJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationCandidateSources = `-- name: ListRelationCandidateSources :many
SELECT m.source_id, m.metadata_json, v.created_by_source_id = m.source_id AS opened_candidate
FROM knowledge_source_metadata m
JOIN knowledge_versions v
  ON v.zone_id = m.zone_id AND v.knowledge_kind = m.knowledge_kind
 AND v.knowledge_id = m.knowledge_id AND v.version = m.version
 AND v.candidate_number = m.candidate_number
WHERE m.zone_id = ?1 AND m.knowledge_kind = 'relation'
  AND m.knowledge_id = ?2 AND m.version = ?3
  AND m.candidate_number > 0 AND v.content_hash = ?4
  AND v.resolved_by_source_id IS NULL
ORDER BY m.source_id
`

type ListRelationCandidateSourcesParams struct {
	ZoneID      string
	RelationID  string
	BaseVersion int64
	ContentHash []byte
}

type ListRelationCandidateSourcesRow struct {
	SourceID        string
	MetadataJson    string
	OpenedCandidate bool
}

func (q *Queries) ListRelationCandidateSources(ctx context.Context, arg ListRelationCandidateSourcesParams) ([]ListRelationCandidateSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelationCandidateSources,
		arg.ZoneID,
		arg.RelationID,
		arg.BaseVersion,
		arg.ContentHash,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelationCandidateSourcesRow{}
	for rows.Next() {
		var i ListRelationCandidateSourcesRow
		if err := rows.Scan(&i.SourceID, &i.MetadataJson, &i.OpenedCandidate); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationVersionSources = `-- name: ListRelationVersionSources :many
SELECT m.source_id, m.metadata_json FROM knowledge_source_metadata m
WHERE m.zone_id = ?1 AND m.knowledge_kind = 'relation'
  AND m.knowledge_id = ?2 AND m.version = ?3
  AND m.candidate_number = 0
UNION
SELECT candidate_source.source_id, candidate_source.metadata_json
FROM knowledge_versions formal
JOIN knowledge_versions candidate
  ON candidate.zone_id = formal.zone_id
 AND candidate.knowledge_kind = formal.knowledge_kind
 AND candidate.knowledge_id = formal.knowledge_id
 AND candidate.version = formal.version - 1
 AND candidate.candidate_number > 0
 AND candidate.content_hash = formal.content_hash
 AND candidate.resolved_by_source_id = formal.created_by_source_id
JOIN knowledge_source_metadata candidate_source
  ON candidate_source.zone_id = candidate.zone_id
 AND candidate_source.knowledge_kind = candidate.knowledge_kind
 AND candidate_source.knowledge_id = candidate.knowledge_id
 AND candidate_source.version = candidate.version
 AND candidate_source.candidate_number = candidate.candidate_number
WHERE formal.zone_id = ?1 AND formal.knowledge_kind = 'relation'
  AND formal.knowledge_id = ?2 AND formal.version = ?3
  AND formal.candidate_number = 0
ORDER BY source_id
`

type ListRelationVersionSourcesParams struct {
	ZoneID     string
	RelationID string
	Version    int64
}

type ListRelationVersionSourcesRow struct {
	SourceID     string
	MetadataJson string
}

func (q *Queries) ListRelationVersionSources(ctx context.Context, arg ListRelationVersionSourcesParams) ([]ListRelationVersionSourcesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelationVersionSources, arg.ZoneID, arg.RelationID, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelationVersionSourcesRow{}
	for rows.Next() {
		var i ListRelationVersionSourcesRow
		if err := rows.Scan(&i.SourceID, &i.MetadataJson); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceClaimCandidates = `-- name: ListSourceClaimCandidates :many
SELECT m.knowledge_id AS claim_id, m.version AS base_version, v.content_hash,
       v.created_by_source_id = m.source_id AS opened_candidate
FROM knowledge_source_metadata m
JOIN knowledge_versions v
  ON v.zone_id = m.zone_id AND v.knowledge_kind = m.knowledge_kind
 AND v.knowledge_id = m.knowledge_id AND v.version = m.version
 AND v.candidate_number = m.candidate_number
WHERE m.zone_id = ?1 AND m.knowledge_kind = 'claim'
  AND m.source_id = ?2 AND m.candidate_number > 0
ORDER BY m.knowledge_id, m.version, v.content_hash
`

type ListSourceClaimCandidatesParams struct {
	ZoneID   string
	SourceID string
}

type ListSourceClaimCandidatesRow struct {
	ClaimID         string
	BaseVersion     int64
	ContentHash     []byte
	OpenedCandidate bool
}

func (q *Queries) ListSourceClaimCandidates(ctx context.Context, arg ListSourceClaimCandidatesParams) ([]ListSourceClaimCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceClaimCandidates, arg.ZoneID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceClaimCandidatesRow{}
	for rows.Next() {
		var i ListSourceClaimCandidatesRow
		if err := rows.Scan(
			&i.ClaimID,
			&i.BaseVersion,
			&i.ContentHash,
			&i.OpenedCandidate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceClaimVersions = `-- name: ListSourceClaimVersions :many
SELECT m.knowledge_id AS claim_id, m.version,
       v.created_by_source_id = m.source_id AS created_version
FROM knowledge_source_metadata m
JOIN knowledge_versions v
  ON v.zone_id = m.zone_id AND v.knowledge_kind = m.knowledge_kind
 AND v.knowledge_id = m.knowledge_id AND v.version = m.version
 AND v.candidate_number = m.candidate_number
WHERE m.zone_id = ?1 AND m.knowledge_kind = 'claim'
  AND m.source_id = ?2 AND m.candidate_number = 0
ORDER BY m.knowledge_id, m.version
`

type ListSourceClaimVersionsParams struct {
	ZoneID   string
	SourceID string
}

type ListSourceClaimVersionsRow struct {
	ClaimID        string
	Version        int64
	CreatedVersion bool
}

func (q *Queries) ListSourceClaimVersions(ctx context.Context, arg ListSourceClaimVersionsParams) ([]ListSourceClaimVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceClaimVersions, arg.ZoneID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceClaimVersionsRow{}
	for rows.Next() {
		var i ListSourceClaimVersionsRow
		if err := rows.Scan(&i.ClaimID, &i.Version, &i.CreatedVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceEntityCandidates = `-- name: ListSourceEntityCandidates :many
SELECT m.knowledge_id AS entity_id, m.version AS base_version, v.content_hash,
       v.created_by_source_id = m.source_id AS opened_candidate
FROM knowledge_source_metadata m
JOIN knowledge_versions v
  ON v.zone_id = m.zone_id AND v.knowledge_kind = m.knowledge_kind
 AND v.knowledge_id = m.knowledge_id AND v.version = m.version
 AND v.candidate_number = m.candidate_number
WHERE m.zone_id = ?1 AND m.knowledge_kind = 'entity'
  AND m.source_id = ?2 AND m.candidate_number > 0
ORDER BY m.knowledge_id, m.version, v.content_hash
`

type ListSourceEntityCandidatesParams struct {
	ZoneID   string
	SourceID string
}

type ListSourceEntityCandidatesRow struct {
	EntityID        string
	BaseVersion     int64
	ContentHash     []byte
	OpenedCandidate bool
}

func (q *Queries) ListSourceEntityCandidates(ctx context.Context, arg ListSourceEntityCandidatesParams) ([]ListSourceEntityCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceEntityCandidates, arg.ZoneID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceEntityCandidatesRow{}
	for rows.Next() {
		var i ListSourceEntityCandidatesRow
		if err := rows.Scan(
			&i.EntityID,
			&i.BaseVersion,
			&i.ContentHash,
			&i.OpenedCandidate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceEntityVersions = `-- name: ListSourceEntityVersions :many
SELECT m.knowledge_id AS entity_id, m.version,
       v.created_by_source_id = m.source_id AS created_version
FROM knowledge_source_metadata m
JOIN knowledge_versions v
  ON v.zone_id = m.zone_id AND v.knowledge_kind = m.knowledge_kind
 AND v.knowledge_id = m.knowledge_id AND v.version = m.version
 AND v.candidate_number = m.candidate_number
WHERE m.zone_id = ?1 AND m.knowledge_kind = 'entity'
  AND m.source_id = ?2 AND m.candidate_number = 0
ORDER BY m.knowledge_id, m.version
`

type ListSourceEntityVersionsParams struct {
	ZoneID   string
	SourceID string
}

type ListSourceEntityVersionsRow struct {
	EntityID       string
	Version        int64
	CreatedVersion bool
}

func (q *Queries) ListSourceEntityVersions(ctx context.Context, arg ListSourceEntityVersionsParams) ([]ListSourceEntityVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceEntityVersions, arg.ZoneID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceEntityVersionsRow{}
	for rows.Next() {
		var i ListSourceEntityVersionsRow
		if err := rows.Scan(&i.EntityID, &i.Version, &i.CreatedVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceRelationCandidates = `-- name: ListSourceRelationCandidates :many
SELECT m.knowledge_id AS relation_id, m.version AS base_version, v.content_hash,
       v.created_by_source_id = m.source_id AS opened_candidate
FROM knowledge_source_metadata m
JOIN knowledge_versions v
  ON v.zone_id = m.zone_id AND v.knowledge_kind = m.knowledge_kind
 AND v.knowledge_id = m.knowledge_id AND v.version = m.version
 AND v.candidate_number = m.candidate_number
WHERE m.zone_id = ?1 AND m.knowledge_kind = 'relation'
  AND m.source_id = ?2 AND m.candidate_number > 0
ORDER BY m.knowledge_id, m.version, v.content_hash
`

type ListSourceRelationCandidatesParams struct {
	ZoneID   string
	SourceID string
}

type ListSourceRelationCandidatesRow struct {
	RelationID      string
	BaseVersion     int64
	ContentHash     []byte
	OpenedCandidate bool
}

func (q *Queries) ListSourceRelationCandidates(ctx context.Context, arg ListSourceRelationCandidatesParams) ([]ListSourceRelationCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceRelationCandidates, arg.ZoneID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceRelationCandidatesRow{}
	for rows.Next() {
		var i ListSourceRelationCandidatesRow
		if err := rows.Scan(
			&i.RelationID,
			&i.BaseVersion,
			&i.ContentHash,
			&i.OpenedCandidate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceRelationVersions = `-- name: ListSourceRelationVersions :many
SELECT m.knowledge_id AS relation_id, m.version,
       v.created_by_source_id = m.source_id AS created_version
FROM knowledge_source_metadata m
JOIN knowledge_versions v
  ON v.zone_id = m.zone_id AND v.knowledge_kind = m.knowledge_kind
 AND v.knowledge_id = m.knowledge_id AND v.version = m.version
 AND v.candidate_number = m.candidate_number
WHERE m.zone_id = ?1 AND m.knowledge_kind = 'relation'
  AND m.source_id = ?2 AND m.candidate_number = 0
ORDER BY m.knowledge_id, m.version
`

type ListSourceRelationVersionsParams struct {
	ZoneID   string
	SourceID string
}

type ListSourceRelationVersionsRow struct {
	RelationID     string
	Version        int64
	CreatedVersion bool
}

func (q *Queries) ListSourceRelationVersions(ctx context.Context, arg ListSourceRelationVersionsParams) ([]ListSourceRelationVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSourceRelationVersions, arg.ZoneID, arg.SourceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSourceRelationVersionsRow{}
	for rows.Next() {
		var i ListSourceRelationVersionsRow
		if err := rows.Scan(&i.RelationID, &i.Version, &i.CreatedVersion); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveKnowledgeEvidence = `-- name: SaveKnowledgeEvidence :exec
INSERT INTO knowledge_evidence (zone_id, source_id, evidence_json)
VALUES (?1, ?2, ?3)
`

type SaveKnowledgeEvidenceParams struct {
	ZoneID       string
	SourceID     string
	EvidenceJson string
}

func (q *Queries) SaveKnowledgeEvidence(ctx context.Context, arg SaveKnowledgeEvidenceParams) error {
	_, err := q.db.ExecContext(ctx, saveKnowledgeEvidence, arg.ZoneID, arg.SourceID, arg.EvidenceJson)
	return err
}

const saveKnowledgeSourceMetadata = `-- name: SaveKnowledgeSourceMetadata :exec
INSERT INTO knowledge_source_metadata
    (zone_id, source_id, knowledge_kind, knowledge_id, version,
     candidate_number, metadata_json)
VALUES
    (?1, ?2, ?3,
     ?4, ?5, ?6,
     ?7)
`

type SaveKnowledgeSourceMetadataParams struct {
	ZoneID          string
	SourceID        string
	KnowledgeKind   string
	KnowledgeID     string
	Version         int64
	CandidateNumber int64
	MetadataJson    string
}

func (q *Queries) SaveKnowledgeSourceMetadata(ctx context.Context, arg SaveKnowledgeSourceMetadataParams) error {
	_, err := q.db.ExecContext(ctx, saveKnowledgeSourceMetadata,
		arg.ZoneID,
		arg.SourceID,
		arg.KnowledgeKind,
		arg.KnowledgeID,
		arg.Version,
		arg.CandidateNumber,
		arg.MetadataJson,
	)
	return err
}
