// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AdvanceKnowledgeExtractionProgress(ctx context.Context, arg AdvanceKnowledgeExtractionProgressParams) (int64, error)
	BrowsePendingClaimIDs(ctx context.Context, arg BrowsePendingClaimIDsParams) ([]string, error)
	BrowsePendingEntityIDs(ctx context.Context, arg BrowsePendingEntityIDsParams) ([]string, error)
	BrowsePendingRelationIDs(ctx context.Context, arg BrowsePendingRelationIDsParams) ([]string, error)
	CountActiveEntity(ctx context.Context, arg CountActiveEntityParams) (int64, error)
	CountActiveRelation(ctx context.Context, arg CountActiveRelationParams) (int64, error)
	CreateClaimCandidate(ctx context.Context, arg CreateClaimCandidateParams) error
	CreateClaimIdentity(ctx context.Context, arg CreateClaimIdentityParams) error
	CreateClaimVersion(ctx context.Context, arg CreateClaimVersionParams) error
	CreateEntityAlias(ctx context.Context, arg CreateEntityAliasParams) error
	CreateEntityCandidate(ctx context.Context, arg CreateEntityCandidateParams) error
	CreateEntityCandidateAlias(ctx context.Context, arg CreateEntityCandidateAliasParams) error
	CreateEntityIdentity(ctx context.Context, arg CreateEntityIdentityParams) error
	CreateEntityVersion(ctx context.Context, arg CreateEntityVersionParams) error
	CreateKnowledgeSource(ctx context.Context, arg CreateKnowledgeSourceParams) error
	CreateRelationCandidate(ctx context.Context, arg CreateRelationCandidateParams) error
	CreateRelationIdentity(ctx context.Context, arg CreateRelationIdentityParams) error
	CreateRelationVersion(ctx context.Context, arg CreateRelationVersionParams) error
	CurrentClaimVersion(ctx context.Context, arg CurrentClaimVersionParams) (interface{}, error)
	CurrentEntityVersion(ctx context.Context, arg CurrentEntityVersionParams) (interface{}, error)
	CurrentRelationVersion(ctx context.Context, arg CurrentRelationVersionParams) (interface{}, error)
	FindEntities(ctx context.Context, arg FindEntitiesParams) ([]FindEntitiesRow, error)
	GetClaimCandidate(ctx context.Context, arg GetClaimCandidateParams) (GetClaimCandidateRow, error)
	GetClaimID(ctx context.Context, arg GetClaimIDParams) (string, error)
	GetClaimIdentity(ctx context.Context, arg GetClaimIdentityParams) (GetClaimIdentityRow, error)
	GetClaimVersion(ctx context.Context, arg GetClaimVersionParams) (GetClaimVersionRow, error)
	GetCurrentClaim(ctx context.Context, arg GetCurrentClaimParams) (GetCurrentClaimRow, error)
	GetCurrentEntity(ctx context.Context, arg GetCurrentEntityParams) (GetCurrentEntityRow, error)
	GetCurrentRelation(ctx context.Context, arg GetCurrentRelationParams) (GetCurrentRelationRow, error)
	GetEntityCandidate(ctx context.Context, arg GetEntityCandidateParams) (GetEntityCandidateRow, error)
	GetEntityID(ctx context.Context, arg GetEntityIDParams) (string, error)
	GetEntityIdentity(ctx context.Context, arg GetEntityIdentityParams) (GetEntityIdentityRow, error)
	GetEntityVersion(ctx context.Context, arg GetEntityVersionParams) (GetEntityVersionRow, error)
	GetKnowledgeEvidence(ctx context.Context, arg GetKnowledgeEvidenceParams) (string, error)
	GetKnowledgeExtractionProgress(ctx context.Context, arg GetKnowledgeExtractionProgressParams) (string, error)
	GetKnowledgeSource(ctx context.Context, arg GetKnowledgeSourceParams) (GetKnowledgeSourceRow, error)
	GetKnowledgeSourceMetadata(ctx context.Context, arg GetKnowledgeSourceMetadataParams) (string, error)
	GetRelationCandidate(ctx context.Context, arg GetRelationCandidateParams) (GetRelationCandidateRow, error)
	GetRelationID(ctx context.Context, arg GetRelationIDParams) (string, error)
	GetRelationIdentity(ctx context.Context, arg GetRelationIdentityParams) (GetRelationIdentityRow, error)
	GetRelationVersion(ctx context.Context, arg GetRelationVersionParams) (GetRelationVersionRow, error)
	GetResolvedZoneClaimConflict(ctx context.Context, arg GetResolvedZoneClaimConflictParams) (GetResolvedZoneClaimConflictRow, error)
	GetResolvedZoneEntityConflict(ctx context.Context, arg GetResolvedZoneEntityConflictParams) (GetResolvedZoneEntityConflictRow, error)
	GetResolvedZoneRelationConflict(ctx context.Context, arg GetResolvedZoneRelationConflictParams) (GetResolvedZoneRelationConflictRow, error)
	GetZoneClaimConflict(ctx context.Context, arg GetZoneClaimConflictParams) (GetZoneClaimConflictRow, error)
	GetZoneEntityConflict(ctx context.Context, arg GetZoneEntityConflictParams) (GetZoneEntityConflictRow, error)
	GetZoneRelationConflict(ctx context.Context, arg GetZoneRelationConflictParams) (GetZoneRelationConflictRow, error)
	HasEntityIdentity(ctx context.Context, arg HasEntityIdentityParams) (int64, error)
	HasRelationIdentity(ctx context.Context, arg HasRelationIdentityParams) (int64, error)
	ListActiveClaimReferences(ctx context.Context, arg ListActiveClaimReferencesParams) ([]ListActiveClaimReferencesRow, error)
	ListActiveClaims(ctx context.Context, arg ListActiveClaimsParams) ([]string, error)
	ListActiveEntityReferences(ctx context.Context, arg ListActiveEntityReferencesParams) ([]ListActiveEntityReferencesRow, error)
	ListActiveRelationReferences(ctx context.Context, arg ListActiveRelationReferencesParams) ([]ListActiveRelationReferencesRow, error)
	ListActiveRelations(ctx context.Context, arg ListActiveRelationsParams) ([]string, error)
	ListClaimCandidateSources(ctx context.Context, arg ListClaimCandidateSourcesParams) ([]ListClaimCandidateSourcesRow, error)
	ListClaimCandidates(ctx context.Context, arg ListClaimCandidatesParams) ([]ListClaimCandidatesRow, error)
	ListClaimHistory(ctx context.Context, arg ListClaimHistoryParams) ([]ListClaimHistoryRow, error)
	ListClaimVersionSources(ctx context.Context, arg ListClaimVersionSourcesParams) ([]ListClaimVersionSourcesRow, error)
	ListCurrentClaims(ctx context.Context, arg ListCurrentClaimsParams) ([]ListCurrentClaimsRow, error)
	ListCurrentEntities(ctx context.Context, arg ListCurrentEntitiesParams) ([]ListCurrentEntitiesRow, error)
	ListCurrentRelations(ctx context.Context, arg ListCurrentRelationsParams) ([]ListCurrentRelationsRow, error)
	ListEntityAliases(ctx context.Context, arg ListEntityAliasesParams) ([]string, error)
	ListEntityCandidateAliases(ctx context.Context, arg ListEntityCandidateAliasesParams) ([]string, error)
	ListEntityCandidateSources(ctx context.Context, arg ListEntityCandidateSourcesParams) ([]ListEntityCandidateSourcesRow, error)
	ListEntityCandidates(ctx context.Context, arg ListEntityCandidatesParams) ([]ListEntityCandidatesRow, error)
	ListEntityHistory(ctx context.Context, arg ListEntityHistoryParams) ([]ListEntityHistoryRow, error)
	ListEntityVersionSources(ctx context.Context, arg ListEntityVersionSourcesParams) ([]ListEntityVersionSourcesRow, error)
	ListRelationCandidateSources(ctx context.Context, arg ListRelationCandidateSourcesParams) ([]ListRelationCandidateSourcesRow, error)
	ListRelationCandidates(ctx context.Context, arg ListRelationCandidatesParams) ([]ListRelationCandidatesRow, error)
	ListRelationHistory(ctx context.Context, arg ListRelationHistoryParams) ([]ListRelationHistoryRow, error)
	ListRelationVersionSources(ctx context.Context, arg ListRelationVersionSourcesParams) ([]ListRelationVersionSourcesRow, error)
	ListSourceClaimCandidates(ctx context.Context, arg ListSourceClaimCandidatesParams) ([]ListSourceClaimCandidatesRow, error)
	ListSourceClaimVersions(ctx context.Context, arg ListSourceClaimVersionsParams) ([]ListSourceClaimVersionsRow, error)
	ListSourceEntityCandidates(ctx context.Context, arg ListSourceEntityCandidatesParams) ([]ListSourceEntityCandidatesRow, error)
	ListSourceEntityVersions(ctx context.Context, arg ListSourceEntityVersionsParams) ([]ListSourceEntityVersionsRow, error)
	ListSourceRelationCandidates(ctx context.Context, arg ListSourceRelationCandidatesParams) ([]ListSourceRelationCandidatesRow, error)
	ListSourceRelationVersions(ctx context.Context, arg ListSourceRelationVersionsParams) ([]ListSourceRelationVersionsRow, error)
	NextClaimCandidateNumber(ctx context.Context, arg NextClaimCandidateNumberParams) (int64, error)
	NextEntityCandidateNumber(ctx context.Context, arg NextEntityCandidateNumberParams) (int64, error)
	NextRelationCandidateNumber(ctx context.Context, arg NextRelationCandidateNumberParams) (int64, error)
	ReconcileZoneClaimConflict(ctx context.Context, arg ReconcileZoneClaimConflictParams) (int64, error)
	ReconcileZoneEntityConflict(ctx context.Context, arg ReconcileZoneEntityConflictParams) (int64, error)
	ReconcileZoneRelationConflict(ctx context.Context, arg ReconcileZoneRelationConflictParams) (int64, error)
	ResolveClaimCandidate(ctx context.Context, arg ResolveClaimCandidateParams) (int64, error)
	ResolveEntityCandidate(ctx context.Context, arg ResolveEntityCandidateParams) (int64, error)
	ResolveRelationCandidate(ctx context.Context, arg ResolveRelationCandidateParams) (int64, error)
	ResolveZoneClaimConflict(ctx context.Context, arg ResolveZoneClaimConflictParams) (int64, error)
	ResolveZoneEntityConflict(ctx context.Context, arg ResolveZoneEntityConflictParams) (int64, error)
	ResolveZoneRelationConflict(ctx context.Context, arg ResolveZoneRelationConflictParams) (int64, error)
	SaveKnowledgeEvidence(ctx context.Context, arg SaveKnowledgeEvidenceParams) error
	SaveKnowledgeSourceMetadata(ctx context.Context, arg SaveKnowledgeSourceMetadataParams) error
	SaveZoneClaimConflict(ctx context.Context, arg SaveZoneClaimConflictParams) error
	SaveZoneEntityConflict(ctx context.Context, arg SaveZoneEntityConflictParams) error
	SaveZoneRelationConflict(ctx context.Context, arg SaveZoneRelationConflictParams) error
	StartKnowledgeExtractionProgress(ctx context.Context, arg StartKnowledgeExtractionProgressParams) error
}

var _ Querier = (*Queries)(nil)
