// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: versions.sql

package db

import (
	"context"
)

const countActiveEntity = `-- name: CountActiveEntity :one
SELECT count(*) FROM knowledge_versions v
WHERE v.zone_id = ?1 AND v.knowledge_kind = 'entity'
  AND v.knowledge_id = ?2
  AND v.candidate_number = 0 AND v.deleted = 0
  AND v.version = (
      SELECT MAX(current.version) FROM knowledge_versions current
      WHERE current.zone_id = v.zone_id
        AND current.knowledge_kind = v.knowledge_kind
        AND current.knowledge_id = v.knowledge_id
        AND current.candidate_number = 0
  )
`

type CountActiveEntityParams struct {
	ZoneID   string
	EntityID string
}

func (q *Queries) CountActiveEntity(ctx context.Context, arg CountActiveEntityParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveEntity, arg.ZoneID, arg.EntityID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveRelation = `-- name: CountActiveRelation :one
SELECT count(*) FROM knowledge_versions v
WHERE v.zone_id = ?1 AND v.knowledge_kind = 'relation'
  AND v.knowledge_id = ?2
  AND v.candidate_number = 0 AND v.deleted = 0
  AND v.version = (
      SELECT MAX(current.version) FROM knowledge_versions current
      WHERE current.zone_id = v.zone_id
        AND current.knowledge_kind = v.knowledge_kind
        AND current.knowledge_id = v.knowledge_id
        AND current.candidate_number = 0
  )
`

type CountActiveRelationParams struct {
	ZoneID     string
	RelationID string
}

func (q *Queries) CountActiveRelation(ctx context.Context, arg CountActiveRelationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveRelation, arg.ZoneID, arg.RelationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClaimVersion = `-- name: CreateClaimVersion :exec
INSERT INTO knowledge_versions
    (zone_id, knowledge_kind, knowledge_id, version, candidate_number,
     deleted, content_hash, description, created_by_source_id)
VALUES
    (?1, 'claim', ?2, ?3, 0,
     ?4, ?5, ?6,
     ?7)
`

type CreateClaimVersionParams struct {
	ZoneID            string
	ClaimID           string
	Version           int64
	Deleted           int64
	ContentHash       []byte
	Description       string
	CreatedBySourceID string
}

func (q *Queries) CreateClaimVersion(ctx context.Context, arg CreateClaimVersionParams) error {
	_, err := q.db.ExecContext(ctx, createClaimVersion,
		arg.ZoneID,
		arg.ClaimID,
		arg.Version,
		arg.Deleted,
		arg.ContentHash,
		arg.Description,
		arg.CreatedBySourceID,
	)
	return err
}

const createEntityAlias = `-- name: CreateEntityAlias :exec
INSERT INTO entity_version_aliases
    (zone_id, entity_id, version, candidate_number, alias)
VALUES
    (?1, ?2, ?3, 0, ?4)
`

type CreateEntityAliasParams struct {
	ZoneID   string
	EntityID string
	Version  int64
	Alias    string
}

func (q *Queries) CreateEntityAlias(ctx context.Context, arg CreateEntityAliasParams) error {
	_, err := q.db.ExecContext(ctx, createEntityAlias,
		arg.ZoneID,
		arg.EntityID,
		arg.Version,
		arg.Alias,
	)
	return err
}

const createEntityVersion = `-- name: CreateEntityVersion :exec
INSERT INTO knowledge_versions
    (zone_id, knowledge_kind, knowledge_id, version, candidate_number,
     deleted, content_hash, description, created_by_source_id)
VALUES
    (?1, 'entity', ?2, ?3, 0,
     ?4, ?5, ?6,
     ?7)
`

type CreateEntityVersionParams struct {
	ZoneID            string
	EntityID          string
	Version           int64
	Deleted           int64
	ContentHash       []byte
	Description       string
	CreatedBySourceID string
}

func (q *Queries) CreateEntityVersion(ctx context.Context, arg CreateEntityVersionParams) error {
	_, err := q.db.ExecContext(ctx, createEntityVersion,
		arg.ZoneID,
		arg.EntityID,
		arg.Version,
		arg.Deleted,
		arg.ContentHash,
		arg.Description,
		arg.CreatedBySourceID,
	)
	return err
}

const createRelationVersion = `-- name: CreateRelationVersion :exec
INSERT INTO knowledge_versions
    (zone_id, knowledge_kind, knowledge_id, version, candidate_number,
     deleted, content_hash, description, created_by_source_id)
VALUES
    (?1, 'relation', ?2, ?3, 0,
     ?4, ?5, ?6,
     ?7)
`

type CreateRelationVersionParams struct {
	ZoneID            string
	RelationID        string
	Version           int64
	Deleted           int64
	ContentHash       []byte
	Description       string
	CreatedBySourceID string
}

func (q *Queries) CreateRelationVersion(ctx context.Context, arg CreateRelationVersionParams) error {
	_, err := q.db.ExecContext(ctx, createRelationVersion,
		arg.ZoneID,
		arg.RelationID,
		arg.Version,
		arg.Deleted,
		arg.ContentHash,
		arg.Description,
		arg.CreatedBySourceID,
	)
	return err
}

const currentClaimVersion = `-- name: CurrentClaimVersion :one
SELECT MAX(version) FROM knowledge_versions
WHERE zone_id = ?1 AND knowledge_kind = 'claim'
  AND knowledge_id = ?2 AND candidate_number = 0
`

type CurrentClaimVersionParams struct {
	ZoneID  string
	ClaimID string
}

func (q *Queries) CurrentClaimVersion(ctx context.Context, arg CurrentClaimVersionParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, currentClaimVersion, arg.ZoneID, arg.ClaimID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const currentEntityVersion = `-- name: CurrentEntityVersion :one
SELECT MAX(version) FROM knowledge_versions
WHERE zone_id = ?1 AND knowledge_kind = 'entity'
  AND knowledge_id = ?2 AND candidate_number = 0
`

type CurrentEntityVersionParams struct {
	ZoneID   string
	EntityID string
}

func (q *Queries) CurrentEntityVersion(ctx context.Context, arg CurrentEntityVersionParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, currentEntityVersion, arg.ZoneID, arg.EntityID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const currentRelationVersion = `-- name: CurrentRelationVersion :one
SELECT MAX(version) FROM knowledge_versions
WHERE zone_id = ?1 AND knowledge_kind = 'relation'
  AND knowledge_id = ?2 AND candidate_number = 0
`

type CurrentRelationVersionParams struct {
	ZoneID     string
	RelationID string
}

func (q *Queries) CurrentRelationVersion(ctx context.Context, arg CurrentRelationVersionParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, currentRelationVersion, arg.ZoneID, arg.RelationID)
	var max interface{}
	err := row.Scan(&max)
	return max, err
}

const findEntities = `-- name: FindEntities :many
SELECT i.entity_id, v.version
FROM entity_identities i
JOIN knowledge_versions v
  ON v.zone_id = i.zone_id AND v.knowledge_kind = 'entity'
 AND v.knowledge_id = i.entity_id
WHERE i.zone_id = ?1
  AND i.title = ?2
  AND (CAST(?3 AS TEXT) = '' OR i.entity_type = CAST(?3 AS TEXT))
  AND v.candidate_number = 0
  AND v.deleted = 0
  AND v.version = (
      SELECT MAX(current.version) FROM knowledge_versions current
      WHERE current.zone_id = v.zone_id
        AND current.knowledge_kind = v.knowledge_kind
        AND current.knowledge_id = v.knowledge_id
        AND current.candidate_number = 0
  )
ORDER BY i.entity_type, i.entity_id
LIMIT ?4
`

type FindEntitiesParams struct {
	ZoneID     string
	Title      string
	EntityType string
	PageSize   int64
}

type FindEntitiesRow struct {
	EntityID string
	Version  int64
}

func (q *Queries) FindEntities(ctx context.Context, arg FindEntitiesParams) ([]FindEntitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, findEntities,
		arg.ZoneID,
		arg.Title,
		arg.EntityType,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindEntitiesRow{}
	for rows.Next() {
		var i FindEntitiesRow
		if err := rows.Scan(&i.EntityID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClaimVersion = `-- name: GetClaimVersion :one
SELECT i.subject_kind, i.subject_id, i.claim_type,
       v.version, v.deleted, v.content_hash, v.description
FROM claim_identities i
JOIN knowledge_versions v
  ON v.zone_id = i.zone_id AND v.knowledge_kind = 'claim'
 AND v.knowledge_id = i.claim_id
WHERE i.zone_id = ?1 AND i.claim_id = ?2
  AND v.version = ?3 AND v.candidate_number = 0
`

type GetClaimVersionParams struct {
	ZoneID  string
	ClaimID string
	Version int64
}

type GetClaimVersionRow struct {
	SubjectKind string
	SubjectID   string
	ClaimType   string
	Version     int64
	Deleted     int64
	ContentHash []byte
	Description string
}

func (q *Queries) GetClaimVersion(ctx context.Context, arg GetClaimVersionParams) (GetClaimVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getClaimVersion, arg.ZoneID, arg.ClaimID, arg.Version)
	var i GetClaimVersionRow
	err := row.Scan(
		&i.SubjectKind,
		&i.SubjectID,
		&i.ClaimType,
		&i.Version,
		&i.Deleted,
		&i.ContentHash,
		&i.Description,
	)
	return i, err
}

const getCurrentClaim = `-- name: GetCurrentClaim :one
SELECT i.subject_kind, i.subject_id, i.claim_type,
       v.version, v.deleted, v.content_hash, v.description
FROM claim_identities i
JOIN knowledge_versions v
  ON v.zone_id = i.zone_id AND v.knowledge_kind = 'claim'
 AND v.knowledge_id = i.claim_id
WHERE i.zone_id = ?1 AND i.claim_id = ?2
  AND v.candidate_number = 0
ORDER BY v.version DESC
LIMIT 1
`

type GetCurrentClaimParams struct {
	ZoneID  string
	ClaimID string
}

type GetCurrentClaimRow struct {
	SubjectKind string
	SubjectID   string
	ClaimType   string
	Version     int64
	Deleted     int64
	ContentHash []byte
	Description string
}

func (q *Queries) GetCurrentClaim(ctx context.Context, arg GetCurrentClaimParams) (GetCurrentClaimRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentClaim, arg.ZoneID, arg.ClaimID)
	var i GetCurrentClaimRow
	err := row.Scan(
		&i.SubjectKind,
		&i.SubjectID,
		&i.ClaimType,
		&i.Version,
		&i.Deleted,
		&i.ContentHash,
		&i.Description,
	)
	return i, err
}

const getCurrentEntity = `-- name: GetCurrentEntity :one
SELECT i.title, i.entity_type, v.version, v.deleted, v.content_hash, v.description
FROM entity_identities i
JOIN knowledge_versions v
  ON v.zone_id = i.zone_id AND v.knowledge_kind = 'entity'
 AND v.knowledge_id = i.entity_id
WHERE i.zone_id = ?1 AND i.entity_id = ?2
  AND v.candidate_number = 0
ORDER BY v.version DESC
LIMIT 1
`

type GetCurrentEntityParams struct {
	ZoneID   string
	EntityID string
}

type GetCurrentEntityRow struct {
	Title       string
	EntityType  string
	Version     int64
	Deleted     int64
	ContentHash []byte
	Description string
}

func (q *Queries) GetCurrentEntity(ctx context.Context, arg GetCurrentEntityParams) (GetCurrentEntityRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentEntity, arg.ZoneID, arg.EntityID)
	var i GetCurrentEntityRow
	err := row.Scan(
		&i.Title,
		&i.EntityType,
		&i.Version,
		&i.Deleted,
		&i.ContentHash,
		&i.Description,
	)
	return i, err
}

const getCurrentRelation = `-- name: GetCurrentRelation :one
SELECT i.source_entity_id, i.target_entity_id, i.relation_type,
       v.version, v.deleted, v.content_hash, v.description
FROM relation_identities i
JOIN knowledge_versions v
  ON v.zone_id = i.zone_id AND v.knowledge_kind = 'relation'
 AND v.knowledge_id = i.relation_id
WHERE i.zone_id = ?1 AND i.relation_id = ?2
  AND v.candidate_number = 0
ORDER BY v.version DESC
LIMIT 1
`

type GetCurrentRelationParams struct {
	ZoneID     string
	RelationID string
}

type GetCurrentRelationRow struct {
	SourceEntityID string
	TargetEntityID string
	RelationType   string
	Version        int64
	Deleted        int64
	ContentHash    []byte
	Description    string
}

func (q *Queries) GetCurrentRelation(ctx context.Context, arg GetCurrentRelationParams) (GetCurrentRelationRow, error) {
	row := q.db.QueryRowContext(ctx, getCurrentRelation, arg.ZoneID, arg.RelationID)
	var i GetCurrentRelationRow
	err := row.Scan(
		&i.SourceEntityID,
		&i.TargetEntityID,
		&i.RelationType,
		&i.Version,
		&i.Deleted,
		&i.ContentHash,
		&i.Description,
	)
	return i, err
}

const getEntityVersion = `-- name: GetEntityVersion :one
SELECT i.title, i.entity_type, v.version, v.deleted, v.content_hash, v.description
FROM entity_identities i
JOIN knowledge_versions v
  ON v.zone_id = i.zone_id AND v.knowledge_kind = 'entity'
 AND v.knowledge_id = i.entity_id
WHERE i.zone_id = ?1 AND i.entity_id = ?2
  AND v.version = ?3 AND v.candidate_number = 0
`

type GetEntityVersionParams struct {
	ZoneID   string
	EntityID string
	Version  int64
}

type GetEntityVersionRow struct {
	Title       string
	EntityType  string
	Version     int64
	Deleted     int64
	ContentHash []byte
	Description string
}

func (q *Queries) GetEntityVersion(ctx context.Context, arg GetEntityVersionParams) (GetEntityVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getEntityVersion, arg.ZoneID, arg.EntityID, arg.Version)
	var i GetEntityVersionRow
	err := row.Scan(
		&i.Title,
		&i.EntityType,
		&i.Version,
		&i.Deleted,
		&i.ContentHash,
		&i.Description,
	)
	return i, err
}

const getRelationVersion = `-- name: GetRelationVersion :one
SELECT i.source_entity_id, i.target_entity_id, i.relation_type,
       v.version, v.deleted, v.content_hash, v.description
FROM relation_identities i
JOIN knowledge_versions v
  ON v.zone_id = i.zone_id AND v.knowledge_kind = 'relation'
 AND v.knowledge_id = i.relation_id
WHERE i.zone_id = ?1 AND i.relation_id = ?2
  AND v.version = ?3 AND v.candidate_number = 0
`

type GetRelationVersionParams struct {
	ZoneID     string
	RelationID string
	Version    int64
}

type GetRelationVersionRow struct {
	SourceEntityID string
	TargetEntityID string
	RelationType   string
	Version        int64
	Deleted        int64
	ContentHash    []byte
	Description    string
}

func (q *Queries) GetRelationVersion(ctx context.Context, arg GetRelationVersionParams) (GetRelationVersionRow, error) {
	row := q.db.QueryRowContext(ctx, getRelationVersion, arg.ZoneID, arg.RelationID, arg.Version)
	var i GetRelationVersionRow
	err := row.Scan(
		&i.SourceEntityID,
		&i.TargetEntityID,
		&i.RelationType,
		&i.Version,
		&i.Deleted,
		&i.ContentHash,
		&i.Description,
	)
	return i, err
}

const listActiveClaimReferences = `-- name: ListActiveClaimReferences :many
SELECT v.knowledge_id AS claim_id, v.version
FROM knowledge_versions v
WHERE v.zone_id = ?1 AND v.knowledge_kind = 'claim'
  AND v.candidate_number = 0 AND v.deleted = 0
  AND v.version = (
      SELECT MAX(current.version) FROM knowledge_versions current
      WHERE current.zone_id = v.zone_id
        AND current.knowledge_kind = v.knowledge_kind
        AND current.knowledge_id = v.knowledge_id
        AND current.candidate_number = 0
  )
  AND v.knowledge_id > ?2
ORDER BY v.knowledge_id
LIMIT ?3
`

type ListActiveClaimReferencesParams struct {
	ZoneID       string
	AfterClaimID string
	PageSize     int64
}

type ListActiveClaimReferencesRow struct {
	ClaimID string
	Version int64
}

func (q *Queries) ListActiveClaimReferences(ctx context.Context, arg ListActiveClaimReferencesParams) ([]ListActiveClaimReferencesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveClaimReferences, arg.ZoneID, arg.AfterClaimID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveClaimReferencesRow{}
	for rows.Next() {
		var i ListActiveClaimReferencesRow
		if err := rows.Scan(&i.ClaimID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveClaims = `-- name: ListActiveClaims :many
SELECT i.claim_id FROM claim_identities i
JOIN knowledge_versions v
  ON v.zone_id = i.zone_id AND v.knowledge_kind = 'claim'
 AND v.knowledge_id = i.claim_id AND v.deleted = 0
 AND v.candidate_number = 0
WHERE i.zone_id = ?1
  AND i.subject_kind = ?2
  AND i.subject_id = ?3
  AND v.version = (
      SELECT MAX(current.version) FROM knowledge_versions current
      WHERE current.zone_id = v.zone_id
        AND current.knowledge_kind = v.knowledge_kind
        AND current.knowledge_id = v.knowledge_id
        AND current.candidate_number = 0
  )
ORDER BY i.claim_id
`

type ListActiveClaimsParams struct {
	ZoneID      string
	SubjectKind string
	SubjectID   string
}

func (q *Queries) ListActiveClaims(ctx context.Context, arg ListActiveClaimsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveClaims, arg.ZoneID, arg.SubjectKind, arg.SubjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var claim_id string
		if err := rows.Scan(&claim_id); err != nil {
			return nil, err
		}
		items = append(items, claim_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveEntityReferences = `-- name: ListActiveEntityReferences :many
SELECT v.knowledge_id AS entity_id, v.version
FROM knowledge_versions v
WHERE v.zone_id = ?1 AND v.knowledge_kind = 'entity'
  AND v.candidate_number = 0 AND v.deleted = 0
  AND v.version = (
      SELECT MAX(current.version) FROM knowledge_versions current
      WHERE current.zone_id = v.zone_id
        AND current.knowledge_kind = v.knowledge_kind
        AND current.knowledge_id = v.knowledge_id
        AND current.candidate_number = 0
  )
  AND v.knowledge_id > ?2
ORDER BY v.knowledge_id
LIMIT ?3
`

type ListActiveEntityReferencesParams struct {
	ZoneID        string
	AfterEntityID string
	PageSize      int64
}

type ListActiveEntityReferencesRow struct {
	EntityID string
	Version  int64
}

func (q *Queries) ListActiveEntityReferences(ctx context.Context, arg ListActiveEntityReferencesParams) ([]ListActiveEntityReferencesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveEntityReferences, arg.ZoneID, arg.AfterEntityID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveEntityReferencesRow{}
	for rows.Next() {
		var i ListActiveEntityReferencesRow
		if err := rows.Scan(&i.EntityID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveRelationReferences = `-- name: ListActiveRelationReferences :many
SELECT v.knowledge_id AS relation_id, v.version
FROM knowledge_versions v
WHERE v.zone_id = ?1 AND v.knowledge_kind = 'relation'
  AND v.candidate_number = 0 AND v.deleted = 0
  AND v.version = (
      SELECT MAX(current.version) FROM knowledge_versions current
      WHERE current.zone_id = v.zone_id
        AND current.knowledge_kind = v.knowledge_kind
        AND current.knowledge_id = v.knowledge_id
        AND current.candidate_number = 0
  )
  AND v.knowledge_id > ?2
ORDER BY v.knowledge_id
LIMIT ?3
`

type ListActiveRelationReferencesParams struct {
	ZoneID          string
	AfterRelationID string
	PageSize        int64
}

type ListActiveRelationReferencesRow struct {
	RelationID string
	Version    int64
}

func (q *Queries) ListActiveRelationReferences(ctx context.Context, arg ListActiveRelationReferencesParams) ([]ListActiveRelationReferencesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRelationReferences, arg.ZoneID, arg.AfterRelationID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveRelationReferencesRow{}
	for rows.Next() {
		var i ListActiveRelationReferencesRow
		if err := rows.Scan(&i.RelationID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveRelations = `-- name: ListActiveRelations :many
SELECT i.relation_id FROM relation_identities i
JOIN knowledge_versions v
  ON v.zone_id = i.zone_id AND v.knowledge_kind = 'relation'
 AND v.knowledge_id = i.relation_id AND v.deleted = 0
 AND v.candidate_number = 0
WHERE i.zone_id = ?1
  AND (i.source_entity_id = ?2 OR i.target_entity_id = ?2)
  AND v.version = (
      SELECT MAX(current.version) FROM knowledge_versions current
      WHERE current.zone_id = v.zone_id
        AND current.knowledge_kind = v.knowledge_kind
        AND current.knowledge_id = v.knowledge_id
        AND current.candidate_number = 0
  )
ORDER BY i.relation_id
`

type ListActiveRelationsParams struct {
	ZoneID   string
	EntityID string
}

func (q *Queries) ListActiveRelations(ctx context.Context, arg ListActiveRelationsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveRelations, arg.ZoneID, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var relation_id string
		if err := rows.Scan(&relation_id); err != nil {
			return nil, err
		}
		items = append(items, relation_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimHistory = `-- name: ListClaimHistory :many
SELECT i.subject_kind, i.subject_id, i.claim_type,
       v.version, v.deleted, v.content_hash, v.description
FROM claim_identities i
JOIN knowledge_versions v
  ON v.zone_id = i.zone_id AND v.knowledge_kind = 'claim'
 AND v.knowledge_id = i.claim_id
WHERE i.zone_id = ?1 AND i.claim_id = ?2
  AND v.candidate_number = 0 AND v.version > ?3
ORDER BY v.version
LIMIT ?4
`

type ListClaimHistoryParams struct {
	ZoneID       string
	ClaimID      string
	AfterVersion int64
	PageSize     int64
}

type ListClaimHistoryRow struct {
	SubjectKind string
	SubjectID   string
	ClaimType   string
	Version     int64
	Deleted     int64
	ContentHash []byte
	Description string
}

func (q *Queries) ListClaimHistory(ctx context.Context, arg ListClaimHistoryParams) ([]ListClaimHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listClaimHistory,
		arg.ZoneID,
		arg.ClaimID,
		arg.AfterVersion,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClaimHistoryRow{}
	for rows.Next() {
		var i ListClaimHistoryRow
		if err := rows.Scan(
			&i.SubjectKind,
			&i.SubjectID,
			&i.ClaimType,
			&i.Version,
			&i.Deleted,
			&i.ContentHash,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentClaims = `-- name: ListCurrentClaims :many
SELECT i.claim_id, i.subject_kind, i.subject_id, i.claim_type,
       v.version, v.deleted, v.content_hash, v.description
FROM claim_identities i
JOIN knowledge_versions v
  ON v.zone_id = i.zone_id AND v.knowledge_kind = 'claim'
 AND v.knowledge_id = i.claim_id
WHERE i.zone_id = ?1
  AND i.claim_id > ?2
  AND v.candidate_number = 0
  AND v.version = (
      SELECT MAX(current.version) FROM knowledge_versions current
      WHERE current.zone_id = v.zone_id
        AND current.knowledge_kind = v.knowledge_kind
        AND current.knowledge_id = v.knowledge_id
        AND current.candidate_number = 0
  )
ORDER BY i.claim_id
LIMIT ?3
`

type ListCurrentClaimsParams struct {
	ZoneID       string
	AfterClaimID string
	PageSize     int64
}

type ListCurrentClaimsRow struct {
	ClaimID     string
	SubjectKind string
	SubjectID   string
	ClaimType   string
	Version     int64
	Deleted     int64
	ContentHash []byte
	Description string
}

func (q *Queries) ListCurrentClaims(ctx context.Context, arg ListCurrentClaimsParams) ([]ListCurrentClaimsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentClaims, arg.ZoneID, arg.AfterClaimID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentClaimsRow{}
	for rows.Next() {
		var i ListCurrentClaimsRow
		if err := rows.Scan(
			&i.ClaimID,
			&i.SubjectKind,
			&i.SubjectID,
			&i.ClaimType,
			&i.Version,
			&i.Deleted,
			&i.ContentHash,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentEntities = `-- name: ListCurrentEntities :many
SELECT i.entity_id, i.title, i.entity_type,
       v.version, v.deleted, v.content_hash, v.description
FROM entity_identities i
JOIN knowledge_versions v
  ON v.zone_id = i.zone_id AND v.knowledge_kind = 'entity'
 AND v.knowledge_id = i.entity_id
WHERE i.zone_id = ?1
  AND i.entity_id > ?2
  AND v.candidate_number = 0
  AND v.version = (
      SELECT MAX(current.version) FROM knowledge_versions current
      WHERE current.zone_id = v.zone_id
        AND current.knowledge_kind = v.knowledge_kind
        AND current.knowledge_id = v.knowledge_id
        AND current.candidate_number = 0
  )
ORDER BY i.entity_id
LIMIT ?3
`

type ListCurrentEntitiesParams struct {
	ZoneID        string
	AfterEntityID string
	PageSize      int64
}

type ListCurrentEntitiesRow struct {
	EntityID    string
	Title       string
	EntityType  string
	Version     int64
	Deleted     int64
	ContentHash []byte
	Description string
}

func (q *Queries) ListCurrentEntities(ctx context.Context, arg ListCurrentEntitiesParams) ([]ListCurrentEntitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentEntities, arg.ZoneID, arg.AfterEntityID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentEntitiesRow{}
	for rows.Next() {
		var i ListCurrentEntitiesRow
		if err := rows.Scan(
			&i.EntityID,
			&i.Title,
			&i.EntityType,
			&i.Version,
			&i.Deleted,
			&i.ContentHash,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentRelations = `-- name: ListCurrentRelations :many
SELECT i.relation_id, i.source_entity_id, i.target_entity_id, i.relation_type,
       v.version, v.deleted, v.content_hash, v.description
FROM relation_identities i
JOIN knowledge_versions v
  ON v.zone_id = i.zone_id AND v.knowledge_kind = 'relation'
 AND v.knowledge_id = i.relation_id
WHERE i.zone_id = ?1
  AND i.relation_id > ?2
  AND v.candidate_number = 0
  AND v.version = (
      SELECT MAX(current.version) FROM knowledge_versions current
      WHERE current.zone_id = v.zone_id
        AND current.knowledge_kind = v.knowledge_kind
        AND current.knowledge_id = v.knowledge_id
        AND current.candidate_number = 0
  )
ORDER BY i.relation_id
LIMIT ?3
`

type ListCurrentRelationsParams struct {
	ZoneID          string
	AfterRelationID string
	PageSize        int64
}

type ListCurrentRelationsRow struct {
	RelationID     string
	SourceEntityID string
	TargetEntityID string
	RelationType   string
	Version        int64
	Deleted        int64
	ContentHash    []byte
	Description    string
}

func (q *Queries) ListCurrentRelations(ctx context.Context, arg ListCurrentRelationsParams) ([]ListCurrentRelationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentRelations, arg.ZoneID, arg.AfterRelationID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCurrentRelationsRow{}
	for rows.Next() {
		var i ListCurrentRelationsRow
		if err := rows.Scan(
			&i.RelationID,
			&i.SourceEntityID,
			&i.TargetEntityID,
			&i.RelationType,
			&i.Version,
			&i.Deleted,
			&i.ContentHash,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityAliases = `-- name: ListEntityAliases :many
SELECT alias FROM entity_version_aliases
WHERE zone_id = ?1
  AND entity_id = ?2
  AND version = ?3 AND candidate_number = 0
ORDER BY alias
`

type ListEntityAliasesParams struct {
	ZoneID   string
	EntityID string
	Version  int64
}

func (q *Queries) ListEntityAliases(ctx context.Context, arg ListEntityAliasesParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listEntityAliases, arg.ZoneID, arg.EntityID, arg.Version)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var alias string
		if err := rows.Scan(&alias); err != nil {
			return nil, err
		}
		items = append(items, alias)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityHistory = `-- name: ListEntityHistory :many
SELECT i.title, i.entity_type, v.version, v.deleted, v.content_hash, v.description
FROM entity_identities i
JOIN knowledge_versions v
  ON v.zone_id = i.zone_id AND v.knowledge_kind = 'entity'
 AND v.knowledge_id = i.entity_id
WHERE i.zone_id = ?1 AND i.entity_id = ?2
  AND v.candidate_number = 0 AND v.version > ?3
ORDER BY v.version
LIMIT ?4
`

type ListEntityHistoryParams struct {
	ZoneID       string
	EntityID     string
	AfterVersion int64
	PageSize     int64
}

type ListEntityHistoryRow struct {
	Title       string
	EntityType  string
	Version     int64
	Deleted     int64
	ContentHash []byte
	Description string
}

func (q *Queries) ListEntityHistory(ctx context.Context, arg ListEntityHistoryParams) ([]ListEntityHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntityHistory,
		arg.ZoneID,
		arg.EntityID,
		arg.AfterVersion,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEntityHistoryRow{}
	for rows.Next() {
		var i ListEntityHistoryRow
		if err := rows.Scan(
			&i.Title,
			&i.EntityType,
			&i.Version,
			&i.Deleted,
			&i.ContentHash,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelationHistory = `-- name: ListRelationHistory :many
SELECT i.source_entity_id, i.target_entity_id, i.relation_type,
       v.version, v.deleted, v.content_hash, v.description
FROM relation_identities i
JOIN knowledge_versions v
  ON v.zone_id = i.zone_id AND v.knowledge_kind = 'relation'
 AND v.knowledge_id = i.relation_id
WHERE i.zone_id = ?1 AND i.relation_id = ?2
  AND v.candidate_number = 0 AND v.version > ?3
ORDER BY v.version
LIMIT ?4
`

type ListRelationHistoryParams struct {
	ZoneID       string
	RelationID   string
	AfterVersion int64
	PageSize     int64
}

type ListRelationHistoryRow struct {
	SourceEntityID string
	TargetEntityID string
	RelationType   string
	Version        int64
	Deleted        int64
	ContentHash    []byte
	Description    string
}

func (q *Queries) ListRelationHistory(ctx context.Context, arg ListRelationHistoryParams) ([]ListRelationHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listRelationHistory,
		arg.ZoneID,
		arg.RelationID,
		arg.AfterVersion,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRelationHistoryRow{}
	for rows.Next() {
		var i ListRelationHistoryRow
		if err := rows.Scan(
			&i.SourceEntityID,
			&i.TargetEntityID,
			&i.RelationType,
			&i.Version,
			&i.Deleted,
			&i.ContentHash,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
