// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: zone_merging.sql

package db

import (
	"context"
	"database/sql"
)

const getResolvedZoneClaimConflict = `-- name: GetResolvedZoneClaimConflict :one
SELECT c.child_knowledge_id AS child_claim_id, c.child_base_version,
       v.content_hash AS candidate_content_hash, c.parent_zone_id,
       c.parent_knowledge_id AS parent_claim_id, c.parent_version, c.parent_reconciled
FROM zone_knowledge_conflicts c
JOIN knowledge_versions v
  ON v.zone_id = c.child_zone_id AND v.knowledge_kind = c.knowledge_kind
 AND v.knowledge_id = c.child_knowledge_id AND v.version = c.child_base_version
 AND v.candidate_number = c.child_candidate_number
WHERE c.child_zone_id = ?1 AND c.knowledge_kind = 'claim'
  AND c.resolved_by_source_id = ?2
LIMIT 1
`

type GetResolvedZoneClaimConflictParams struct {
	ChildZoneID        string
	ResolutionSourceID sql.NullString
}

type GetResolvedZoneClaimConflictRow struct {
	ChildClaimID         string
	ChildBaseVersion     int64
	CandidateContentHash []byte
	ParentZoneID         string
	ParentClaimID        string
	ParentVersion        int64
	ParentReconciled     int64
}

func (q *Queries) GetResolvedZoneClaimConflict(ctx context.Context, arg GetResolvedZoneClaimConflictParams) (GetResolvedZoneClaimConflictRow, error) {
	row := q.db.QueryRowContext(ctx, getResolvedZoneClaimConflict, arg.ChildZoneID, arg.ResolutionSourceID)
	var i GetResolvedZoneClaimConflictRow
	err := row.Scan(
		&i.ChildClaimID,
		&i.ChildBaseVersion,
		&i.CandidateContentHash,
		&i.ParentZoneID,
		&i.ParentClaimID,
		&i.ParentVersion,
		&i.ParentReconciled,
	)
	return i, err
}

const getResolvedZoneEntityConflict = `-- name: GetResolvedZoneEntityConflict :one
SELECT c.child_knowledge_id AS child_entity_id, c.child_base_version,
       v.content_hash AS candidate_content_hash, c.parent_zone_id,
       c.parent_knowledge_id AS parent_entity_id, c.parent_version, c.parent_reconciled
FROM zone_knowledge_conflicts c
JOIN knowledge_versions v
  ON v.zone_id = c.child_zone_id AND v.knowledge_kind = c.knowledge_kind
 AND v.knowledge_id = c.child_knowledge_id AND v.version = c.child_base_version
 AND v.candidate_number = c.child_candidate_number
WHERE c.child_zone_id = ?1 AND c.knowledge_kind = 'entity'
  AND c.resolved_by_source_id = ?2
LIMIT 1
`

type GetResolvedZoneEntityConflictParams struct {
	ChildZoneID        string
	ResolutionSourceID sql.NullString
}

type GetResolvedZoneEntityConflictRow struct {
	ChildEntityID        string
	ChildBaseVersion     int64
	CandidateContentHash []byte
	ParentZoneID         string
	ParentEntityID       string
	ParentVersion        int64
	ParentReconciled     int64
}

func (q *Queries) GetResolvedZoneEntityConflict(ctx context.Context, arg GetResolvedZoneEntityConflictParams) (GetResolvedZoneEntityConflictRow, error) {
	row := q.db.QueryRowContext(ctx, getResolvedZoneEntityConflict, arg.ChildZoneID, arg.ResolutionSourceID)
	var i GetResolvedZoneEntityConflictRow
	err := row.Scan(
		&i.ChildEntityID,
		&i.ChildBaseVersion,
		&i.CandidateContentHash,
		&i.ParentZoneID,
		&i.ParentEntityID,
		&i.ParentVersion,
		&i.ParentReconciled,
	)
	return i, err
}

const getResolvedZoneRelationConflict = `-- name: GetResolvedZoneRelationConflict :one
SELECT c.child_knowledge_id AS child_relation_id, c.child_base_version,
       v.content_hash AS candidate_content_hash, c.parent_zone_id,
       c.parent_knowledge_id AS parent_relation_id, c.parent_version, c.parent_reconciled
FROM zone_knowledge_conflicts c
JOIN knowledge_versions v
  ON v.zone_id = c.child_zone_id AND v.knowledge_kind = c.knowledge_kind
 AND v.knowledge_id = c.child_knowledge_id AND v.version = c.child_base_version
 AND v.candidate_number = c.child_candidate_number
WHERE c.child_zone_id = ?1 AND c.knowledge_kind = 'relation'
  AND c.resolved_by_source_id = ?2
LIMIT 1
`

type GetResolvedZoneRelationConflictParams struct {
	ChildZoneID        string
	ResolutionSourceID sql.NullString
}

type GetResolvedZoneRelationConflictRow struct {
	ChildRelationID      string
	ChildBaseVersion     int64
	CandidateContentHash []byte
	ParentZoneID         string
	ParentRelationID     string
	ParentVersion        int64
	ParentReconciled     int64
}

func (q *Queries) GetResolvedZoneRelationConflict(ctx context.Context, arg GetResolvedZoneRelationConflictParams) (GetResolvedZoneRelationConflictRow, error) {
	row := q.db.QueryRowContext(ctx, getResolvedZoneRelationConflict, arg.ChildZoneID, arg.ResolutionSourceID)
	var i GetResolvedZoneRelationConflictRow
	err := row.Scan(
		&i.ChildRelationID,
		&i.ChildBaseVersion,
		&i.CandidateContentHash,
		&i.ParentZoneID,
		&i.ParentRelationID,
		&i.ParentVersion,
		&i.ParentReconciled,
	)
	return i, err
}

const getZoneClaimConflict = `-- name: GetZoneClaimConflict :one
SELECT v.content_hash AS candidate_content_hash, c.parent_zone_id,
       c.parent_knowledge_id AS parent_claim_id, c.parent_version
FROM zone_knowledge_conflicts c
JOIN knowledge_versions v
  ON v.zone_id = c.child_zone_id AND v.knowledge_kind = c.knowledge_kind
 AND v.knowledge_id = c.child_knowledge_id AND v.version = c.child_base_version
 AND v.candidate_number = c.child_candidate_number
WHERE c.child_zone_id = ?1 AND c.knowledge_kind = 'claim'
  AND c.child_knowledge_id = ?2
  AND c.child_base_version = ?3
  AND c.resolved_by_source_id IS NULL
LIMIT 1
`

type GetZoneClaimConflictParams struct {
	ChildZoneID      string
	ChildClaimID     string
	ChildBaseVersion int64
}

type GetZoneClaimConflictRow struct {
	CandidateContentHash []byte
	ParentZoneID         string
	ParentClaimID        string
	ParentVersion        int64
}

func (q *Queries) GetZoneClaimConflict(ctx context.Context, arg GetZoneClaimConflictParams) (GetZoneClaimConflictRow, error) {
	row := q.db.QueryRowContext(ctx, getZoneClaimConflict, arg.ChildZoneID, arg.ChildClaimID, arg.ChildBaseVersion)
	var i GetZoneClaimConflictRow
	err := row.Scan(
		&i.CandidateContentHash,
		&i.ParentZoneID,
		&i.ParentClaimID,
		&i.ParentVersion,
	)
	return i, err
}

const getZoneEntityConflict = `-- name: GetZoneEntityConflict :one
SELECT v.content_hash AS candidate_content_hash, c.parent_zone_id,
       c.parent_knowledge_id AS parent_entity_id, c.parent_version
FROM zone_knowledge_conflicts c
JOIN knowledge_versions v
  ON v.zone_id = c.child_zone_id AND v.knowledge_kind = c.knowledge_kind
 AND v.knowledge_id = c.child_knowledge_id AND v.version = c.child_base_version
 AND v.candidate_number = c.child_candidate_number
WHERE c.child_zone_id = ?1 AND c.knowledge_kind = 'entity'
  AND c.child_knowledge_id = ?2
  AND c.child_base_version = ?3
  AND c.resolved_by_source_id IS NULL
LIMIT 1
`

type GetZoneEntityConflictParams struct {
	ChildZoneID      string
	ChildEntityID    string
	ChildBaseVersion int64
}

type GetZoneEntityConflictRow struct {
	CandidateContentHash []byte
	ParentZoneID         string
	ParentEntityID       string
	ParentVersion        int64
}

func (q *Queries) GetZoneEntityConflict(ctx context.Context, arg GetZoneEntityConflictParams) (GetZoneEntityConflictRow, error) {
	row := q.db.QueryRowContext(ctx, getZoneEntityConflict, arg.ChildZoneID, arg.ChildEntityID, arg.ChildBaseVersion)
	var i GetZoneEntityConflictRow
	err := row.Scan(
		&i.CandidateContentHash,
		&i.ParentZoneID,
		&i.ParentEntityID,
		&i.ParentVersion,
	)
	return i, err
}

const getZoneRelationConflict = `-- name: GetZoneRelationConflict :one
SELECT v.content_hash AS candidate_content_hash, c.parent_zone_id,
       c.parent_knowledge_id AS parent_relation_id, c.parent_version
FROM zone_knowledge_conflicts c
JOIN knowledge_versions v
  ON v.zone_id = c.child_zone_id AND v.knowledge_kind = c.knowledge_kind
 AND v.knowledge_id = c.child_knowledge_id AND v.version = c.child_base_version
 AND v.candidate_number = c.child_candidate_number
WHERE c.child_zone_id = ?1 AND c.knowledge_kind = 'relation'
  AND c.child_knowledge_id = ?2
  AND c.child_base_version = ?3
  AND c.resolved_by_source_id IS NULL
LIMIT 1
`

type GetZoneRelationConflictParams struct {
	ChildZoneID      string
	ChildRelationID  string
	ChildBaseVersion int64
}

type GetZoneRelationConflictRow struct {
	CandidateContentHash []byte
	ParentZoneID         string
	ParentRelationID     string
	ParentVersion        int64
}

func (q *Queries) GetZoneRelationConflict(ctx context.Context, arg GetZoneRelationConflictParams) (GetZoneRelationConflictRow, error) {
	row := q.db.QueryRowContext(ctx, getZoneRelationConflict, arg.ChildZoneID, arg.ChildRelationID, arg.ChildBaseVersion)
	var i GetZoneRelationConflictRow
	err := row.Scan(
		&i.CandidateContentHash,
		&i.ParentZoneID,
		&i.ParentRelationID,
		&i.ParentVersion,
	)
	return i, err
}

const reconcileZoneClaimConflict = `-- name: ReconcileZoneClaimConflict :execrows
UPDATE zone_knowledge_conflicts SET parent_reconciled = 1
WHERE child_zone_id = ?1 AND knowledge_kind = 'claim'
  AND child_knowledge_id = ?2
  AND child_base_version = ?3
  AND child_candidate_number = (
      SELECT candidate_number FROM knowledge_versions
      WHERE zone_id = ?1 AND knowledge_kind = 'claim'
        AND knowledge_id = ?2
        AND version = ?3 AND candidate_number > 0
        AND content_hash = ?4
  )
  AND parent_zone_id = ?5
  AND parent_knowledge_id = ?6
  AND parent_version = ?7
  AND zone_knowledge_conflicts.resolved_by_source_id = ?8
  AND parent_reconciled = 0
`

type ReconcileZoneClaimConflictParams struct {
	ChildZoneID          string
	ChildClaimID         string
	ChildBaseVersion     int64
	CandidateContentHash []byte
	ParentZoneID         string
	ParentClaimID        string
	ParentVersion        int64
	ResolutionSourceID   sql.NullString
}

func (q *Queries) ReconcileZoneClaimConflict(ctx context.Context, arg ReconcileZoneClaimConflictParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reconcileZoneClaimConflict,
		arg.ChildZoneID,
		arg.ChildClaimID,
		arg.ChildBaseVersion,
		arg.CandidateContentHash,
		arg.ParentZoneID,
		arg.ParentClaimID,
		arg.ParentVersion,
		arg.ResolutionSourceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reconcileZoneEntityConflict = `-- name: ReconcileZoneEntityConflict :execrows
UPDATE zone_knowledge_conflicts SET parent_reconciled = 1
WHERE child_zone_id = ?1 AND knowledge_kind = 'entity'
  AND child_knowledge_id = ?2
  AND child_base_version = ?3
  AND child_candidate_number = (
      SELECT candidate_number FROM knowledge_versions
      WHERE zone_id = ?1 AND knowledge_kind = 'entity'
        AND knowledge_id = ?2
        AND version = ?3 AND candidate_number > 0
        AND content_hash = ?4
  )
  AND parent_zone_id = ?5
  AND parent_knowledge_id = ?6
  AND parent_version = ?7
  AND zone_knowledge_conflicts.resolved_by_source_id = ?8
  AND parent_reconciled = 0
`

type ReconcileZoneEntityConflictParams struct {
	ChildZoneID          string
	ChildEntityID        string
	ChildBaseVersion     int64
	CandidateContentHash []byte
	ParentZoneID         string
	ParentEntityID       string
	ParentVersion        int64
	ResolutionSourceID   sql.NullString
}

func (q *Queries) ReconcileZoneEntityConflict(ctx context.Context, arg ReconcileZoneEntityConflictParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reconcileZoneEntityConflict,
		arg.ChildZoneID,
		arg.ChildEntityID,
		arg.ChildBaseVersion,
		arg.CandidateContentHash,
		arg.ParentZoneID,
		arg.ParentEntityID,
		arg.ParentVersion,
		arg.ResolutionSourceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reconcileZoneRelationConflict = `-- name: ReconcileZoneRelationConflict :execrows
UPDATE zone_knowledge_conflicts SET parent_reconciled = 1
WHERE child_zone_id = ?1 AND knowledge_kind = 'relation'
  AND child_knowledge_id = ?2
  AND child_base_version = ?3
  AND child_candidate_number = (
      SELECT candidate_number FROM knowledge_versions
      WHERE zone_id = ?1 AND knowledge_kind = 'relation'
        AND knowledge_id = ?2
        AND version = ?3 AND candidate_number > 0
        AND content_hash = ?4
  )
  AND parent_zone_id = ?5
  AND parent_knowledge_id = ?6
  AND parent_version = ?7
  AND zone_knowledge_conflicts.resolved_by_source_id = ?8
  AND parent_reconciled = 0
`

type ReconcileZoneRelationConflictParams struct {
	ChildZoneID          string
	ChildRelationID      string
	ChildBaseVersion     int64
	CandidateContentHash []byte
	ParentZoneID         string
	ParentRelationID     string
	ParentVersion        int64
	ResolutionSourceID   sql.NullString
}

func (q *Queries) ReconcileZoneRelationConflict(ctx context.Context, arg ReconcileZoneRelationConflictParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reconcileZoneRelationConflict,
		arg.ChildZoneID,
		arg.ChildRelationID,
		arg.ChildBaseVersion,
		arg.CandidateContentHash,
		arg.ParentZoneID,
		arg.ParentRelationID,
		arg.ParentVersion,
		arg.ResolutionSourceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveZoneClaimConflict = `-- name: ResolveZoneClaimConflict :execrows
UPDATE zone_knowledge_conflicts
SET resolved_by_source_id = ?1
WHERE child_zone_id = ?2 AND knowledge_kind = 'claim'
  AND child_knowledge_id = ?3
  AND child_base_version = ?4
  AND child_candidate_number = (
      SELECT candidate_number FROM knowledge_versions
      WHERE zone_id = ?2 AND knowledge_kind = 'claim'
        AND knowledge_id = ?3
        AND version = ?4 AND candidate_number > 0
        AND content_hash = ?5
  )
  AND parent_zone_id = ?6
  AND parent_knowledge_id = ?7
  AND parent_version = ?8
  AND resolved_by_source_id IS NULL
`

type ResolveZoneClaimConflictParams struct {
	ResolutionSourceID   sql.NullString
	ChildZoneID          string
	ChildClaimID         string
	ChildBaseVersion     int64
	CandidateContentHash []byte
	ParentZoneID         string
	ParentClaimID        string
	ParentVersion        int64
}

func (q *Queries) ResolveZoneClaimConflict(ctx context.Context, arg ResolveZoneClaimConflictParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveZoneClaimConflict,
		arg.ResolutionSourceID,
		arg.ChildZoneID,
		arg.ChildClaimID,
		arg.ChildBaseVersion,
		arg.CandidateContentHash,
		arg.ParentZoneID,
		arg.ParentClaimID,
		arg.ParentVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveZoneEntityConflict = `-- name: ResolveZoneEntityConflict :execrows
UPDATE zone_knowledge_conflicts
SET resolved_by_source_id = ?1
WHERE child_zone_id = ?2 AND knowledge_kind = 'entity'
  AND child_knowledge_id = ?3
  AND child_base_version = ?4
  AND child_candidate_number = (
      SELECT candidate_number FROM knowledge_versions
      WHERE zone_id = ?2 AND knowledge_kind = 'entity'
        AND knowledge_id = ?3
        AND version = ?4 AND candidate_number > 0
        AND content_hash = ?5
  )
  AND parent_zone_id = ?6
  AND parent_knowledge_id = ?7
  AND parent_version = ?8
  AND resolved_by_source_id IS NULL
`

type ResolveZoneEntityConflictParams struct {
	ResolutionSourceID   sql.NullString
	ChildZoneID          string
	ChildEntityID        string
	ChildBaseVersion     int64
	CandidateContentHash []byte
	ParentZoneID         string
	ParentEntityID       string
	ParentVersion        int64
}

func (q *Queries) ResolveZoneEntityConflict(ctx context.Context, arg ResolveZoneEntityConflictParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveZoneEntityConflict,
		arg.ResolutionSourceID,
		arg.ChildZoneID,
		arg.ChildEntityID,
		arg.ChildBaseVersion,
		arg.CandidateContentHash,
		arg.ParentZoneID,
		arg.ParentEntityID,
		arg.ParentVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const resolveZoneRelationConflict = `-- name: ResolveZoneRelationConflict :execrows
UPDATE zone_knowledge_conflicts
SET resolved_by_source_id = ?1
WHERE child_zone_id = ?2 AND knowledge_kind = 'relation'
  AND child_knowledge_id = ?3
  AND child_base_version = ?4
  AND child_candidate_number = (
      SELECT candidate_number FROM knowledge_versions
      WHERE zone_id = ?2 AND knowledge_kind = 'relation'
        AND knowledge_id = ?3
        AND version = ?4 AND candidate_number > 0
        AND content_hash = ?5
  )
  AND parent_zone_id = ?6
  AND parent_knowledge_id = ?7
  AND parent_version = ?8
  AND resolved_by_source_id IS NULL
`

type ResolveZoneRelationConflictParams struct {
	ResolutionSourceID   sql.NullString
	ChildZoneID          string
	ChildRelationID      string
	ChildBaseVersion     int64
	CandidateContentHash []byte
	ParentZoneID         string
	ParentRelationID     string
	ParentVersion        int64
}

func (q *Queries) ResolveZoneRelationConflict(ctx context.Context, arg ResolveZoneRelationConflictParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, resolveZoneRelationConflict,
		arg.ResolutionSourceID,
		arg.ChildZoneID,
		arg.ChildRelationID,
		arg.ChildBaseVersion,
		arg.CandidateContentHash,
		arg.ParentZoneID,
		arg.ParentRelationID,
		arg.ParentVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const saveZoneClaimConflict = `-- name: SaveZoneClaimConflict :exec
INSERT INTO zone_knowledge_conflicts
    (child_zone_id, knowledge_kind, child_knowledge_id, child_base_version,
     child_candidate_number, parent_zone_id, parent_knowledge_id, parent_version)
SELECT ?1, 'claim', ?2,
       ?3, v.candidate_number,
       ?4, ?5, ?6
FROM knowledge_versions v
WHERE v.zone_id = ?1 AND v.knowledge_kind = 'claim'
  AND v.knowledge_id = ?2
  AND v.version = ?3 AND v.candidate_number > 0
  AND v.content_hash = ?7
ON CONFLICT DO NOTHING
`

type SaveZoneClaimConflictParams struct {
	ChildZoneID          string
	ChildClaimID         string
	ChildBaseVersion     int64
	ParentZoneID         string
	ParentClaimID        string
	ParentVersion        int64
	CandidateContentHash []byte
}

func (q *Queries) SaveZoneClaimConflict(ctx context.Context, arg SaveZoneClaimConflictParams) error {
	_, err := q.db.ExecContext(ctx, saveZoneClaimConflict,
		arg.ChildZoneID,
		arg.ChildClaimID,
		arg.ChildBaseVersion,
		arg.ParentZoneID,
		arg.ParentClaimID,
		arg.ParentVersion,
		arg.CandidateContentHash,
	)
	return err
}

const saveZoneEntityConflict = `-- name: SaveZoneEntityConflict :exec
INSERT INTO zone_knowledge_conflicts
    (child_zone_id, knowledge_kind, child_knowledge_id, child_base_version,
     child_candidate_number, parent_zone_id, parent_knowledge_id, parent_version)
SELECT ?1, 'entity', ?2,
       ?3, v.candidate_number,
       ?4, ?5, ?6
FROM knowledge_versions v
WHERE v.zone_id = ?1 AND v.knowledge_kind = 'entity'
  AND v.knowledge_id = ?2
  AND v.version = ?3 AND v.candidate_number > 0
  AND v.content_hash = ?7
ON CONFLICT DO NOTHING
`

type SaveZoneEntityConflictParams struct {
	ChildZoneID          string
	ChildEntityID        string
	ChildBaseVersion     int64
	ParentZoneID         string
	ParentEntityID       string
	ParentVersion        int64
	CandidateContentHash []byte
}

func (q *Queries) SaveZoneEntityConflict(ctx context.Context, arg SaveZoneEntityConflictParams) error {
	_, err := q.db.ExecContext(ctx, saveZoneEntityConflict,
		arg.ChildZoneID,
		arg.ChildEntityID,
		arg.ChildBaseVersion,
		arg.ParentZoneID,
		arg.ParentEntityID,
		arg.ParentVersion,
		arg.CandidateContentHash,
	)
	return err
}

const saveZoneRelationConflict = `-- name: SaveZoneRelationConflict :exec
INSERT INTO zone_knowledge_conflicts
    (child_zone_id, knowledge_kind, child_knowledge_id, child_base_version,
     child_candidate_number, parent_zone_id, parent_knowledge_id, parent_version)
SELECT ?1, 'relation', ?2,
       ?3, v.candidate_number,
       ?4, ?5, ?6
FROM knowledge_versions v
WHERE v.zone_id = ?1 AND v.knowledge_kind = 'relation'
  AND v.knowledge_id = ?2
  AND v.version = ?3 AND v.candidate_number > 0
  AND v.content_hash = ?7
ON CONFLICT DO NOTHING
`

type SaveZoneRelationConflictParams struct {
	ChildZoneID          string
	ChildRelationID      string
	ChildBaseVersion     int64
	ParentZoneID         string
	ParentRelationID     string
	ParentVersion        int64
	CandidateContentHash []byte
}

func (q *Queries) SaveZoneRelationConflict(ctx context.Context, arg SaveZoneRelationConflictParams) error {
	_, err := q.db.ExecContext(ctx, saveZoneRelationConflict,
		arg.ChildZoneID,
		arg.ChildRelationID,
		arg.ChildBaseVersion,
		arg.ParentZoneID,
		arg.ParentRelationID,
		arg.ParentVersion,
		arg.CandidateContentHash,
	)
	return err
}
